// GENERATED by scripts/anticipation/build_anticipation.py — see the docstring there.
// Do not hand-edit.
//
// The anticipation reel marquee (Figma 7142:29286): the sign that lights up around a reel still
// spinning while the board waits on a bonus scatter.
//
// Coordinates are in FRAME-WIDTH units from the frame's centre, both axes — the convention
// <WinCardLights> takes — so <Anticipation> sizes the whole sign off the width of a reel.

/** Width / height of the art. The frame is as wide as a reel; this is what makes it as tall. */
export const ANTICIPATION_ASPECT = 0.28943;

/** The dome's diameter, in frame widths, so the light stays in scale with the bulb under it. */
export const ANTICIPATION_BULB = 0.05819;

/**
 * Every bulb's centre, clockwise from the top-left corner. 20 down each side and 6 across
 * the top and bottom, corners shared — the count is not the design's, because the design's frame is
 * far wider for its height than a reel is and what carries over is the PITCH, not the number.
 */
export const ANTICIPATION_BULBS: [number, number][] = '-0.43103,-1.65871 -0.25862,-1.65871 -0.08621,-1.65871 0.08621,-1.65871 0.25862,-1.65871 0.43103,-1.65871 0.43103,-1.48411 0.43103,-1.30951 0.43103,-1.13491 0.43103,-0.96031 0.43103,-0.78571 0.43103,-0.61110 0.43103,-0.43650 0.43103,-0.26190 0.43103,-0.08730 0.43103,0.08730 0.43103,0.26190 0.43103,0.43650 0.43103,0.61110 0.43103,0.78571 0.43103,0.96031 0.43103,1.13491 0.43103,1.30951 0.43103,1.48411 0.43103,1.65871 0.25862,1.65871 0.08621,1.65871 -0.08621,1.65871 -0.25862,1.65871 -0.43103,1.65871 -0.43103,1.48411 -0.43103,1.30951 -0.43103,1.13491 -0.43103,0.96031 -0.43103,0.78571 -0.43103,0.61110 -0.43103,0.43650 -0.43103,0.26190 -0.43103,0.08730 -0.43103,-0.08730 -0.43103,-0.26190 -0.43103,-0.43650 -0.43103,-0.61110 -0.43103,-0.78571 -0.43103,-0.96031 -0.43103,-1.13491 -0.43103,-1.30951 -0.43103,-1.48411'
	.split(' ')
	.map((pair) => {
		const [x, y] = pair.split(',');
		return [Number(x), Number(y)];
	});

/**
 * Where each bulb sits in the run AROUND the frame, 0-1 — handed to <WinCardLights> as its chase
 * order. Its own default orders bulbs by their ANGLE about the centre, which is right for a sign
 * that is roughly as wide as it is tall and wrong for this one: nearly every bulb here is at some
 * angle near straight up or straight down, so a chase would light the two long rails as two lumps
 * instead of running round the sign.
 */
export const ANTICIPATION_PLACES: number[] = '0.00000 0.02063 0.04125 0.06188 0.08250 0.10313 0.12402 0.14491 0.16579 0.18668 0.20757 0.22846 0.24935 0.27023 0.29112 0.31201 0.33290 0.35379 0.37467 0.39556 0.41645 0.43734 0.45822 0.47911 0.50000 0.52063 0.54125 0.56188 0.58250 0.60313 0.62402 0.64491 0.66579 0.68668 0.70757 0.72846 0.74935 0.77023 0.79112 0.81201 0.83290 0.85379 0.87467 0.89556 0.91645 0.93734 0.95822 0.97911'.split(' ').map(Number);
