// GENERATED by scripts/balloons/build_balloons.py — edit that, not this.
//
// The balloon symbol as the six balloons it is made of, so the bunch can bob while the
// board idles and fly when it wins. Every number is a fraction of the 448x360 symbol
// frame, which is what makes one table serve every size the board draws a symbol at.
//
// Listed BACK TO FRONT, the design's own stacking.

export type Balloon = {
	key: string;
	/**
	 * The end of its string, as a fraction of the frame — NOT the middle of the balloon.
	 * This is what it hangs from and what it turns about; a balloon pivoted on its middle
	 * slides sideways instead of bobbing. Draw it anchored (0.5, 1) on this point.
	 */
	x: number;
	y: number;
	width: number;
	height: number;
	/** Radians it hangs at when nothing is happening — the angle the design drew it at. */
	rest: number;
};

export const BALLOONS: Balloon[] = [
	{ key: 'tpBalloonBlue', x: 0.4509, y: 0.5958, width: 0.2098, height: 0.4778, rest: -0.5236 },
	{ key: 'tpBalloonBlue', x: 0.4877, y: 0.8485, width: 0.2455, height: 0.5611, rest: -0.5236 },
	{ key: 'tpBalloonGreen', x: 0.5946, y: 0.6221, width: 0.2254, height: 0.5139, rest: 0.3316 },
	{ key: 'tpBalloonOrange', x: 0.4904, y: 0.6138, width: 0.2522, height: 0.5778, rest: 0.0175 },
	{ key: 'tpBalloonOrange', x: 0.5078, y: 0.8613, width: 0.2522, height: 0.5778, rest: 0.5236 },
	{ key: 'tpBalloonPink', x: 0.4978, y: 0.8583, width: 0.2902, height: 0.6611, rest: -0.0000 },
];
