// GENERATED by scripts/board/build_board_frame.py. Do not hand-edit.
//
// How the board frame sits over the reel grid.
//
// ART is the exported drawing. ART_GRID is the opening inside its neon line, and that opening IS
// the gameplay rect: <BoardFrame> scales the drawing so the two coincide, which is why the reels
// land inside the frame instead of under it, and why the dividers baked at fifths of the opening
// land on the cell boundaries.
//
// The opening is not centred in the drawing — the rail is thicker at the bottom — so GRID_OFFSET_*
// carries the difference. Drop it and the whole board sits a few pixels high.

export const ART = { width: 1462, height: 966 };
export const ART_GRID = {
	left: 42.2,
	top: 36.8,
	right: 1418.3,
	bottom: 925.3,
};

export const FRAME_OVER_GRID_X = ART.width / (ART_GRID.right - ART_GRID.left);
export const FRAME_OVER_GRID_Y = ART.height / (ART_GRID.bottom - ART_GRID.top);

export const GRID_OFFSET_X = 0.5 - (ART_GRID.left + ART_GRID.right) / 2 / ART.width;
export const GRID_OFFSET_Y = 0.5 - (ART_GRID.top + ART_GRID.bottom) / 2 / ART.height;

/**
 * The corner to clip the grid at, as a fraction of its width — how deep the drawn corners bite into
 * the opening at their deepest. It is deliberately the LARGEST radius that still stays under the
 * rail: clip any rounder and the park shows through the board's corners, and any squarer is hidden
 * by the rail above anyway. Not BOARD_CORNER_RADIUS, which is the shape features are masked to.
 */
export const GRID_RADIUS = 0.04064;
