// GENERATED by scripts/coaster/build_coaster.py — edit that, not this.
//
// The coaster car in pieces, so the family in the back row can wave. Every number is a
// fraction of the 448x360 symbol frame, which is what lets one table serve every size the
// board draws a symbol at.
//
// An arm is a SHOULDER and a turn about it: `x`/`y` are the shoulder in the frame, the
// anchor is that same point in the arm's own art, and `rest` is the angle the artist drew
// it at. Adding to `rest` swings the arm; nothing else has to move with it.

export type CoasterArm = {
	key: string;
	/** The shoulder, as a fraction of the symbol frame: what the arm turns about. */
	x: number;
	y: number;
	width: number;
	height: number;
	/** The same shoulder, as a fraction of the arm's own art. */
	anchorX: number;
	anchorY: number;
	/** Radians it rests at — the pose in the drawing. */
	rest: number;
	/**
	 * Whether this arm draws over the car rather than under it. The mother's crosses the red
	 * loop and has to; the father's ends inside his own shoulder and wants to be hidden there.
	 */
	front: boolean;
};

export const COASTER_ARMS: CoasterArm[] = [
	{ key: 'tpCoasterArmFather', x: 0.3372, y: 0.3544, width: 0.1109, height: 0.1618, anchorX: 0.8960, anchorY: 0.9293, rest: 0.1047, front: false },
	{ key: 'tpCoasterArmMother', x: 0.6913, y: 0.4393, width: 0.1109, height: 0.1618, anchorX: 0.1029, anchorY: 0.9293, rest: 0.0349, front: true },
];
