// GENERATED by scripts/coaster-sign/build_coaster_sign.py — edit that, not this.
//
// The MEGA COASTER scatter's moving parts: the marquee bolted to the pavilion's face, and the two
// words written on it. The pavilion itself never moves and ships as one house.
//
// Every number is a fraction of the 448x360 symbol frame, which is what makes one table serve every
// size the board draws a symbol at. See <MegaCoaster>.

export type CoasterSignPiece = {
	/** The middle of the DRAWING in the frame: what the part turns and scales about. */
	x: number;
	y: number;
	width: number;
	height: number;
	/**
	 * That same point as a fraction of the part's own art, for the sprite's anchor. The exports
	 * carry a margin, and a different one each, so this is not 0.5.
	 */
	anchorX: number;
	anchorY: number;
};

export const COASTER_SIGN_PARTS: Record<'sign' | 'mega' | 'coaster', CoasterSignPiece> = {
	sign: {
		x: 0.5031,
		y: 0.5137,
		width: 0.6339,
		height: 0.5222,
		anchorX: 0.5014,
		anchorY: 0.4837,
	},
	mega: {
		x: 0.502,
		y: 0.443,
		width: 0.3482,
		height: 0.1472,
		anchorX: 0.4929,
		anchorY: 0.4999,
	},
	coaster: {
		x: 0.502,
		y: 0.5905,
		width: 0.4576,
		height: 0.1861,
		anchorX: 0.497,
		anchorY: 0.5011,
	},
};

/**
 * The three flags flying from the pavilion's towers, cut off it so they can fly.
 *
 * `x`/`y` are the SEAM — the middle of the cloth where it meets its mast — because that is the one
 * point of a flag that does not move, and `anchorX`/`anchorY` put a sprite's origin there. The mast
 * itself stays on the building.
 */
export const COASTER_FLAGS: Record<'left' | 'centre' | 'right', CoasterSignPiece> = {
	left: {
		x: 0.2746,
		y: 0.2625,
		width: 0.0536,
		height: 0.0806,
		anchorX: 0,
		anchorY: 0.431,
	},
	centre: {
		x: 0.529,
		y: 0.1319,
		width: 0.0737,
		height: 0.0889,
		anchorX: 0,
		anchorY: 0.4219,
	},
	right: {
		x: 0.7701,
		y: 0.2625,
		width: 0.0558,
		height: 0.0806,
		anchorX: 0,
		anchorY: 0.431,
	},
};
