// GENERATED by scripts/coaster-driver/build_coaster_driver.py — edit that, not this.
//
// The Mega Coaster bumper car in pieces, so the duck driving it can drive. Every number is
// a fraction of the 256x256 frame the Spine cart is packed into, which is what lets the
// loose rig and the vomit clip be the same cart at the same size on the same ground line.
//
// A wheel is a wheel: `radius` is the radius it is DRAWN at, so <CoasterDriver> can roll it
// by the distance the cart has travelled rather than by a clock. A head is hung on a neck:
// `x`/`y` are that neck in the frame, the anchor is the same point in the head's own art,
// and turning about it nods the head instead of sliding it off the body.

export type CoasterDriverPart = {
	key: string;
	/** The centre, as a fraction of the frame — or the pivot, where the part has one. */
	x: number;
	y: number;
	width: number;
	height: number;
};

/** A part that turns about a point of its own, given as a fraction of its texture. */
export type CoasterDriverJoint = CoasterDriverPart & { anchorX: number; anchorY: number };

export const COASTER_DRIVER_BODY: CoasterDriverPart = { key: 'coasterDriverBody', x: 0.4219, y: 0.7340, width: 0.7031, height: 0.3317 };

/** Hung on the neck: `x`/`y` are the neck in the frame, the anchor is it in the head's art. */
export const COASTER_DRIVER_HEAD: CoasterDriverJoint = { key: 'coasterDriverHead', x: 0.3980, y: 0.6504, width: 0.2180, height: 0.2174, anchorX: 0.4800, anchorY: 0.9400 };

/** Both wheels, and the radius they are drawn at: rolling is distance / radius. */
export const COASTER_DRIVER_WHEEL_RADIUS = 0.0439;
export const COASTER_DRIVER_WHEELS: CoasterDriverPart[] = [
	{ key: 'coasterDriverWheel', x: 0.6152, y: 0.8857, width: 0.0879, height: 0.0879 },
	{ key: 'coasterDriverWheel', x: 0.2285, y: 0.8857, width: 0.0879, height: 0.0879 },
];

/** The headlamp's GLASS — there is no lamp art: <CoasterDriver> lights this rectangle. */
export const COASTER_DRIVER_LAMP = { x: 0.7581, y: 0.7849, width: 0.0196, height: 0.0610 };
