// GENERATED by scripts/congrats/build_congrats.py. Do not hand-edit.
//
// Layout for the redesigned congratulations panel (Figma 6909:9366), and the centres of the marquee
// bulbs painted into its art so <WinCardLights> can light them.
//
// Every number is a fraction of the PANEL's box, so <CongratsPanel> needs one size and everything
// else follows — the ring's bulbs included, which is why they are stored in panel space rather than
// in the ring's own.

const points = (packed: string): [number, number][] =>
	packed.split(' ').map((pair) => {
		const [x, y] = pair.split(',');
		return [Number(x), Number(y)];
	});

export type PartRect = { x: number; y: number; w: number; h: number };

/** The panel art's own aspect, for sizing it without stretching. */
export const CONGRATS_PANEL_ASPECT = 0.99824;

export const CONGRATS_PARTS = {
	ring: { x: 0.49823, y: 0.56790, w: 0.37456, h: 0.56085 },
	p: { x: 0.50442, y: 0.55644, w: 0.15724, h: 0.23457 },
	/**
	 * Centre of the medallion's bulb circle, which is NOT its box centre — the ring art hangs
	 * a taller star off the bottom than the top. Mount the ring container here and offset the
	 * sprite, so the chase runs about the circle the bulbs actually sit on.
	 */
	ringCentre: { x: 0.49823, y: 0.54872 },
};

/** Bulb tint, averaged from the art: lilac on the frame, amber on the medallion. */
export const CONGRATS_PANEL_BULB_COLOUR = 0xff8fd6;
export const CONGRATS_RING_BULB_COLOUR = 0xffe67c;

/** Frame rails and the amount well. */
export const CONGRATS_PANEL_BULBS: [number, number][] = points(
	'0.9346,0.2831 0.0582,0.2847 0.9386,0.4561 0.9378,0.5845 0.5000,0.7943 0.0622,0.4107 0.0574,0.4984 0.0598,0.6667 0.9123,0.8900 0.9354,0.2424 0.0630,0.2480 0.0630,0.6300 0.0622,0.4553 0.0638,0.8230 0.0574,0.3708 0.9362,0.3708 0.9378,0.4131 0.9378,0.3285 0.0630,0.3238 0.9346,0.6244 0.0614,0.7105 0.9378,0.5439 0.7002,0.0558 0.8006,0.0558 0.3030,0.0566 0.9362,0.7105 0.3573,0.0478 0.6451,0.0486 0.0829,0.0574 0.9147,0.0574 0.7384,0.0598 0.2265,0.0606 0.2576,0.0606 0.0606,0.5375 0.7695,0.0606 0.3876,0.7935 0.9354,0.7616 0.6691,0.7879 0.7217,0.7879 0.0622,0.5837 0.2751,0.7911 0.0510,0.7265 0.6746,0.9322 0.3238,0.9322 0.0638,0.7608 0.2233,0.7935 0.8780,0.0375 0.9410,0.6683 0.9338,0.7982 0.9107,0.9019 0.1093,0.0670 0.9410,0.4952 0.0638,0.7990 0.1451,0.8158 0.0893,0.9019 0.7767,0.7935 0.8533,0.0718 0.0662,0.1842 0.0901,0.0837 0.5096,0.0303 0.4282,0.9474 0.5574,0.7903 0.8907,0.9370 0.3309,0.7911 0.6140,0.7911 0.4442,0.7911 0.5510,0.9258 0.9370,0.8238 0.0901,0.8413 0.8716,0.8325 0.1292,0.8325 0.8429,0.9195 0.2137,0.9338 0.9482,0.2073 0.9298,0.8804 0.4968,0.9003 0.1443,0.9067 0.1579,0.9195 0.5829,0.0263 0.7305,0.9362 0.4187,0.0311 0.1093,0.9370 0.2703,0.9354 0.8676,0.8947 0.9322,0.1842 0.4490,0.0287 0.7823,0.9346 0.1252,0.0367 0.4506,0.9258 0.0869,0.8724 0.1707,0.7919 0.1475,0.0726 0.8700,0.8636 0.4992,0.9274 0.8660,0.9290 0.1348,0.9314 0.1292,0.8636 0.5550,0.0303 0.9466,0.7273 0.2002,0.0558 0.1316,0.8947 0.8533,0.8142 0.8285,0.7919 0.9545,0.2265 0.6164,0.9402 0.0694,0.8788 0.0566,0.0789 0.8971,0.8772 0.9426,0.0766 0.4944,0.0455 0.5056,0.0096 0.6324,0.0526 0.0455,0.2265 0.5383,0.0399 0.9514,0.8589 0.0463,0.1324 0.4944,0.9402 0.4785,0.0191 0.9147,0.0957 0.0949,0.0957',
);

/** The medallion ring, in panel space — mount inside the ring container with its centre as origin. */
export const CONGRATS_RING_BULBS: [number, number][] = points(
	'0.5754,0.6679 0.3666,0.6066 0.6288,0.6051 0.4203,0.6679 0.5765,0.4397 0.3680,0.5022 0.4587,0.6847 0.6299,0.5011 0.4565,0.4237 0.6083,0.4624 0.3903,0.4660 0.5385,0.4218 0.3874,0.6362 0.4222,0.4390 0.5363,0.6847 0.6069,0.6406',
);
