// GENERATED by scripts/congrats/build_congrats.py. Do not hand-edit.
//
// The tall congratulations marquee (Figma 7033:24761, bonus won) and the centres of the bulbs
// painted into its rail, so <WinCardLights> can light them.
//
// Distances are fractions of the marquee's WIDTH on BOTH axes — <WinCardLights> scales x and y by
// the single size it is given — with the origin at the art's centre.
//
// The bonus-COMPLETE screen is not here: it shares the marquee pad with the big-win cards, and that
// is generated by scripts/pad/build_pad.py into game/padMarquee.ts.

const points = (packed: string): [number, number][] =>
	packed.split(' ').map((pair) => {
		const [x, y] = pair.split(',');
		return [Number(x), Number(y)];
	});

export type MarqueeArt = {
	/** width / height of the art as the design draws it, for sizing it without stretching. */
	aspect: number;
	/** Bulb tint, averaged from the rail. */
	bulbColour: number;
	/**
	 * What the glow is sized off, in width units: the diameter of the bulb's bright core. On this
	 * art the bulbs are painted lit and fade into the rail, so the core is a good deal smaller than
	 * the disc a viewer would call the bulb.
	 */
	bulb: number;
	bulbs: [number, number][];
};

export const CONGRATS_MARQUEES: Record<string, MarqueeArt> = {
	tall: {
		aspect: 0.87298,
		bulbColour: 0xffdc4e,
		bulb: 0.01887,
		bulbs: points(
			'0.2441,0.4839 -0.1426,0.4800 0.4160,-0.0435 -0.4180,0.1606 0.0801,0.4810 -0.3564,0.4790 0.4209,-0.0991 -0.4180,0.3179 -0.4199,-0.1987 0.4180,0.2104 0.4131,-0.1978 -0.4160,0.2104 0.3770,-0.2349 -0.3770,-0.2319 -0.4072,0.4702 0.2422,-0.2905 -0.2402,-0.2866 -0.2852,-0.2788 0.2852,-0.2778 -0.3164,-0.2466 0.3125,-0.2446 -0.4238,-0.1460 0.4209,0.1597 -0.4238,0.0063 0.0205,0.4810 -0.0352,0.4810 0.4199,0.0522 -0.4229,0.0571 0.4170,0.1069 0.1934,0.4790 -0.4248,-0.0444 0.4209,-0.1509 -0.4229,-0.0942 0.4170,0.3599 -0.0869,0.4839 0.1367,0.4839 -0.4219,0.3706 -0.2998,0.4780 0.4082,0.4536 -0.1943,0.4849 0.4150,0.4058 0.3613,0.4839 0.1748,-0.3306 -0.1748,-0.3315 0.1211,-0.3433 0.4209,0.3052 0.2061,-0.2925 -0.1982,-0.2954 0.0000,-0.3569 0.0635,-0.3589 -0.0645,-0.3550 -0.2480,0.4839 -0.1260,-0.3511 -0.4229,0.2651 0.3018,0.4790 0.4180,0.2612 -0.4238,0.4214 -0.4189,0.1050 0.4180,0.0024',
		),
	},
};
