// GENERATED by scripts/congrats/build_congrats.py. Do not hand-edit.
//
// The tall congratulations marquee (Figma 7033:24761, bonus won) and the centres of the bulbs
// painted into its rail, so <WinCardLights> can light them.
//
// Distances are fractions of the marquee's WIDTH on BOTH axes — <WinCardLights> scales x and y by
// the single size it is given — with the origin at the art's centre.
//
// The bonus-COMPLETE screen is not here: it shares the marquee pad with the big-win cards, and that
// is generated by scripts/pad/build_pad.py into game/padMarquee.ts.

const points = (packed: string): [number, number][] =>
	packed.split(' ').map((pair) => {
		const [x, y] = pair.split(',');
		return [Number(x), Number(y)];
	});

export type MarqueeArt = {
	/** width / height of the art as the design draws it, for sizing it without stretching. */
	aspect: number;
	/** Bulb tint, averaged from the rail. */
	bulbColour: number;
	/**
	 * What the glow is sized off, in width units: the diameter of the bulb's bright core. On this
	 * art the bulbs are painted lit and fade into the rail, so the core is a good deal smaller than
	 * the disc a viewer would call the bulb.
	 */
	bulb: number;
	bulbs: [number, number][];
};

export const CONGRATS_MARQUEES: Record<string, MarqueeArt> = {
	tall: {
		aspect: 0.74203,
		bulbColour: 0xffdb4d,
		bulb: 0.01885,
		bulbs: points(
			'-0.1416,0.5713 0.2461,0.5752 0.0781,0.5742 0.4209,0.0000 -0.3564,0.5703 0.4160,0.0547 -0.4180,0.4111 -0.4219,0.2549 -0.4219,-0.1973 0.4150,0.1543 -0.4219,0.1543 -0.4209,-0.2471 -0.4229,0.1045 -0.4248,0.0537 0.4170,0.2031 0.4150,-0.2949 0.4170,0.2559 -0.4189,-0.1025 0.4170,-0.1514 0.4209,-0.2012 -0.4238,-0.1514 -0.4209,0.0049 -0.4238,-0.0469 0.4150,-0.0996 -0.4229,0.3096 0.4160,0.3047 -0.3047,0.5752 -0.0342,0.5742 0.0205,0.5723 0.1934,0.5713 0.1309,0.5713 -0.2451,0.5703 -0.1953,0.5752 -0.0869,0.5762 0.3594,0.5752 -0.4072,0.5635 0.4170,0.4043 0.4131,0.5518 -0.4238,0.5137 0.4150,0.4990 -0.4219,0.4648 0.4170,0.4541 -0.4160,-0.2969 0.2461,-0.3828 -0.2402,-0.3828 0.2861,-0.3750 -0.2861,-0.3750 0.0625,-0.4570 -0.0596,-0.4561 0.1201,-0.4404 -0.1982,-0.3945 -0.0020,-0.4570 0.1807,-0.4277 -0.1748,-0.4287 0.1992,-0.3926 -0.3154,-0.3438 0.3115,-0.3359 0.3770,-0.3320 -0.3779,-0.3311 -0.1260,-0.4473 0.4180,0.3555 -0.4229,0.3604 -0.4189,0.2051 0.4199,0.0996 0.3047,0.5742 0.4209,-0.0518 0.4170,-0.2451',
		),
	},
};
