// GENERATED by scripts/duck/build_duck.py — edit that, not this.
//
// The duck symbol in pieces, so it can blink about and beat its wings. Every number is a
// fraction of the 448x360 symbol frame, which is what makes one table serve every size the
// board draws a symbol at.
//
// DUCK_BODY is the bird with NEITHER wing on it. The far one was painted into the drawing
// and had to be cut off it, torso and all — see the script.

export type DuckPiece = {
	/** Centre, as a fraction of the symbol frame. */
	x: number;
	y: number;
	width: number;
	height: number;
};

export type DuckWing = DuckPiece & {
	/**
	 * The shoulder, as a fraction of the wing's own art: where it tucks under the body, and so
	 * the point it beats about. `x`/`y` above are this point in the frame, not the art's centre.
	 */
	anchorX: number;
	anchorY: number;
	/** Radians it hangs at when nothing is happening — the angle the artist drew it at. */
	rest: number;
};

export type DuckEye = DuckPiece & {
	key: string;
	/**
	 * How far the iris may slide from the middle of its socket. Measured against the socket's
	 * own shape rather than its box, allowing the pupil to run under the eyelid the way a
	 * cartoon draws a glance — so these are the full range, safe to use to the end.
	 */
	roamX: number;
	roamY: number;
};

export const DUCK_BODY: DuckPiece = { x: 0.5413, y: 0.5375, width: 0.4933, height: 0.8417 };

/** The near wing, tucked at the flank nearest the viewer. */
export const DUCK_WING: DuckWing = { x: 0.3623, y: 0.6836, width: 0.1786, height: 0.2500, anchorX: 0.6584, anchorY: 0.6074, rest: 0.0349 };

/**
 * The far wing, raised and fanned over the far shoulder. Cut out of the body drawing, so it
 * is stored exactly as the artist left it and hangs at no angle of its own.
 */
export const DUCK_WING_FAR: DuckWing = { x: 0.6665, y: 0.6230, width: 0.1629, height: 0.3000, anchorX: 0.2432, anchorY: 0.4273, rest: 0 };

export const DUCK_EYES: DuckEye[] = [
	{ key: 'tpDuckIrisLeft', x: 0.3962, y: 0.3319, width: 0.0558, height: 0.0750, roamX: 0.0067, roamY: 0.0139 },
	{ key: 'tpDuckIrisRight', x: 0.5268, y: 0.3750, width: 0.0737, height: 0.0944, roamX: 0.0156, roamY: 0.0222 },
];
