/**
 * The DUCK YOUR LUCK scatter's two loose wings: where each sits on the symbol frame, and the point
 * it beats about.
 *
 * GENERATED by `scripts/duck-sign/build_duck_sign.py` — edit that, not this. The symbol ships as a
 * base (the duck, the sign and the wingtips gripping it) plus these two wings, so that a win can
 * flap them; drawing them at these coordinates behind the base reproduces the design exactly.
 * See <DuckSign>.
 *
 * All six numbers are fractions of the symbol FRAME, origin top-left, so they survive any change to
 * how big the symbol is drawn. `pivotX`/`pivotY` are in the same frame space, not in the wing's.
 */
export type DuckSignWing = {
	x: number;
	y: number;
	width: number;
	height: number;
	pivotX: number;
	pivotY: number;
};

export const DUCK_SIGN_WINGS: Record<'left' | 'right', DuckSignWing> = {
	left: {
		x: 0.0893,
		y: 0.4056,
		width: 0.4018,
		height: 0.4417,
		pivotX: 0.3112,
		pivotY: 0.6366,
	},
	right: {
		x: 0.5,
		y: 0.4056,
		width: 0.4018,
		height: 0.4417,
		pivotX: 0.6806,
		pivotY: 0.6355,
	},
};
