/**
 * The DUCK YOUR LUCK scatter's two loose wings: where each sits on the symbol frame, and the point
 * it beats about.
 *
 * GENERATED by `scripts/duck-sign/build_duck_sign.py` — edit that, not this. The symbol ships as a
 * base with NO wings in it — just the duck and the sign it holds — plus these two, so that the only
 * wings on screen are the ones that move. Drawing them at these coordinates behind the base
 * reproduces the design. See <DuckSign>.
 *
 * All six numbers are fractions of the symbol FRAME, origin top-left, so they survive any change to
 * how big the symbol is drawn. `pivotX`/`pivotY` are in the same frame space, not in the wing's, and
 * each is that wing's SHOULDER — the point where it meets the duck, which the sign hides.
 */
export type DuckSignWing = {
	x: number;
	y: number;
	width: number;
	height: number;
	pivotX: number;
	pivotY: number;
};

export const DUCK_SIGN_WINGS: Record<'left' | 'right', DuckSignWing> = {
	left: {
		x: 0.1272,
		y: 0.0194,
		width: 0.3638,
		height: 0.4722,
		pivotX: 0.4,
		pivotY: 0.42,
	},
	right: {
		x: 0.5089,
		y: 0.0194,
		width: 0.3638,
		height: 0.4722,
		pivotX: 0.6,
		pivotY: 0.42,
	},
};
