import type { SymbolBulb } from './symbolBulbs';

/**
 * The six lit fittings on the MEGA WILD plaque: a jewel on the funnel, one on each column, one on
 * the bottom bar, and the two headlamps.
 *
 * GENERATED by `scripts/mega-wild/build_mega_wild_bulbs.py` — edit that, not this. Found by their
 * GLASS, sized by the bezel proportion the drawing uses throughout, and filtered by the plaque's own
 * symmetry; see the script for why each of those is the honest measurement. Re-run it whenever the
 * plaque is re-exported.
 *
 * Ordered top-to-bottom then left-to-right, which is the order the chase runs in. `colour` is the
 * measured colour of each one's glass, so the purple jewels do not light amber.
 *
 * This is not in `symbolBulbs.ts` with the rest because there is no MEGA WILD board symbol to key it
 * off: the plaque is a full-reel overlay that 'W' happens to render as. <Board> picks it by sprite.
 */
export const MEGA_WILD_BULBS: SymbolBulb[] = [
	{ x: 0.4982, y: 0.2272, r: 0.0545, colour: 0xbf2ec7 },
	{ x: 0.2053, y: 0.4673, r: 0.0436, colour: 0xc032cc },
	{ x: 0.7875, y: 0.4664, r: 0.044, colour: 0xbd30cb },
	{ x: 0.201, y: 0.7166, r: 0.0529, colour: 0xfde372 },
	{ x: 0.501, y: 0.7093, r: 0.0433, colour: 0xfb7204 },
	{ x: 0.7951, y: 0.7167, r: 0.0533, colour: 0xfde372 },
];
