// GENERATED by scripts/pad/build_pad.py — see the README there. Do not hand-edit.
//
// The marquee PAD: the circus sign under the big-win cards and the bonus-complete screen.
//
// Everything here is in PAD-WIDTH units on BOTH axes with the origin at the pad's centre, which is
// the convention <WinCardLights> wants and what lets each screen size the sign with one number.

const points = (packed: string): [number, number][] =>
	packed.split(' ').map((pair) => {
		const [x, y] = pair.split(',');
		return [Number(x), Number(y)];
	});

/** Width / height of the art, so neither screen has to stretch it. */
export const PAD_ASPECT = 1.83448;

/**
 * The purple field inside the rail — where copy has to land. Measured down the CENTRE COLUMN, not
 * by bounding box: the silhouette is a cloud whose bottom lobes drop well below the middle, and a
 * bbox would promise height that nothing can be written in.
 */
export const PAD_FIELD = {
	top: -0.09398,
	bottom: 0.21617,
	left: -0.45451,
	right: 0.45451,
};

/** Half the field's usable height, and its middle — the two figures every screen places copy from. */
export const PAD_FIELD_CENTRE = 0.06109;
export const PAD_FIELD_HEIGHT = 0.31015;

/**
 * The bulb as the art draws it: an unlit cream disc. `size` is its diameter, so a glow can be sized
 * off the thing it is lighting rather than off a number that has to be re-tuned whenever the sign
 * is re-exported at a different width.
 */
export const PAD_BULB = { size: 0.01535, colour: 0xffc177 };

/** Every disc's centre. Nothing in the art is lit — <WinCardLights> is the lighting. */
export const PAD_BULBS: [number, number][] = points(
	'-0.00168,-0.10959 -0.05363,-0.10781 0.04915,-0.10760 -0.10331,-0.10357 0.09974,-0.10336 -0.15028,-0.09701 0.14810,-0.09690 -0.19642,-0.08750 0.19538,-0.08735 -0.23780,-0.07292 0.23679,-0.07292 -0.25358,-0.03780 0.25240,-0.03770 -0.28848,-0.01893 0.28765,-0.01903 -0.32868,-0.00847 0.32796,-0.00841 -0.33955,0.02848 0.33864,0.02862 -0.36564,0.05444 0.36526,0.05461 -0.40181,0.06660 0.40168,0.06669 -0.43811,0.07739 0.43809,0.07749 -0.46440,0.10297 0.46437,0.10299 -0.47400,0.13705 0.47344,0.13705 -0.45997,0.16975 0.45917,0.16999 -0.42591,0.18982 0.42471,0.19020 -0.11652,0.21325 0.11541,0.21360 -0.15700,0.21623 -0.07766,0.21548 0.07445,0.21563 0.15711,0.21686 -0.19844,0.22054 0.19874,0.22113 -0.40254,0.22544 -0.24068,0.22528 0.24067,0.22575 0.40152,0.22568 -0.28314,0.23182 0.28422,0.23238 -0.02981,0.23683 0.02850,0.23611 -0.32565,0.23863 0.32637,0.23929 -0.36851,0.24532 0.36868,0.24563',
);

/**
 * The pad as <WinCard>'s plate, in that card's space: fractions of the CARD width from the plate's
 * centre. Pinned so the pad's field centre lands where the Figma card put it, which is what keeps
 * the wordmark, the stars and the amount — all measured against that card — where they were.
 */
export const PAD_PLATE = { x: 0, y: -0.04041, w: 0.97985, h: 0.53413 };

/**
 * Where <WinCard>'s gold stars sit: the middle of a shoulder pocket, as pad units below the pad's
 * centre. Their SIDEWAYS place is the design's (`MARQUEE_STAR.x`); this is the height.
 *
 * Measured here rather than taken from the Figma card because the card was measured against a
 * different sign. Pinning by the field centre lines the two up down the middle column only, and at
 * the shoulders the design's height put the star hard against the bottom rail with a lobe of empty
 * purple over it. The row with the most room in the pocket this art actually draws is the seat.
 */
export const PAD_STAR_SEAT = 0.13571;
