// GENERATED by scripts/pad/build_pad.py — see the README there. Do not hand-edit.
//
// The marquee PAD: the circus sign under the big-win cards and the bonus-complete screen.
//
// Everything here is in PAD-WIDTH units on BOTH axes with the origin at the pad's centre, which is
// the convention <WinCardLights> wants and what lets each screen size the sign with one number.

const points = (packed: string): [number, number][] =>
	packed.split(' ').map((pair) => {
		const [x, y] = pair.split(',');
		return [Number(x), Number(y)];
	});

/** Width / height of the art, so neither screen has to stretch it. */
export const PAD_ASPECT = 1.78066;

/**
 * The purple field inside the rail — where copy has to land. Measured down the CENTRE COLUMN, not
 * by bounding box: the silhouette is a cloud whose bottom lobes drop well below the middle, and a
 * bbox would promise height that nothing can be written in.
 */
export const PAD_FIELD = {
	top: -0.10885,
	bottom: 0.22901,
	left: -0.49598,
	right: 0.49698,
};

/** Half the field's usable height, and its middle — the two figures every screen places copy from. */
export const PAD_FIELD_CENTRE = 0.06008;
export const PAD_FIELD_HEIGHT = 0.33786;

/**
 * The bulb as the art draws it: an unlit cream disc. `size` is its diameter, so a glow can be sized
 * off the thing it is lighting rather than off a number that has to be re-tuned whenever the sign
 * is re-exported at a different width.
 */
export const PAD_BULB = { size: 0.01604, colour: 0xffefa4 };

/** Every disc's centre. Nothing in the art is lit — <WinCardLights> is the lighting. */
export const PAD_BULBS: [number, number][] = points(
	'-0.09106,-0.13266 -0.04804,-0.13555 -0.00289,-0.13688 0.04036,-0.13576 0.08341,-0.13308 -0.13251,-0.12689 0.12843,-0.12723 -0.17292,-0.12101 0.17091,-0.12148 -0.21241,-0.11343 0.21136,-0.11408 -0.25022,-0.10275 0.25069,-0.10371 0.26627,-0.06779 -0.26546,-0.06649 -0.29835,-0.04914 0.29795,-0.04980 -0.33451,-0.03788 0.33476,-0.03907 -0.34338,-0.00317 0.34357,-0.00567 0.36574,0.02263 -0.36488,0.02434 -0.39877,0.03667 0.39895,0.03519 -0.43417,0.04786 0.43427,0.04721 -0.46263,0.07828 0.46195,0.07736 -0.47205,0.11791 0.47061,0.11610 0.45429,0.15261 -0.45537,0.15459 -0.42186,0.17715 0.41861,0.17669 -0.39483,0.21136 0.39276,0.21076 -0.13645,0.21860 -0.09763,0.21652 0.09750,0.21664 0.13740,0.21883 -0.17604,0.22240 0.17563,0.22346 -0.21545,0.22716 -0.06044,0.22536 0.06038,0.22470 0.21401,0.22833 -0.25401,0.23268 0.25280,0.23377 -0.29253,0.23879 0.29092,0.23973 0.36897,0.24346 -0.36835,0.24507 -0.32943,0.24619 -0.02434,0.24527 0.02357,0.24508 0.32951,0.24671',
);

/**
 * The pad as <WinCard>'s plate, in that card's space: fractions of the CARD width from the plate's
 * centre. Pinned so the pad's field centre lands where the Figma card put it, which is what keeps
 * the wordmark, the stars and the amount — all measured against that card — where they were.
 */
export const PAD_PLATE = { x: 0, y: -0.03942, w: 0.97985, h: 0.55027 };

/**
 * Where <WinCard>'s gold stars sit: the middle of a shoulder pocket, as pad units below the pad's
 * centre. Their SIDEWAYS place is the design's (`MARQUEE_STAR.x`); this is the height.
 *
 * Measured here rather than taken from the Figma card because the card was measured against a
 * different sign. Pinning by the field centre lines the two up down the middle column only, and at
 * the shoulders the design's height put the star hard against the bottom rail with a lobe of empty
 * purple over it. The row with the most room in the pocket this art actually draws is the seat.
 */
export const PAD_STAR_SEAT = 0.11407;
