// GENERATED by scripts/background/build_background.py — see the README there. Do not hand-edit.
//
// The base-game park: the plaza backdrop, the house that stands in it, and the lights on both.

const points = (packed: string): [number, number][] =>
	packed.split(' ').map((pair) => {
		const [x, y] = pair.split(',');
		return [Number(x), Number(y)];
	});

/** Width / height of the plaza art. */
export const PARK_ASPECT = 1197 / 670;

/**
 * Where the house is pinned in the plaza: its centre and width as fractions of the backdrop's DRAWN
 * width and height, so it rides the same cover transform the art does.
 *
 * It hangs off the left edge, and it has to: the plaza has a smaller house painted into that corner
 * and this one covers it. Moving it reveals the painted one. Solved from the bulb run rather than
 * from the drawing's edges, so a redraw with bigger flower beds does not slide the building.
 */
export const PARK_HOUSE = { x: 0.10535, y: 0.69840, w: 0.36338 };

/** Width / height of the house art, including whatever transparent margin it was drawn with. */
export const HOUSE_ASPECT = 1.23729;

/**
 * The bulb as the art draws it: a cream disc, painted already lit. `size` is its diameter, so a glow
 * can be sized off the thing it is lighting rather than off a number that has to be re-tuned
 * whenever the house is re-exported at another width.
 */
export const HOUSE_BULB = { size: 0.01573, colour: 0xffd08a };

/**
 * Every bulb on the gables and the door arch, in HOUSE-WIDTH units from the house's centre on both
 * axes — the convention <WinCardLights> wants.
 */
export const HOUSE_BULBS: [number, number][] = points(
	'0.06589,-0.31365 0.03886,-0.28188 0.09126,-0.28003 0.01080,-0.25033 0.11630,-0.24374 -0.01446,-0.21929 0.14096,-0.20773 -0.04176,-0.18660 0.16489,-0.17250 -0.06971,-0.15459 0.18721,-0.14002 -0.09722,-0.12285 0.20968,-0.10835 -0.11989,-0.09379 -0.24625,-0.08738 -0.19806,-0.08978 -0.15162,-0.09300 -0.29323,-0.08471 0.04969,-0.08607 -0.38378,-0.07722 -0.33958,-0.08131 0.00759,-0.07699 0.22779,-0.07893 0.08934,-0.07136 -0.02133,-0.04849 0.11498,-0.04051 -0.03269,-0.00260 0.12460,-0.00111 -0.03300,0.04351 0.12501,0.04270 0.12521,0.08647 -0.03278,0.09059 0.12486,0.13065 -0.03308,0.13858 0.12491,0.17355 -0.03314,0.18467',
);

/** The lit openings — the window and the door's fanlight — in the same units. */
export const HOUSE_PANES = [
	{ x: -0.25257, y: 0.03938, w: 0.06336, h: 0.11872 },
	{ x: 0.03596, y: -0.00285, w: 0.07306, h: 0.06393 },
];

/**
 * The plaza's lamp lanterns: the glass of each, as fractions of the backdrop's drawn width and
 * height, with `size` relative to the biggest. The two down the avenue are a third of the near
 * pair, which is what sells the distance.
 */
export const PARK_LAMPS = [
	{ x: 0.2210, y: 0.4857, size: 0.94 },
	{ x: 0.3758, y: 0.5473, size: 0.44 },
	{ x: 0.6325, y: 0.5666, size: 0.34 },
	{ x: 0.7061, y: 0.4232, size: 1.00 },
];
