/**
 * The popcorn symbol's loose kernels, and where they are thrown from.
 *
 * GENERATED by `scripts/popcorn/build_popcorn.py` — edit that, not this. The symbol ships as a
 * bucket with nothing flying around it plus these three kernel drawings, so that a win can pop them
 * out of the heap and let them fall; see <PopcornBurst>.
 *
 * Every number is a fraction of the symbol FRAME, origin top-left, so they survive any change to how
 * big the symbol is drawn. `x`/`y` are the centre of the crown of the heap and `spread` is its
 * half-width, which is the band kernels are launched across.
 */
export type PopcornMouth = { x: number; y: number; spread: number };
export type PopcornKernel = { key: string; width: number; height: number };

export const POPCORN_MOUTH: PopcornMouth = {
	x: 0.5022,
	y: 0.2167,
	spread: 0.1696,
};

export const POPCORN_KERNELS: PopcornKernel[] = [
	// 7052:7943
	{ key: 'tpPopcornKernelA', width: 0.1049, height: 0.1361 },
	// 7052:7945
	{ key: 'tpPopcornKernelB', width: 0.1161, height: 0.1472 },
	// 7052:7941
	{ key: 'tpPopcornKernelC', width: 0.0379, height: 0.0472 },
];
