// GENERATED by scripts/roller/build_roller.py — edit that, not this.
//
// The ROLLER WILDS scatter's three moving parts: the star that turns while the symbol just sits
// there, and the two words that pop against each other when it wins. Everything else about the
// symbol — the coaster emblem and the banner over it — never moves and ships as one sign.
//
// Every number is a fraction of the 448x360 symbol frame, which is what makes one table serve
// every size the board draws a symbol at. See <RollerWilds>.

export type RollerPiece = {
	/** The middle of the DRAWING in the frame: what the part turns and scales about. */
	x: number;
	y: number;
	width: number;
	height: number;
	/**
	 * That same point as a fraction of the part's own art, for the sprite's anchor. The exports
	 * carry a margin, and a different one each, so this is not 0.5.
	 */
	anchorX: number;
	anchorY: number;
};

export const ROLLER_PARTS: Record<'star' | 'roller' | 'wilds', RollerPiece> = {
	star: {
		x: 0.5098,
		y: 0.3975,
		width: 0.1897,
		height: 0.2361,
		anchorX: 0.4989,
		anchorY: 0.4952,
	},
	roller: {
		x: 0.5047,
		y: 0.5322,
		width: 0.3638,
		height: 0.1583,
		anchorX: 0.4975,
		anchorY: 0.4841,
	},
	wilds: {
		x: 0.4973,
		y: 0.6772,
		width: 0.4866,
		height: 0.2028,
		anchorX: 0.4945,
		anchorY: 0.4493,
	},
};
