/**
 * The four drifting clouds on the splash: which piece of art, where it sits, and how far and how
 * slowly it travels.
 *
 * GENERATED by `scripts/splash/build_splash_clouds.py` — edit that, not this. Every number is a
 * fraction of the 1680x936 splash frame except the two durations, each of which is one full
 * there-and-back. The horizontal and vertical periods differ, which is the whole trick: a cloud on
 * one period retraces the same line for ever, and on two it never repeats a pass.
 *
 * The bounds are on the cloud's TOP-LEFT, not its centre, because that is what CSS wants and this
 * table has exactly one consumer. They are nothing to do with the design's own cloud positions: the
 * frame those were composed in has been renumbered and is gone. See the script.
 */
export type SplashCloud = {
	key: string;
	/**
	 * The region this cloud may start in — top-left corner, as fractions of the frame. Pick anywhere
	 * inside and every one of the builder's tests still holds: clear of the rails, the treeline and
	 * the lockup at both ends of both of its drifts. It is a region and not a point because the page
	 * places the clouds afresh on every load; see the script for how the rectangle is found.
	 */
	xMin: number;
	xMax: number;
	yMin: number;
	yMax: number;
	width: number;
	/**
	 * Drawn height, as a fraction of the frame. The element sizes itself off `width` and its own
	 * aspect, so this is here for one reason: `rise` below has to be turned into a percentage of
	 * the cloud, and the page has no other way to know how tall the cloud came out.
	 */
	height: number;
	/** How far it drifts right of `x`, as a fraction of the frame width. */
	drift: number;
	seconds: number;
	/** How far it sinks below `y`, as a fraction of the frame height. */
	rise: number;
	/** Deliberately not a factor of `seconds`, so the path never closes. */
	riseSeconds: number;
};

export const SPLASH_CLOUDS: SplashCloud[] = [
	{ key: 'cloud-b', xMin: 0.0577, xMax: 0.1458, yMin: 0, yMax: 0.0128, width: 0.1298, height: 0.0491, drift: 0.0548, seconds: 55, rise: 0.0171, riseSeconds: 37 },
	{ key: 'cloud-c', xMin: 0.2464, xMax: 0.3083, yMin: 0.0203, yMax: 0.063, width: 0.2, height: 0.0919, drift: 0.0601, seconds: 47, rise: 0.0203, riseSeconds: 31 },
	{ key: 'cloud-d', xMin: 0.275, xMax: 0.394, yMin: 0, yMax: 0.0256, width: 0.3, height: 0.1378, drift: 0.0702, seconds: 61, rise: 0.0139, riseSeconds: 43 },
	{ key: 'cloud-a', xMin: 0.4548, xMax: 0.4857, yMin: 0.0203, yMax: 0.063, width: 0.2399, height: 0.0908, drift: 0.05, seconds: 73, rise: 0.0256, riseSeconds: 29 },
];
