/**
 * The ferris wheel, in pieces, and the geometry that puts it back together.
 *
 * GENERATED by `scripts/wheel/build_wheel.py` — edit that, not this. The symbol ships as a rim, a
 * hub, a pair of legs and its gondolas rather than one drawing, so that a win can spin the rim and
 * ride the gondolas round it; see <FerrisWheel>.
 *
 * Every number is a fraction of the symbol FRAME, origin top-left, so they survive any change to how
 * big the symbol is drawn. `x`/`y` are a piece's CENTRE.
 *
 * `WHEEL_AXLE` is the rim's own centre, which is what the wheel turns about. It is NOT the hub cap:
 * the cap is drawn a couple of pixels off centre, and turning the rim about it would walk the whole
 * wheel round in a small circle once a revolution.
 *
 * A GONDOLA HANGS; IT DOES NOT ORBIT. They all share `WHEEL_MOUNT` — one mounting radius, given
 * twice so the circle stretches with the symbol instead of going oval when the board squeezes it,
 * and one `hang`, the fixed drop from the mount to the car's centre. Each car carries only its
 * `angle`: where its mount sits round the wheel, in radians, clockwise from three o'clock.
 *
 * That split is what makes the wheel turnable. Measured straight off the design the cars sit at
 * radii from 101 to 136 on a 134-pixel rim, which looks like sloppy drawing and is not: the car at
 * the top is nearer the axle than the ones at the bottom by exactly twice the drop. Turning those
 * measured radii slides every car off the spoke it is bolted to.
 *
 * `WHEEL_CARS` has one entry per SPOKE, which is why there are more of them than the design draws.
 * The artist's five are unevenly spaced, around a bottom deliberately left empty, and that is a
 * property of a still: turned, they pile up in the legs, and spacing five of them evenly instead
 * leaves most of them hanging between spokes. Eight spokes take eight cars, cycling the four
 * colours drawn, and that is the only arrangement that is even and bolted down at once.
 *
 * `WHEEL_BULBS` is the exception to all of the above being about a wheel that turns: those six sit
 * on the LEGS, which stand still, so they are plain frame coordinates and the board lights them
 * with the same <SymbolBulbs> it points at every other marquee sign.
 */
import type { SymbolBulb } from './symbolBulbs';

export type WheelPiece = { key: string; x: number; y: number; width: number; height: number };
export type WheelMount = { radiusX: number; radiusY: number; hang: number };
export type WheelCar = { key: string; angle: number; width: number; height: number };

export const WHEEL_AXLE = {
	x: 0.5045,
	y: 0.4375,
};

export const WHEEL_RIM: WheelPiece = {
	key: 'tpWheelRim',
	x: 0.5045,
	y: 0.4375,
	width: 0.5848,
	height: 0.7361,
};

export const WHEEL_LEGS: WheelPiece = {
	key: 'tpWheelLegs',
	x: 0.5045,
	y: 0.6931,
	width: 0.4554,
	height: 0.4694,
};

export const WHEEL_HUB: WheelPiece = {
	key: 'tpWheelHub',
	x: 0.5089,
	y: 0.4333,
	width: 0.125,
	height: 0.1556,
};

/** The 6 bulbs down the legs, in chase order: down one leg and up the other. */
export const WHEEL_BULBS: SymbolBulb[] = [
	{ x: 0.4565, y: 0.5528, r: 0.0106 },
	{ x: 0.4196, y: 0.6583, r: 0.01 },
	{ x: 0.3783, y: 0.775, r: 0.0106 },
	{ x: 0.6283, y: 0.775, r: 0.0106 },
	{ x: 0.5882, y: 0.6583, r: 0.0106 },
	{ x: 0.5525, y: 0.5528, r: 0.0106 },
];

export const WHEEL_MOUNT: WheelMount = {
	radiusX: 0.2742,
	radiusY: 0.3412,
	hang: 0.0594,
};

export const WHEEL_CARS: WheelCar[] = [
	{ key: 'tpWheelCarOrange', angle: 0.7898, width: 0.1295, height: 0.1778 },
	{ key: 'tpWheelCarPurple', angle: 1.5773, width: 0.125, height: 0.1778 },
	{ key: 'tpWheelCarGreen', angle: 2.3606, width: 0.1272, height: 0.1806 },
	{ key: 'tpWheelCarBlue', angle: 3.1525, width: 0.1205, height: 0.1694 },
	{ key: 'tpWheelCarOrange', angle: 3.9379, width: 0.1295, height: 0.1778 },
	{ key: 'tpWheelCarPurple', angle: 4.7058, width: 0.125, height: 0.1778 },
	{ key: 'tpWheelCarGreen', angle: 5.476, width: 0.1272, height: 0.1806 },
	{ key: 'tpWheelCarBlue', angle: 6.2723, width: 0.1205, height: 0.1694 },
];
