/**
 * Where the W sits on the wild's plate.
 *
 * GENERATED by `scripts/wild/build_wild.py` — edit that, not this. The symbol ships as a bare gold
 * plate plus this letter, so that a win can pop the letter on its own; see <WildLetter>.
 *
 * `x`/`y` are the letter's CENTRE and all four numbers are fractions of the symbol FRAME, origin
 * top-left, so they survive any change to how big the symbol is drawn.
 */
export type WildLetter = { x: number; y: number; width: number; height: number };

export const WILD_LETTER: WildLetter = {
	x: 0.5056,
	y: 0.4944,
	width: 0.4774,
	height: 0.3985,
};
