// GENERATED by scripts/win-cards/build_marquee.py — see the README there. Do not hand-edit.
//
// Where every piece of the marquee win card sits (Figma 7013:9117).
//
// All coordinates are fractions of the CARD WIDTH — the width of the plate — with the origin
// at the plate's centre. One number sizes the whole assembly, and it is the plate rather than
// the confetti fan that lines up with the reels, which is why the plate is the unit.

export type PartRect = { x: number; y: number; w: number; h: number };

/** One loose scrap of the confetti fan. `area` is its pixel count, which is how heavy it falls. */
export type ConfettiPiece = PartRect & { area: number };

export type MarqueeTier = keyof typeof MARQUEE_TEXT;

/** The tent plate: the card itself, and the unit everything else is measured in. */
export const MARQUEE_PLATE: PartRect = { x: -0.00067, y: -0.02179, w: 0.97985, h: 0.58532 };

/** The tier wordmark, every tier fitted to the same cap height on the same centre. */
export const MARQUEE_TEXT = {
	sweet: { x: 0.01126, y: 0.06663, w: 0.71089, h: 0.38172 },
	wild: { x: 0.01126, y: 0.06663, w: 0.54561, h: 0.38172 },
	epic: { x: 0.01126, y: 0.06663, w: 0.57486, h: 0.38172 },
	mythic: { x: 0.01126, y: 0.06663, w: 0.71089, h: 0.38139 },
	legendary: { x: 0.01126, y: 0.06663, w: 0.71089, h: 0.3593 },
} as const satisfies Record<string, PartRect>;

/** The right-hand star. The left one is its mirror — see <WinCard>. */
export const MARQUEE_STAR: PartRect = { x: 0.34654, y: 0.13818, w: 0.06914, h: 0.06851 };

/** The amount plate hanging below the card. Drawn, not an image: it is a rounded rect. */
export const MARQUEE_AMOUNT: PartRect = { x: 0.00076, y: 0.37923, w: 0.61047, h: 0.18381 };

/**
 * The confetti scraps, biggest first. Only their art and `area` are used now: the card no
 * longer draws the design's static fan — <WinConfettiRain> falls them down the screen.
 */
export const MARQUEE_CONFETTI: ConfettiPiece[] = [
	{ x: -0.28192, y: -0.0257, w: 0.26986, h: 0.16482, area: 44814 },
	{ x: 0.29874, y: -0.02278, w: 0.21866, h: 0.11523, area: 31744 },
	{ x: -0.40954, y: 0.09901, w: 0.2779, h: 0.10794, area: 30744 },
	{ x: 0.3982, y: 0.09172, w: 0.24938, h: 0.11231, area: 30437 },
	{ x: -0.38211, y: -0.13655, w: 0.09726, h: 0.10794, area: 9091 },
	{ x: 0.38065, y: -0.15442, w: 0.09288, h: 0.10721, area: 8258 },
	{ x: 0.17222, y: -0.23647, w: 0.06362, h: 0.07147, area: 4087 },
	{ x: -0.07642, y: -0.26455, w: 0.06216, h: 0.06928, area: 4024 },
	{ x: -0.21098, y: -0.21532, w: 0.05192, h: 0.0671, area: 3432 },
	{ x: -0.47426, y: -0.05196, w: 0.06509, h: 0.05105, area: 3166 },
	{ x: 0.47426, y: -0.07821, w: 0.05924, h: 0.04813, area: 2752 },
	{ x: -0.36164, y: 0.27441, w: 0.05924, h: 0.04886, area: 2744 },
	{ x: 0.45159, y: 0.19346, w: 0.06216, h: 0.03719, area: 2687 },
	{ x: 0.36164, y: 0.27477, w: 0.05631, h: 0.04813, area: 2588 },
	{ x: -0.44939, y: 0.21935, w: 0.05631, h: 0.04668, area: 2430 },
];

/** Bulb centres painted into the plate art, for the glow drawn over them. */
export const MARQUEE_BULBS: [number, number][] = [
	[-0.2126, -0.0731],
	[-0.0272, 0.1964],
	[-0.2978, -0.0409],
	[0.41, 0.1797],
	[-0.4537, 0.1643],
	[-0.4134, 0.059],
	[0.0762, -0.1482],
	[-0.4134, 0.1797],
	[0.2025, 0.1978],
	[0.1635, 0.1938],
	[0.1306, -0.1448],
	[-0.4516, 0.0811],
	[0.0238, 0.1951],
	[0.2455, -0.0563],
	[-0.2535, -0.0563],
	[-0.0816, -0.1468],
	[0.2488, 0.2018],
	[-0.0809, 0.179],
	[0.0782, 0.1743],
	[-0.1924, -0.1147],
	[-0.2146, 0.2052],
	[-0.1649, 0.1938],
	[-0.1259, 0.1884],
	[0.449, 0.1596],
	[-0.1649, -0.1348],
	[0.1185, 0.1891],
	[0.4671, 0.116],
	[-0.1279, -0.1428],
	[0.2085, -0.0764],
	[0.0212, -0.1643],
	[0.2925, 0.2186],
	[-0.2952, 0.2192],
	[-0.2999, 0.0067],
	[0.2925, 0.0067],
	[0.3361, 0.0355],
	[-0.3858, 0.2152],
	[-0.3643, 0.0436],
	[-0.0299, -0.1623],
	[-0.3442, 0.2306],
	[-0.3422, 0.0302],
	[0.3388, 0.2313],
	[0.3758, 0.0436],
	[-0.2569, 0.2112],
	[0.3825, 0.2132],
	[-0.4711, 0.1173],
	[0.4127, 0.0577],
	[0.4483, 0.0811],
	[0.2979, -0.0369],
	[0.1904, -0.12],
	[0.0816, -0.1629],
	[0.0332, -0.1515],
	[-0.3126, -0.0476],
	[-0.1508, -0.1274],
	[-0.0594, -0.1703],
	[-0.0111, 0.1884],
	[-0.0453, -0.1522],
	[0.0071, -0.173],
	[-0.2233, -0.0543],
	[-0.0662, -0.1495],
	[-0.0561, 0.1737],
	[-0.4255, 0.0436],
	[-0.0091, -0.1737],
	[0.0514, -0.169],
	[0.3093, -0.0476],
	[-0.1488, -0.1488],
	[-0.0843, -0.1656],
	[-0.0984, -0.1435],
	[-0.1051, 0.1716],
	[0.1743, -0.1126],
	[-0.1951, 0.1857],
	[-0.2636, -0.0416],
	[-0.234, 0.1931],
	[0.0494, 0.1743],
	[-0.3261, 0.0349],
	[-0.4597, 0.067],
	[0.1091, 0.1723],
	[-0.1911, -0.0912],
	[-0.3744, 0.0295],
	[-0.1931, 0.2085],
	[-0.2287, -0.0771],
];
