// GENERATED by scripts/win-cards/build_marquee.py — see the README there. Do not hand-edit.
//
// Where every piece of the marquee win card sits (Figma 7013:9117).
//
// All coordinates are fractions of the CARD WIDTH — the width of the plate — with the origin
// at the plate's centre. One number sizes the whole assembly, and it is the plate rather than
// the confetti fan that lines up with the reels, which is why the plate is the unit.
//
// The plate itself is not here: the card sits on the shared marquee pad, generated by
// scripts/pad/build_pad.py into game/padMarquee.ts.

export type PartRect = { x: number; y: number; w: number; h: number };

/** One loose scrap of the confetti fan. `area` is its pixel count, which is how heavy it falls. */
export type ConfettiPiece = PartRect & { area: number };

export type MarqueeTier = keyof typeof MARQUEE_TEXT;

/** The tier wordmark, every tier fitted to the same cap height on the same centre. */
export const MARQUEE_TEXT = {
	sweet: { x: 0.01126, y: 0.06663, w: 0.71089, h: 0.38172 },
	wild: { x: 0.01126, y: 0.06663, w: 0.54561, h: 0.38172 },
	epic: { x: 0.01126, y: 0.06663, w: 0.57486, h: 0.38172 },
	mythic: { x: 0.01126, y: 0.06663, w: 0.71089, h: 0.38139 },
	legendary: { x: 0.01126, y: 0.06663, w: 0.71089, h: 0.3593 },
} as const satisfies Record<string, PartRect>;

/**
 * The right-hand star. The left one is its mirror — see <WinCard>.
 *
 * ONLY x, w AND h ARE USED. The height comes from `PAD_STAR_SEAT` instead: this y was
 * measured against a plate the game no longer draws, and on the pad it seats the star
 * against the pocket's bottom rail. See the note by STAR_BOXES in build_marquee.py.
 */
export const MARQUEE_STAR: PartRect = { x: 0.34654, y: 0.13818, w: 0.06914, h: 0.06851 };

/** The amount plate hanging below the card. Drawn, not an image: it is a rounded rect. */
export const MARQUEE_AMOUNT: PartRect = { x: 0.00076, y: 0.37923, w: 0.61047, h: 0.18381 };

/**
 * The confetti scraps, biggest first. Only their art and `area` are used now: the card no
 * longer draws the design's static fan — <WinConfettiRain> falls them down the screen.
 */
export const MARQUEE_CONFETTI: ConfettiPiece[] = [
	{ x: -0.28192, y: -0.0257, w: 0.26986, h: 0.16482, area: 44814 },
	{ x: 0.29874, y: -0.02278, w: 0.21866, h: 0.11523, area: 31744 },
	{ x: -0.40954, y: 0.09901, w: 0.2779, h: 0.10794, area: 30744 },
	{ x: 0.3982, y: 0.09172, w: 0.24938, h: 0.11231, area: 30437 },
	{ x: -0.38211, y: -0.13655, w: 0.09726, h: 0.10794, area: 9091 },
	{ x: 0.38065, y: -0.15442, w: 0.09288, h: 0.10721, area: 8258 },
	{ x: 0.17222, y: -0.23647, w: 0.06362, h: 0.07147, area: 4087 },
	{ x: -0.07642, y: -0.26455, w: 0.06216, h: 0.06928, area: 4024 },
	{ x: -0.21098, y: -0.21532, w: 0.05192, h: 0.0671, area: 3432 },
	{ x: -0.47426, y: -0.05196, w: 0.06509, h: 0.05105, area: 3166 },
	{ x: 0.47426, y: -0.07821, w: 0.05924, h: 0.04813, area: 2752 },
	{ x: -0.36164, y: 0.27441, w: 0.05924, h: 0.04886, area: 2744 },
	{ x: 0.45159, y: 0.19346, w: 0.06216, h: 0.03719, area: 2687 },
	{ x: 0.36164, y: 0.27477, w: 0.05631, h: 0.04813, area: 2588 },
	{ x: -0.44939, y: 0.21935, w: 0.05631, h: 0.04668, area: 2430 },
];

