import type { RawSymbol, SymbolState, SymbolName } from './types';

// Cells are WIDER than tall so the 7×7 grid matches the blue board-pad's ~1.21 aspect and the
// magnetic symbol art (328×264 ≈ 1.24) reads bigger. Positions/magnet math all derive from these.
export const SYMBOL_W = 114;
export const SYMBOL_H = 94;
export const SYMBOL_SIZE = SYMBOL_H;
export const BOARD_GRID_OFFSET_Y = 0;
export const BOARD_DIMENSIONS = { x: 7, y: 7 };
export const BOARD_SIZES = {
	width: SYMBOL_W * BOARD_DIMENSIONS.x,
	height: SYMBOL_H * BOARD_DIMENSIONS.y,
};

export const BACKGROUND_RATIO = 1920 / 1080;
export const PORTRAIT_BACKGROUND_RATIO = 1242 / 2208;
const PORTRAIT_RATIO = 800 / 1422;
const LANDSCAPE_RATIO = 1600 / 900;
const DESKTOP_RATIO = 1422 / 800;
const DESKTOP_HEIGHT = 800;
const LANDSCAPE_HEIGHT = 900;
const PORTRAIT_HEIGHT = 1422;
export const DESKTOP_MAIN_SIZES = { width: DESKTOP_HEIGHT * DESKTOP_RATIO, height: DESKTOP_HEIGHT };
export const LANDSCAPE_MAIN_SIZES = {
	width: LANDSCAPE_HEIGHT * LANDSCAPE_RATIO,
	height: LANDSCAPE_HEIGHT,
};
export const PORTRAIT_MAIN_SIZES = {
	width: PORTRAIT_HEIGHT * PORTRAIT_RATIO,
	height: PORTRAIT_HEIGHT,
};

export const PAY_SYMBOLS: SymbolName[] = ['H1', 'H2', 'H3', 'H4', 'L1', 'L2', 'L3', 'L4'];
export const PREMIUM_SYMBOLS: SymbolName[] = ['H1', 'H2', 'H3', 'H4'];
export const LOW_SYMBOLS: SymbolName[] = ['L1', 'L2', 'L3', 'L4'];

const baseRows: RawSymbol[][] = [
	['H1', 'H2', 'H3', 'H4', 'L1', 'L2', 'L3'],
	['L4', 'H1', 'H2', 'H3', 'H4', 'L1', 'L2'],
	['L3', 'L4', 'H1', 'H2', 'H3', 'H4', 'L1'],
	['L2', 'L3', 'L4', 'H1', 'H2', 'H3', 'H4'],
	['L1', 'L2', 'L3', 'L4', 'H1', 'H2', 'H3'],
	['H4', 'L1', 'L2', 'L3', 'L4', 'WILD', 'H1'],
	['H3', 'H4', 'L1', 'L2', 'L3', 'L4', 'L4'],
].map((row) =>
	row.map((name) => ({
		name: name as SymbolName,
		wild: name === 'WILD',
		magnet: false,
		scatter: name === 'SCATTER',
	})),
);

export const INITIAL_BOARD = baseRows.map((row) => [...row]);
export const INITIAL_SYMBOL_STATE: SymbolState = 'static';

// Calibrated against the Version2 board render (green-chip core = 0.413 of cell pitch in the
// design; 0.92 measured 0.412 with the canvas-composited art), then taken down 5% on the user's
// final pass once the pads/gaps matched — the design's own symbols vary per piece, and slightly
// smaller read better across the set.
export const SYMBOL_SIZE_RATIOS = {
	premium: { width: 0.875, height: 0.875 },
	low: { width: 0.875, height: 0.875 },
	special: { width: 0.93, height: 0.93 },
	multiplierWild: { width: 0.93, height: 0.93 },
} as const;

// Per-asset compensation for padding baked into the ART FILE. The idle symbol art is heavily
// padded (washer is 0.55 content by width, bolt 0.71 by height), so at a shared cell ratio the
// symbols floated in a lot of empty space. This multiplies the class ratio so the ARTWORK grows to
// a consistent size while the cell, its border and the grid are untouched.
//
// Targets stay below 1.0 (0.86w x 0.84h of the cell) so content never reaches the border, and the
// table only ever contains values > 1 — this pass enlarges, it never shrinks anything.
// Generated by scripts/measure-symbol-padding.py (target 0.90w x 0.87h of the cell).
export const SYMBOL_PAD_SCALE: Record<string, number> = {
};

// Generated by scripts/measure-symbol-head.py — fractions of the sprite box from its centre.
export const SYMBOL_HEAD_OFFSET: Record<string, { x: number; y: number }> = {
	wolfTile: { x: 0.03, y: -0.146 },            // core 19% of mask
	wolfTileMobile: { x: 0.026, y: -0.139 },     // core 19% of mask
	wolfTileLand: { x: 0.027, y: -0.138 },       // core 18% of mask
	kTile: { x: -0.034, y: -0.104 },             // core 18% of mask
	wolfWinTileLand: { x: 0.029, y: -0.096 },    // core 17% of mask
	wolfWinTile: { x: 0.034, y: -0.095 },        // core 19% of mask
	wolfWinTileMobile: { x: 0.03, y: -0.092 },   // core 17% of mask
	kTileMobile: { x: -0.028, y: -0.088 },       // core 22% of mask
	kTileLand: { x: -0.028, y: -0.088 },         // core 21% of mask
	kWinTile: { x: 0.022, y: -0.084 },           // core 19% of mask
	kWinTileLand: { x: 0.021, y: -0.079 },       // core 20% of mask
	kWinTileMobile: { x: 0.022, y: -0.077 },     // core 21% of mask
	squirrelTile: { x: -0.074, y: -0.068 },      // core 19% of mask
	squirrelTileMobile: { x: -0.072, y: -0.066 },// core 19% of mask
	squirrelTileLand: { x: -0.069, y: -0.063 },  // core 19% of mask
	foxTileLand: { x: 0.036, y: 0.06 },          // core 12% of mask
	foxTileMobile: { x: 0.034, y: 0.056 },       // core 13% of mask
	qTile: { x: 0.043, y: -0.049 },              // core 18% of mask
	qWinTile: { x: -0.029, y: 0.043 },           // core 22% of mask
	foxTile: { x: 0.025, y: 0.043 },             // core 21% of mask
	qWinTileLand: { x: -0.026, y: 0.042 },       // core 19% of mask
	qWinTileMobile: { x: -0.028, y: 0.039 },     // core 22% of mask
	foxWinTileLand: { x: 0.019, y: 0.037 },      // core 15% of mask
	foxWinTile: { x: 0.02, y: 0.036 },           // core 20% of mask
	foxWinTileMobile: { x: 0.02, y: 0.033 },     // core 17% of mask
	squirrelWinTile: { x: -0.013, y: -0.032 },   // core 21% of mask
	squirrelWinTileLand: { x: -0.013, y: -0.03 },// core 21% of mask
	// Same offset as ...Land: bolt_mobile.webp is a half-res copy of bolt.webp, and these are
	// FRACTIONS of the sprite box, so resolution does not move the head.
	squirrelWinTileMobile: { x: -0.013, y: -0.03 },
	wild10xTile: { x: 0.008, y: 0.029 },         // core 21% of mask
	wild10xTileMobile: { x: 0.008, y: 0.029 },   // core 22% of mask
	qTileLand: { x: 0.027, y: -0.028 },          // core 18% of mask
	wild10xTileLand: { x: 0.007, y: 0.027 },     // core 20% of mask
	scatterCustom: { x: 0.005, y: -0.026 },      // core 22% of mask
	scatterWin: { x: 0.005, y: -0.026 },         // core 22% of mask
	aWinTileLand: { x: 0.031, y: -0.026 },       // core 20% of mask
	scatterCustomMobile: { x: 0.003, y: -0.025 },// core 18% of mask
	scatterWinMobile: { x: 0.003, y: -0.025 },   // core 18% of mask
	scatterTileLand: { x: 0.003, y: -0.025 },    // core 19% of mask
	wild2xTile: { x: 0.001, y: 0.024 },          // core 20% of mask
	wild2xTileLand: { x: 0.001, y: 0.024 },      // core 18% of mask
	wild2xTileMobile: { x: -0.0, y: 0.023 },     // core 19% of mask
	aWinTile: { x: 0.037, y: -0.021 },           // core 19% of mask
	wild4xTile: { x: 0.034, y: 0.021 },          // core 21% of mask
	wild5xTile: { x: 0.013, y: 0.02 },           // core 21% of mask
	aWinTileMobile: { x: 0.031, y: -0.019 },     // core 18% of mask
	wild4xTileMobile: { x: 0.033, y: 0.019 },    // core 20% of mask
	wild4xTileLand: { x: 0.034, y: 0.019 },      // core 20% of mask
	wild5xTileLand: { x: 0.013, y: 0.019 },      // core 21% of mask
	wild5xTileMobile: { x: 0.011, y: 0.018 },    // core 17% of mask
	aTileLand: { x: 0.006, y: -0.017 },          // core 14% of mask
	aTileMobile: { x: 0.004, y: -0.016 },        // core 11% of mask
	aTile: { x: 0.01, y: -0.015 },               // core 17% of mask
	wildTile: { x: 0.006, y: -0.014 },           // core 22% of mask
	wildWinTile: { x: 0.006, y: -0.014 },        // core 22% of mask
	wildTileMobile: { x: 0.004, y: -0.014 },     // core 21% of mask
	wildWinTileMobile: { x: 0.004, y: -0.014 },  // core 21% of mask
	wildTileLand: { x: 0.005, y: -0.014 },       // core 21% of mask
	qTileMobile: { x: 0.035, y: -0.012 },        // core 16% of mask
	wild7xTileLand: { x: 0.026, y: 0.012 },      // core 20% of mask
	wild7xTileMobile: { x: 0.026, y: 0.011 },    // core 21% of mask
	rabbitWinTileMobile: { x: 0.019, y: -0.011 },// core 19% of mask
	rabbitWinTileLand: { x: 0.019, y: -0.009 },  // core 21% of mask
	wild9xTileLand: { x: 0.026, y: 0.009 },      // core 19% of mask
	bearWinTile: { x: 0.02, y: 0.009 },          // core 21% of mask
	rabbitWinTile: { x: 0.022, y: -0.009 },      // core 21% of mask
	wild9xTileMobile: { x: 0.024, y: 0.007 },    // core 20% of mask
	wild7xTile: { x: 0.02, y: 0.006 },           // core 21% of mask
	wild9xTile: { x: 0.022, y: 0.005 },          // core 20% of mask
	bearWinTileLand: { x: 0.012, y: 0.004 },     // core 22% of mask
};

// Hand-tuned per-asset size nudges applied ON TOP of SYMBOL_PAD_SCALE, for art that still reads
// small once its padding is normalised. SYMBOL_PAD_SCALE equalises BOUNDING BOXES, and a slim
// diagonal object with a big box still looks smaller than a chunky one filling the same box.
// Kept separate from SYMBOL_PAD_SCALE because that table is generated and would overwrite these.
//
// NOTE ON NAMING: the symbol files are misnamed relative to their art — washer.webp is the purple
// SCREW, energy_screw.webp is the blue NUT, nut.webp is the gold WASHER. The asset KEY is the
// reliable identifier, so go by key here (kTile = purple screw), not by filename.
// Per-asset size of the stacked-cell burst, as a fraction of the cell's short side. Everything not
// listed keeps the default (see Board.svelte) and stays CENTRED on the cell; a listed asset gets
// this smaller burst AND is anchored on its head via SYMBOL_HEAD_OFFSET, so the crackle sits on the
// solid mass instead of washing over the tile. Only art whose head is a distinct lump benefits —
// shrinking every symbol's burst just made them all weaker.
export const SYMBOL_ZAP_OVERRIDE: Record<string, number> = {
	// kTile = purple screw, squirrelTile = green bolt. Both have a distinct head lump at one end
	// (the files are misnamed — the purple screw is washer.webp — so go by KEY, not filename).
	kTile: 0.66,
	kTileMobile: 0.66,
	kTileLand: 0.66,
	kWinTile: 0.66,
	kWinTileMobile: 0.66,
	kWinTileLand: 0.66,
	squirrelTile: 0.66,
	squirrelTileMobile: 0.66,
	squirrelTileLand: 0.66,
	squirrelWinTile: 0.66,
	squirrelWinTileLand: 0.66,
	squirrelWinTileMobile: 0.66,
};

export const SYMBOL_SIZE_OVERRIDE: Record<string, number> = {
	// kTile = purple screw, squirrelTile = green bolt. Both are slim diagonal shapes whose bounding
	// box is mostly empty corner, so they read smaller than the chunky symbols beside them.
	kTile: 1.1,
	kTileMobile: 1.1,
	kTileLand: 1.1,
	kWinTile: 1.1,
	kWinTileMobile: 1.1,
	kWinTileLand: 1.1,
	squirrelTile: 1.1,
	squirrelTileMobile: 1.1,
	squirrelTileLand: 1.1,
	squirrelWinTile: 1.1,
	squirrelWinTileLand: 1.1,
	squirrelWinTileMobile: 1.1,
};

// createReelForSpinning needs (BOARD_DIMENSIONS.y + 2) symbols per reel:
// one hidden above the mask and one hidden below.
export const SPIN_REEL_LENGTH = BOARD_DIMENSIONS.y + 2; // 9

const SPIN_OPTIONS_SHARED = {
	reelBounceBackSpeed: 0.15,
	reelSpinSpeedBeforeBounce: 4,
	reelPaddingMultiplierNormal: 1.2,
	reelPaddingMultiplierAnticipated: 3,
	reelSpinDelay: 145,
};

// Normal mode only (turbo/super-turbo use FAST/TURBO below). Speeds are 10% lower than the
// previous tuning (1.5 / 2.3 divided by 1.1), so the reels scroll 10% slower.
export const SPIN_OPTIONS_DEFAULT = {
	...SPIN_OPTIONS_SHARED,
	reelPreSpinSpeed: 1.36,
	reelSpinSpeed: 2.09,
	reelBounceSizeMulti: 0.3,
};

export const SPIN_OPTIONS_FAST = {
	...SPIN_OPTIONS_SHARED,
	reelPreSpinSpeed: 3,
	reelSpinSpeed: 4,
	reelBounceSizeMulti: 0.15,
};

export const SPIN_OPTIONS_TURBO = {
	...SPIN_OPTIONS_SHARED,
	reelPreSpinSpeed: 6,
	reelSpinSpeed: 7,
	reelBounceSizeMulti: 0.1,
	reelSpinDelay: 60,
};

// Normal-speed timings run ~69% slower than the original tuning (x1.3 applied twice) — the
// game felt too rushed at normal speed. Turbo (BOARD_MOTION_FAST) is unchanged.
export const BOARD_MOTION_DEFAULT = {
	spin: {
		dropRows: 12,
		fadeOutMs: 0,
		clearGapMs: 0,
		durationMs: 439,
		scaleFrom: 0.98,
		reelDelayMs: 122,
		rowDelayMs: 0,
		bounceMs: 163,
		overshootRows: 0.26,
		lockPulseMs: 0,
	},
	respin: {
		dropRows: 4.8,
		fadeOutMs: 203,
		clearGapMs: 118,
		durationMs: 642,
		scaleFrom: 0.9,
		reelDelayMs: 30,
		rowDelayMs: 30,
		bounceMs: 270,
		overshootRows: 0.18,
		lockPulseMs: 304,
	},
	pulse: {
		magnetMs: 507,
		freshMs: 575,
		winMs: 946,
	},
} as const;

export const BOARD_MOTION_FAST = {
	spin: {
		dropRows: 7,
		fadeOutMs: 0,
		clearGapMs: 0,
		durationMs: 140,
		scaleFrom: 0.96,
		reelDelayMs: 18,
		rowDelayMs: 0,
		bounceMs: 56,
		overshootRows: 0.2,
		lockPulseMs: 0,
	},
	respin: {
		dropRows: 2.2,
		fadeOutMs: 40,
		clearGapMs: 18,
		durationMs: 150,
		scaleFrom: 0.96,
		reelDelayMs: 8,
		rowDelayMs: 6,
		bounceMs: 60,
		overshootRows: 0.12,
		lockPulseMs: 72,
	},
	pulse: {
		magnetMs: 90,
		freshMs: 120,
		winMs: 140,
	},
} as const;

export const SCATTER_LAND_SOUND_MAP = {
	1: 'sfx_scatter_land_first',
	2: 'sfx_scatter_land_more',
	3: 'sfx_scatter_land_more',
	4: 'sfx_scatter_land_more',
	5: 'sfx_scatter_land_more',
} as const;
