"""Emit the generated layout + bulb table the win card component reads.

Everything is in CARD space (fractions of the card's box, origin at its centre) so the component
does one multiply per number and never has to know how the parts were cut.
"""

import json
import os
import pathlib

import numpy as np
from PIL import Image

from build_bulbs import panel_bulbs, ring_bulbs

BASE = os.path.dirname(os.path.abspath(__file__))
APP = pathlib.Path(__file__).resolve().parents[2]
PARTS = str(APP / 'static/assets/theme-park/v2/wins/parts')
OUT = str(APP / 'src/game/winCardParts.ts')
TIERS = ['sweet', 'wild', 'epic', 'mythic', 'legendary']

layout = json.load(open(os.path.join(BASE, 'layout.json')))

# The amount's own text box in each Figma frame, and that frame's panel box. The amount plate is not
# at the same height on every tier, so the y is taken per tier rather than sharing one measured
# constant. Only the y is used: x is centred on the panel, which the art is (a couple of the Figma
# text boxes sit a few px off-centre, which is the sample string, not the plate).
AMOUNT = {
    'sweet': ((440, 510, 321, 104), (290.5, 25.5, 620, 620)),
    'wild': ((440, 516, 321, 104), (280, 16, 641, 641)),
    'epic': ((438, 512, 301, 98), (277, 8, 646, 646)),
    'mythic': ((459, 519, 282, 104), (276, 13, 649, 649)),
    'legendary': ((462, 511, 282, 104), (285, 27, 631, 631)),
}


def to_card(rect, pts):
    """Part-local fractions -> card-space fractions, origin at the card centre."""
    return [
        (rect['x'] + (fx - 0.5) * rect['w'], rect['y'] + (fy - 0.5) * rect['h']) for fx, fy in pts
    ]


def pack(pts):
    return ' '.join(f'{x:.4f},{y:.4f}' for x, y in pts)


def bulb_colour(img, pts, r0=5, r1=12):
    """Mean bulb hue at full brightness — the tint for the glow drawn on top of it.

    Sampled from the HALO around each bulb, not its centre: every bulb has a white-hot core, so
    sampling the middle returns white for all five tiers and the glow washes the tier colour out.
    """
    a = np.array(img.convert('RGB')).astype(float)
    ring = [
        (dx, dy)
        for dx in range(-r1, r1 + 1)
        for dy in range(-r1, r1 + 1)
        if r0 * r0 <= dx * dx + dy * dy <= r1 * r1
    ]
    cols = []
    for fx, fy in pts:
        x, y = int(fx * img.width), int(fy * img.height)
        for dx, dy in ring:
            px, py = x + dx, y + dy
            if 0 <= px < img.width and 0 <= py < img.height:
                cols.append(a[py, px])
    c = np.array(cols).mean(0)
    c = c / max(c.max(), 1) * 255
    return (round(c[0]) << 16) | (round(c[1]) << 8) | round(c[2])


rows = []
for tier in TIERS:
    L = layout[tier]
    pb, pimg = panel_bulbs(f'{PARTS}/{tier}/panel.webp')
    rb, rimg = ring_bulbs(f'{PARTS}/{tier}/ring.webp')
    rows.append(
        {
            'tier': tier,
            'layout': L,
            'panelBulbs': pack(to_card(L['panel'], pb)),
            'ringBulbs': pack(to_card(L['ring'], rb)),
            'panelColour': bulb_colour(pimg, pb),
            'ringColour': bulb_colour(rimg, rb),
            'amountY': round(
                (AMOUNT[tier][0][1] + AMOUNT[tier][0][3] / 2
                 - (AMOUNT[tier][1][1] + AMOUNT[tier][1][3] / 2)) / AMOUNT[tier][1][3], 5),
        }
    )


coin = Image.open(f'{PARTS}/coin.webp')
COIN_ASPECT = round(coin.width / coin.height, 5)


def rect(r):
    return f"{{ x: {r['x']}, y: {r['y']}, w: {r['w']}, h: {r['h']} }}"


src = ['''// GENERATED by scripts/win-cards — see the README there. Do not hand-edit.
//
// The Theme Park win cards (Figma 6089:434 and the four tiers beside it) are built from loose
// images so the game can animate them apart: the panel, the tier wordmark, the medallion ring, the
// P badge and six coins. This table says where each piece sits and where its marquee bulbs are.
//
// All coordinates are fractions of the CARD's box with the origin at its centre, so a component
// multiplies by one card size and is done. `w`/`h` are fractions of the card too.

/** Centre and size of one part, in card-space fractions. */
export type PartRect = { x: number; y: number; w: number; h: number };

export type WinCardTier = {
	/** Panel, wordmark, medallion ring, centre badge. */
	panel: PartRect;
	text: PartRect;
	ring: PartRect;
	badge: PartRect;
	/** Six coins: indices 0-2 run down the left column, 3-5 down the right. */
	coins: PartRect[];
	/** Bulb centres painted into the panel art and the ring art, in card space. */
	panelBulbs: [number, number][];
	ringBulbs: [number, number][];
	/** The bulbs' own hue at full brightness, for tinting the glow drawn over them. */
	panelBulbColour: number;
	ringBulbColour: number;
	/** Centre of the amount plate, in card-space fractions of the card height. */
	amountY: number;
};

/** "0.12,-0.34 0.15,-0.34" -> [[0.12, -0.34], [0.15, -0.34]]. Packed to keep this file readable. */
const points = (packed: string): [number, number][] =>
	packed.split(' ').map((pair) => {
		const [x, y] = pair.split(',');
		return [Number(x), Number(y)];
	});

export const WIN_CARD_TIERS: Record<string, WinCardTier> = {''']

for r in rows:
    L = r['layout']
    coins = ',\n\t\t\t'.join(rect(c) for c in L['coins'])
    src.append(f"""	{r['tier']}: {{
		panel: {rect(L['panel'])},
		text: {rect(L['text'])},
		ring: {rect(L['ring'])},
		badge: {rect(L['badge'])},
		coins: [
			{coins},
		],
		amountY: {r['amountY']},
		panelBulbColour: 0x{r['panelColour']:06x},
		ringBulbColour: 0x{r['ringColour']:06x},
		panelBulbs: points(
			'{r['panelBulbs']}',
		),
		ringBulbs: points(
			'{r['ringBulbs']}',
		),
	}},""")

src.append(
    """};

/**
 * The coin art's width/height. Its Figma node boxes are NOT quite this ratio — that fill is cropped,
 * so the box is the crop rather than the art — and sizing the coin to the box stretched the disc
 * into an ellipse. The component takes its width from the box and its height from this.
 */
export const WIN_CARD_COIN_ASPECT = %s;

/** Asset keys follow the board keys <Win> already uses: winSweet -> 'sweet'. */
export const tierFromBoardKey = (boardKey: string) =>
	boardKey.replace(/^win/, '').toLowerCase() as keyof typeof WIN_CARD_TIERS;
"""
    % COIN_ASPECT
)

open(OUT, 'w').write('\n'.join(src))
print(f'{OUT}  {os.path.getsize(OUT) / 1024:.0f}KB')
for r in rows:
    print(
        f"{r['tier']:10s} panel #{r['panelColour']:06x} ({len(r['panelBulbs'].split()):3d})"
        f"  ring #{r['ringColour']:06x} ({len(r['ringBulbs'].split()):3d})"
    )
