#!/usr/bin/env python3
"""Emit SYMBOL_PAD_SCALE for game/constants.ts.

The idle symbol art carries a lot of transparent padding baked into the file (washer.webp is only
55% content by width), so a symbol drawn at a given cell ratio appears much smaller than the box it
occupies — that is the "air" inside the cells. Rather than enlarging the cell, each asset gets a
per-key multiplier that cancels ITS OWN padding, so only the artwork grows.

The scale is capped by BOTH axes against TARGET_*, which are held below 1.0 on purpose: content
must stay clear of the cell border, never touch it. It is also floored at 1.0 — this pass only ever
enlarges, so nothing that already reads well (wild is 0.92 content by height) gets shrunk.

Keyed by ASSET KEY, not symbol name: desktop / mobile / landscape art of the same symbol have
different padding (bolt.webp is 0.71 content by height, bolt_mobile.webp is 0.82), so one shared
factor per symbol would either under-correct desktop or overflow mobile.

Run from apps/magnetic:  python3 scripts/measure-symbol-padding.py
"""
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ASSETS_TS = ROOT / 'src' / 'game' / 'assets.ts'
STATIC = ROOT / 'static'

# Fractions of the CELL the artwork may occupy. Both leave a margin so nothing abuts the border.
TARGET_H = 0.84
TARGET_W = 0.86

# The multiplier is applied ON TOP OF the class ratio in SYMBOL_SIZE_RATIOS, so the drawn box is
# already BASE x the cell before any art is placed in it. Targeting a fraction of the cell without
# dividing this out under-corrects everything by ~8%.
BASE_SPECIAL = 0.98      # SYMBOL_SIZE_RATIOS.special / .multiplierWild
BASE_NORMAL = 0.92       # SYMBOL_SIZE_RATIOS.premium / .low


def base_for(key: str) -> float:
    k = key.lower()
    return BASE_SPECIAL if ('scatter' in k or 'wild' in k) else BASE_NORMAL

pat = re.compile(r"^\s*(\w+):\s*\{\s*type:\s*'sprite',\s*src:\s*'([^']+)'", re.M)
rows = []
for key, src in pat.findall(ASSETS_TS.read_text()):
    if 'symbols/magnetic' not in src:
        continue
    path = STATIC / src.split('?')[0].lstrip('./')
    if not path.exists():
        print(f'-- missing: {key} {path}')
        continue
    im = Image.open(path).convert('RGBA')
    bb = im.getbbox()
    if not bb:
        continue
    fw = (bb[2] - bb[0]) / im.width
    fh = (bb[3] - bb[1]) / im.height
    base = base_for(key)
    scale = min(TARGET_H / (base * fh), TARGET_W / (base * fw))
    if scale <= 1.001:          # already fills the box; leave it alone
        continue
    rows.append((key, round(scale, 3), fw, fh))

rows.sort(key=lambda r: -r[1])
print(f'// Generated by scripts/measure-symbol-padding.py '
      f'(target {TARGET_W:.2f}w x {TARGET_H:.2f}h of the cell).')
print('export const SYMBOL_PAD_SCALE: Record<string, number> = {')
for key, scale, fw, fh in rows:
    print(f'\t{key}: {scale},'.ljust(34) + f'// content {fw:.2f}w x {fh:.2f}h of file')
print('};')
print(f'\n-- {len(rows)} keys scaled', file=__import__('sys').stderr)
