#!/usr/bin/env python3
"""Emit SYMBOL_HEAD_OFFSET for game/constants.ts.

The stacked-cell burst is anchored on the symbol's HEAD (the bolt/screw cap), not on the cell
centre, so the electricity reads as gathering on the solid mass rather than washing over the whole
tile. The head is found by EROSION rather than hand-placed per symbol: repeatedly shrinking the
alpha mask dissolves thin parts (the shaft, the threads) first and leaves the thick end, whose
centroid is the anchor. Symbols with no thin part erode evenly and land near their own centre,
which is the right answer for them.

Offsets are fractions of the SPRITE BOX from its centre, +y down, so they scale with the cell.

Run from apps/magnetic:  python3 scripts/measure-symbol-head.py
"""
import re
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
ASSETS_TS = ROOT / 'src' / 'game' / 'assets.ts'
STATIC = ROOT / 'static'


def head_offset(path: Path):
    im = Image.open(path).convert('RGBA')
    alpha = im.split()[3]
    mask = np.asarray(alpha) > 8
    if not mask.any():
        return None
    full = mask.sum()
    cur = alpha
    best = mask
    # Erode until only the thickest ~22% of the shape survives; keep the last non-empty state so a
    # shape that vanishes in one step still yields its pre-collapse mass.
    for _ in range(24):
        cur = cur.filter(ImageFilter.MinFilter(5))
        m = np.asarray(cur) > 8
        if not m.any():
            break
        best = m
        if m.sum() <= full * 0.22:
            break
    ys, xs = np.where(best)
    h, w = mask.shape
    return (xs.mean() / w - 0.5, ys.mean() / h - 0.5, best.sum() / full)


pat = re.compile(r"^\s*(\w+):\s*\{\s*type:\s*'sprite',\s*src:\s*'([^']+)'", re.M)
rows = []
for key, src in pat.findall(ASSETS_TS.read_text()):
    if 'symbols/magnetic' not in src:
        continue
    p = STATIC / src.split('?')[0].lstrip('./')
    if not p.exists():
        continue
    r = head_offset(p)
    if r is None:
        continue
    dx, dy, frac = r
    # Sub-pixel offsets are noise; only record anchors that actually move the burst.
    if abs(dx) < 0.012 and abs(dy) < 0.012:
        continue
    rows.append((key, round(dx, 3), round(dy, 3), frac))

rows.sort(key=lambda r: -abs(r[2]))
print('// Generated by scripts/measure-symbol-head.py — fractions of the sprite box from its centre.')
print('export const SYMBOL_HEAD_OFFSET: Record<string, { x: number; y: number }> = {')
for key, dx, dy, frac in rows:
    print(f'\t{key}: {{ x: {dx}, y: {dy} }},'.ljust(46) + f'// core {frac * 100:.0f}% of mask')
print('};')
