<script lang="ts">
	import { Container, Graphics, Sprite } from 'pixi-svelte';

	// The BATTERY cell (L1), assembled live so its panel can have life in it.
	//
	// scripts/build-battery-art.py splits the Figma lockup into the housing with an EMPTY red panel
	// (battery.webp) and the battery character that sits in it (battery_cell.webp), and measures the
	// panel window the two runtime effects are confined to.
	//
	//   idle — a FEW balloons drift up behind the cell, at random sizes, most laps skipped entirely.
	//   win  — the cell pops on a beat and the panel fills with balloons.
	//
	// Balloons are drawn, not textured: Figma supplies them as a 2x2 and a 3x3 colour swatch, which
	// is a palette rather than artwork, and the brief asks for random big and small ones.
	//
	// Note the balloon layer is NORMAL blend, unlike the scatter's bubbles. Those glow inside a cyan
	// tube; these are objects on a bright red panel, and additive orange over rgb(192,12,1) clips
	// straight to white instead of reading as a balloon.
	//
	// One rAF per battery cell, drawing imperatively into captured Graphics — same pattern as
	// <SymbolWinFx> and <ScatterSymbol>, so no Svelte reactivity sits in the render path.

	type Props = {
		/** Housing texture key (desktop / mobile / landscape variant picked by the caller). */
		assetKey: string;
		x: number;
		y: number;
		width: number;
		height: number;
		alpha?: number;
		zIndex?: number;
		/** 0..1 — de-phases every cell so two batteries never pop or bubble in lockstep. */
		phase?: number;
		/** Win choreography: the cell pops and the panel crowds with balloons. */
		winning?: boolean;
	};
	const props: Props = $props();

	// Fractions of the symbol BOX, offsets from its centre. Generated by
	// scripts/build-battery-art.py — re-run it rather than nudging these.
	const PANEL = { dx: -0.003, dy: 0.0606, w: 0.3537, h: 0.4848 };
	const CELL = { w: 0.1533, h: 0.3394 };

	// Sampled off Figma nodes 9012:12109 / 9012:12111.
	const BALLOON_SMALL = 0xfa8444;
	const BALLOON_LARGE = 0xf32b02;

	const IDLE_BALLOONS = 7;
	const WIN_BALLOONS = 18;
	/** Fraction of laps a balloon actually appears on, per state. "Very few" in base. */
	const IDLE_APPEAR = 0.3;
	const WIN_APPEAR = 0.92;
	/** Win pop period, seconds. */
	const POP_P = 0.5;

	// NB: every draw helper works in CONTAINER-RELATIVE coordinates. The <Container> is already
	// translated to (props.x, props.y); adding those again throws the balloons a whole cell away.
	type G = {
		destroyed: boolean;
		clear: () => void;
		circle: (x: number, y: number, r: number) => unknown;
		ellipse: (x: number, y: number, rx: number, ry: number) => unknown;
		moveTo: (x: number, y: number) => void;
		lineTo: (x: number, y: number) => void;
		stroke: (s: object) => void;
		fill: (s: object) => void;
	};
	let ballG = $state<G | null>(null);
	let frontG = $state<G | null>(null);

	// Layer transforms, written by the rAF; the Sprites just bind them.
	let cellSX = $state(1);
	let cellSY = $state(1);
	let cellRot = $state(0);

	const W = $derived(props.width);
	const H = $derived(props.height);
	const P = $derived(props.phase ?? 0);

	/** Deterministic 0..1 from an integer — "random" that is stable per cell and per lap. */
	const hash = (n: number) => ((((n * 2654435761) % 1000) + 1000) % 1000) / 1000;

	// Balloons rise on independent loops. Size, lane and whether the balloon shows at all are
	// re-rolled EVERY LAP, which is what keeps them from reading as a fixed column of dots. Both
	// the size and the colour come from the same roll, so big balloons are the deep red swatch and
	// small ones the orange, exactly as the two Figma swatches are drawn.
	const drawBalloons = (g: G, t: number, count: number, appear: number, fast: boolean) => {
		const left = (PANEL.dx - PANEL.w / 2) * W;
		const right = (PANEL.dx + PANEL.w / 2) * W;
		const top = (PANEL.dy - PANEL.h / 2) * H;
		const bottom = (PANEL.dy + PANEL.h / 2) * H;
		const pw = right - left;
		const ph = bottom - top;

		for (let i = 0; i < count; i++) {
			const seed = i + 1;
			const speed = (fast ? 0.55 : 0.24) * (0.7 + hash(seed * 17) * 0.7);
			const cycle = t * speed + hash(seed * 31) + P;
			const turn = Math.floor(cycle);
			if (hash(turn * 7919 + seed * 104729) > appear) continue;

			const u = cycle - turn; // 0..1 up the panel
			const rise = 1 - u;
			const big = hash(turn * 6151 + seed * 3571);
			const r = pw * (0.035 + big * 0.075);
			const lane = hash(turn * 104729 + seed * 6151) - 0.5;
			// Clamped inside the window: the panel is a hole in the housing, and a balloon that
			// drifts past its edge draws on the metal frame.
			const bx = Math.max(
				left + r,
				Math.min(right - r, left + pw / 2 + lane * pw * 0.78 + Math.sin(u * 6.28 + seed) * pw * 0.04),
			);
			const by = Math.max(top + r, Math.min(bottom - r, top + rise * ph));
			const fade = Math.min(1, u * 5) * Math.min(1, rise * 4);

			g.circle(bx, by, r);
			g.fill({ color: big > 0.5 ? BALLOON_LARGE : BALLOON_SMALL, alpha: 0.92 * fade });
			// Rim + specular: the deep-red swatch is only a little brighter than the panel behind
			// it, so without these the large balloons vanish into the background.
			g.circle(bx, by, r);
			g.stroke({ width: r * 0.22, color: 0xffd9a0, alpha: 0.5 * fade });
			g.circle(bx - r * 0.32, by - r * 0.34, r * 0.3);
			g.fill({ color: 0xffffff, alpha: 0.65 * fade });
		}
	};

	$effect(() => {
		const t0 = performance.now();
		let raf = 0;
		const tick = () => {
			raf = requestAnimationFrame(tick);
			const t = (performance.now() - t0) / 1000;
			const win = props.winning === true;

			if (win) {
				// "Popping": a sharp squash-and-rebound on each beat rather than a smooth sine, so
				// it reads as the cell jolting with charge instead of breathing.
				const u = (t / POP_P + P) % 1;
				const kick = Math.exp(-u * 6) * Math.sin(u * 22);
				cellSX = 1 + kick * 0.16;
				cellSY = 1 - kick * 0.13;
				cellRot = kick * 0.06;
			} else {
				// Idle: barely-there breathing so the symbol is never completely static.
				const b = Math.sin(t * 1.3 + P * 6.28);
				cellSX = 1 + b * 0.012;
				cellSY = 1 - b * 0.012;
				cellRot = 0;
			}

			if (ballG?.destroyed) ballG = null;
			if (frontG?.destroyed) frontG = null;
			if (ballG) {
				ballG.clear();
				drawBalloons(
					ballG,
					t,
					win ? WIN_BALLOONS : IDLE_BALLOONS,
					win ? WIN_APPEAR : IDLE_APPEAR,
					win,
				);
			}
			if (frontG) {
				frontG.clear();
				if (win) {
					// A charge flash behind each pop, clipped to the panel so it does not wash the
					// metal frame.
					const u = (t / POP_P + P) % 1;
					const flash = Math.exp(-u * 7);
					for (let k = 0; k < 3; k++) {
						frontG.ellipse(
							PANEL.dx * W,
							PANEL.dy * H,
							(PANEL.w * W / 2) * (0.5 + 0.2 * k),
							(PANEL.h * H / 2) * (0.5 + 0.2 * k),
						);
						frontG.fill({ color: 0xffc24a, alpha: 0.1 * flash * (1 - k * 0.3) });
					}
				}
			}
		};
		raf = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(raf);
	});
</script>

<Container x={props.x} y={props.y} alpha={props.alpha ?? 1} zIndex={props.zIndex}>
	<!-- Housing, with an empty panel. -->
	<Sprite key={props.assetKey} anchor={0.5} width={W} height={H} />
	<!-- Balloons pass BEHIND the cell — normal blend, see the note at the top. -->
	<Graphics draw={(gr) => (ballG = gr as unknown as G)} />
	<Sprite
		key="batteryCell"
		anchor={0.5}
		x={PANEL.dx * W}
		y={PANEL.dy * H}
		width={CELL.w * W * cellSX}
		height={CELL.h * H * cellSY}
		rotation={cellRot}
	/>
	<Graphics blendMode="add" draw={(gr) => (frontG = gr as unknown as G)} />
</Container>
