<script lang="ts">
	import { Container, Graphics, Sprite } from 'pixi-svelte';

	// The CIRCUIT CHIP cell (L4), assembled live so the slime can ooze and the alien can react.
	//
	//   idle — the two slime blobs SAG: each stretches downward and settles, on its own period.
	//   win  — the board takes a POWER SURGE on a beat: the traces light, an arc jumps between the
	//          two screws at the peak of it, the alien jolts back and then leans in grinning, and
	//          the slime shivers loose.
	//
	// The first cut of the win was a scale sine, a mouth stretched to 1.55 x 1.95, and an arc firing
	// on its own unrelated 5.5 Hz clock. It read as unnatural, and each of those three is why: a sine
	// has no cause, a mouth at nearly twice its height is a rubber face rather than a grin, and light
	// that does not land on the same frame as its own lightning looks like two bugs. Everything below
	// hangs off ONE surge clock, so the board, the bolt and the alien all move on the same beat.
	//
	// The brief:
	//   "maybe make the green 9053:27249 move or drop animated in static mode, and in win make the
	//    alien zoom and become happy and maybe some lightning."
	//
	// "Become happy" is the reason the MOUTH is a separate texture at all. The face plate ships with
	// one small neutral mouth and there is no second drawing of a happy one, so the mouth is cut off
	// the plate (its hole filled with the plate's own green) and grown into a grin here. The eyes
	// squint at the same time — a wide mouth on round staring eyes reads as alarm, not delight.
	//
	// The face, both eyes and the mouth share one <Container> so the zoom moves the alien as a unit.
	// Scaling them separately would need every offset scaled by hand and the eyes would drift out of
	// the head on the first frame.
	//
	// scripts/build-circuit-art.py cuts the layers and emits every placement below.
	//
	// One rAF per cell, drawing imperatively into a captured Graphics — same pattern as
	// <SymbolWinFx>, <ScatterSymbol>, <BatterySymbol>, <CompassSymbol>, <MagnetSymbol>,
	// <EmDeviceSymbol>, <LightningSymbol>, <PortalSymbol>, <CoilSymbol> and <WildSymbol>.

	type G = {
		clear: () => void;
		moveTo: (x: number, y: number) => void;
		lineTo: (x: number, y: number) => void;
		circle: (x: number, y: number, r: number) => void;
		stroke: (o: Record<string, unknown>) => void;
		fill: (o: Record<string, unknown>) => void;
	};

	type Props = {
		/** Base texture key — the gold pins and the framed circuit board (layout variant). */
		assetKey: string;
		x: number;
		y: number;
		width: number;
		height: number;
		alpha?: number;
		zIndex?: number;
		/** 0..1 — de-phases every cell so two chips never sag or strike together. */
		phase?: number;
		/** Win choreography: the alien zooms and grins, and the board arcs. */
		winning?: boolean;
	};
	const props: Props = $props();

	// Fractions of the symbol BOX, offsets from centre. Generated by scripts/build-circuit-art.py.
	const FACE = { dx: 0.0059, dy: -0.0182, w: 0.3335, h: 0.3853 };
	const SLIME_A = { dx: 0.2136, dy: -0.3108, w: 0.1814, h: 0.1563 };
	const SLIME_B = { dx: -0.2691, dy: 0.2708, w: 0.0995, h: 0.1345 };
	/** The board's two screws -- where the win's current jumps from and to. */
	const SCREW_A = { dx: 0.1916, dy: -0.2326 };
	const SCREW_B = { dx: -0.1653, dy: 0.1926 };
	// Relative to the FACE's centre: these live inside the alien's container.
	const EYE_L = { dx: -0.0644, dy: 0.0109, w: 0.0878, h: 0.109 };
	const EYE_R = { dx: 0.0643, dy: 0.0109, w: 0.0878, h: 0.109 };
	const MOUTH = { dx: -0.0008, dy: 0.0924, w: 0.0813, h: 0.0582 };

	const SPARK = 0x9ef03a;
	const SPARK_HOT = 0xffffff;

	/** Slime sag: how much taller a blob gets at the bottom of its cycle, and the two periods. */
	const SAG = 0.16;
	const SAG_P_A = 3.7;
	const SAG_P_B = 4.9;
	/** How far a blob slides down while it stretches, as a fraction of its own height. */
	const SAG_DROP = 0.06;

	/** Seconds between power surges. Everything in the win is phased off this one clock. */
	const SURGE_P = 0.62;
	/** How fast a surge peaks, and how fast it dies. Attack must beat decay or it is a throb. */
	const SURGE_RISE = 26;
	const SURGE_FALL = 6.5;
	/** The surge's effect on the board: how bright the traces burn at the peak. */
	const BOARD_FLASH = 0.5;
	/** The alien's reaction: a recoil away from the jolt, then a lean back into it. */
	const RECOIL = 0.12;
	const LEAN_IN = 0.07;
	/** The grin. Modest on purpose -- see the note at the top about the rubber face. */
	const GRIN_X = 1.24;
	const GRIN_Y = 1.38;
	/** The eyes go WIDE on the jolt and settle to a squint; a permanent squint reads as asleep. */
	const SQUINT = 0.78;
	const EYE_WIDE = 0.42;
	/** How long the alien takes to break into (or drop) the grin. */
	const WIN_TAU = 0.14;
	/** Idle breath — small enough to be felt rather than seen. */
	const BREATH = 0.006;
	const BREATH_HZ = 0.38;
	/** Idle blink: the period, how long the eyes are shut, and how shut they get. */
	const BLINK_P = 4.3;
	const BLINK_DUR = 0.11;
	const BLINK_SHUT = 0.08;
	/** Arc: how long one bolt lasts and how many kinks it has. It fires ON the surge, not on a
	 *  clock of its own -- that mismatch is what made the old win look broken rather than powered. */
	const ARC_DUR = 0.1;
	const ARC_SEGMENTS = 11;
	/** How hard the surge shakes the slime loose, as a fraction of a blob's height. */
	const SLIME_SHIVER = 0.13;
	/** How far the bolt bows off the straight line between the screws, as a fraction of that line. */
	const ARC_BOW = 0.16;

	let sagA = $state(1);
	let sagB = $state(1);
	let alienScale = $state(1);
	let eyeSquash = $state(1);
	let grinX = $state(1);
	let grinY = $state(1);
	/** Additive ghost of the base: the traces lighting up. A tint can only darken. */
	let boardFlash = $state(0);

	let g: G | undefined;

	const W = $derived(props.width);
	const H = $derived(props.height);

	/** Deterministic per-strike jitter — the same strike index always kinks the same way. */
	const hash = (n: number) => ((((n * 2654435761) % 1000) + 1000) % 1000) / 1000;

	/**
	 * One bolt from screw to screw, re-kinked every strike.
	 *
	 * The kinks are tapered by sin(u * PI) so they vanish at both ends. Uniform jitter leaves the
	 * ends dancing off the screws, which reads as a loose wire rather than a discharge.
	 */
	const drawArc = (gr: G, strike: number, life: number) => {
		const x0 = SCREW_A.dx * W;
		const y0 = SCREW_A.dy * H;
		const x1 = SCREW_B.dx * W;
		const y1 = SCREW_B.dy * H;
		const len = Math.hypot(x1 - x0, y1 - y0) || 1;
		// Perpendicular to the screw-to-screw line: the bow has to leave that line, and the two
		// screws sit on a DIAGONAL, so bowing along y alone would barely show.
		const nx = -(y1 - y0) / len;
		const ny = (x1 - x0) / len;
		const spread = len * 0.075;

		const pts: Array<[number, number]> = [];
		for (let i = 0; i <= ARC_SEGMENTS; i++) {
			const u = i / ARC_SEGMENTS;
			const taper = Math.sin(u * Math.PI);
			const k = (hash(strike * 7919 + i * 104729) - 0.5) * 2 * spread * taper;
			const bow = taper * ARC_BOW * len * (strike % 2 ? 1 : -1);
			pts.push([
				x0 + (x1 - x0) * u + nx * (bow + k),
				y0 + (y1 - y0) * u + ny * (bow + k),
			]);
		}

		// Wide soft pass, then the hot core, so the bolt glows rather than ending in a hard edge.
		for (const [wide, color, alpha] of [
			[len * 0.045, SPARK, 0.24 * life],
			[len * 0.018, SPARK, 0.6 * life],
			[len * 0.006, SPARK_HOT, 0.95 * life],
		] as const) {
			gr.moveTo(pts[0][0], pts[0][1]);
			for (let i = 1; i < pts.length; i++) gr.lineTo(pts[i][0], pts[i][1]);
			gr.stroke({ width: wide, color, alpha, cap: 'round', join: 'round' });
		}

		// Both screws flare while the bolt is live.
		for (const [tx, ty] of [
			[x0, y0],
			[x1, y1],
		]) {
			for (let k = 3; k >= 1; k--) {
				gr.circle(tx, ty, len * 0.03 * k);
				gr.fill({ color: SPARK, alpha: (0.14 * life) / k });
			}
		}
	};

	$effect(() => {
		const t0 = performance.now();
		let raf = 0;
		// Carried across frames: how much of the win choreography is currently applied.
		let amp = 0;
		let last = 0;

		const tick = () => {
			raf = requestAnimationFrame(tick);
			const t = (performance.now() - t0) / 1000;
			const dt = Math.min(0.05, t - last);
			last = t;
			const p = props.phase ?? 0;
			const win = props.winning === true;

			amp += ((win ? 1 : 0) - amp) * (1 - Math.exp(-dt / WIN_TAU));

			// --- the slime ---------------------------------------------------------------------
			// A slow asymmetric cycle rather than a sine: slime gathers over a long moment and then
			// slumps. `u**2` on the falling half is what makes it slump rather than swing.
			const sag = (period: number, off: number) => {
				const u = ((t / period + off) % 1 + 1) % 1;
				const shape = u < 0.62 ? (u / 0.62) ** 2 : 1 - (u - 0.62) / 0.38;
				return 1 + SAG * shape;
			};
			// --- the surge ---------------------------------------------------------------------
			// The one clock the whole win hangs off. Fast attack, slower decay: that asymmetry is
			// what makes it read as a discharge instead of a throb, and it is the only reason a
			// surge has a "moment" the alien and the bolt can react to at all.
			const surgeN = Math.floor(t / SURGE_P + p);
			const su = ((t / SURGE_P + p) % 1 + 1) % 1;
			const age = su * SURGE_P;
			const surge = Math.min(1, age * SURGE_RISE) * Math.exp(-age * SURGE_FALL);

			sagA = sag(SAG_P_A, p) + amp * SLIME_SHIVER * surge;
			sagB = sag(SAG_P_B, p * 0.63 + 0.37) + amp * SLIME_SHIVER * 0.7 * surge;

			// --- the alien ---------------------------------------------------------------------
			// Recoil then lean: it flinches AWAY from the jolt on the frame the board lights, then
			// pushes back into it. A single scale ramp is the "zoom" that made this feel unnatural.
			const breath = BREATH * Math.sin(t * BREATH_HZ * Math.PI * 2 + p * 6.28);
			const settle = 1 - surge;
			alienScale = 1 + breath + amp * (LEAN_IN * settle - RECOIL * surge);
			// The grin arrives with the lean, not with the jolt: nobody smiles mid-flinch.
			grinX = 1 + amp * (GRIN_X - 1) * settle;
			grinY = 1 + amp * (GRIN_Y - 1) * settle;
			boardFlash = amp * BOARD_FLASH * surge;

			// The blink runs on the IDLE face only; on a win the eyes go wide on the jolt and settle
			// to a squint, and a blink through that would read as the eyes glitching.
			const u = ((t / BLINK_P + p) % 1 + 1) % 1;
			const shut = u < BLINK_DUR / BLINK_P ? 1 - Math.abs(u / (BLINK_DUR / BLINK_P) * 2 - 1) : 0;
			const blink = 1 - (1 - BLINK_SHUT) * shut;
			const winEye = 1 - amp * ((1 - SQUINT) * settle - EYE_WIDE * surge);
			eyeSquash = Math.min(blink, winEye);

			// --- the current -------------------------------------------------------------------
			const gr = g;
			if (!gr) return;
			gr.clear();
			if (amp < 0.02) return;
			// The bolt fires ON the surge and is gone well before the next one: an arc that never
			// goes out stops reading as electricity within about a second.
			if (age < ARC_DUR) {
				drawArc(gr, surgeN, (1 - age / ARC_DUR) * amp);
			}
		};
		raf = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(raf);
	});
</script>

<Container x={props.x} y={props.y} alpha={props.alpha ?? 1} zIndex={props.zIndex}>
	<!-- The pins and the framed circuit board. Still: the brief moves what sits ON it. -->
	<Sprite key={props.assetKey} anchor={0.5} width={W} height={H} />
	<!-- The traces lighting up under a surge: the same board drawn again additively. Kept mounted at
	     alpha 0 rather than {#if}-toggled -- it changes every frame of a win, and mounting a Pixi
	     child per frame costs more than an empty batched draw. -->
	<Sprite key={props.assetKey} anchor={0.5} blendMode="add" alpha={boardFlash} width={W} height={H} />
	<!-- The alien. Everything below moves with this container, which is what keeps the eyes and the
	     mouth in the head while the head zooms. -->
	<Container x={FACE.dx * W} y={FACE.dy * H} scale={alienScale}>
		<Sprite key="circuitFace" anchor={0.5} x={0} y={0} width={FACE.w * W} height={FACE.h * H} />
		<Sprite
			key="circuitEye"
			anchor={0.5}
			x={EYE_L.dx * W}
			y={EYE_L.dy * H}
			width={EYE_L.w * W}
			height={EYE_L.h * H * eyeSquash}
		/>
		<Sprite
			key="circuitEye"
			anchor={0.5}
			x={EYE_R.dx * W}
			y={EYE_R.dy * H}
			width={EYE_R.w * W}
			height={EYE_R.h * H * eyeSquash}
		/>
		<!-- Anchored near the TOP lip, not the centre: a grin opens downward from where the mouth
		     meets the face, and growing it about its own centre lifts it into the alien's nose. -->
		<Sprite
			key="circuitMouth"
			anchor={{ x: 0.5, y: 0.18 }}
			x={MOUTH.dx * W}
			y={(MOUTH.dy - MOUTH.h * 0.32) * H}
			width={MOUTH.w * W * grinX}
			height={MOUTH.h * H * grinY}
		/>
	</Container>
	<!-- The slime. Anchored at the TOP of each blob so a sag stretches it DOWNWARD; anchored at the
	     centre it would grow out of the frame's corner in both directions at once. -->
	<Sprite
		key="circuitSlimeA"
		anchor={{ x: 0.5, y: 0 }}
		x={SLIME_A.dx * W}
		y={(SLIME_A.dy - SLIME_A.h / 2) * H}
		width={SLIME_A.w * W}
		height={SLIME_A.h * H * sagA}
	/>
	<Sprite
		key="circuitSlimeB"
		anchor={{ x: 0.5, y: 0 }}
		x={SLIME_B.dx * W}
		y={(SLIME_B.dy - SLIME_B.h / 2) * H}
		width={SLIME_B.w * W}
		height={SLIME_B.h * H * sagB}
	/>
	<Graphics blendMode="add" draw={(gr) => (g = gr as unknown as G)} />
</Container>
