<script lang="ts">
	import { Container, Graphics, Sprite } from 'pixi-svelte';

	// The ASTRONAUT cell (L3), assembled live so the alien inside the helmet can move.
	//
	//   idle — the eyes LOOK AROUND: a fast flick to a new direction, then a long hold.
	//   win  — the alien JUMPS inside the helmet, on a beat: it stretches on the way up, leans hard
	//          (alternating sides, so two hops running are never the same frame twice), squashes on
	//          the landing, and throws a ring of light out of the visor as it lands. Its eyes go
	//          wide through the hop and follow the lean.
	//
	// The win used to be a scale sine plus a shake, and it read as boring -- which is what a sine
	// looks like: no beat, no anticipation, no impact. The routine below has all three, and the
	// light runs on the SAME beat, so it is one event rather than two effects that overlap.
	//
	// The gaze is deliberately not a sine. Eyes do not sweep; they saccade. A flick that takes ~0.1s
	// and then sits still for a second and a half is what reads as "looking around" — driving the
	// same offsets off a sine reads as the whole face wobbling.
	//
	// The head, both eyes and nothing else live in an inner <Container>, so the win's zoom and shake
	// are applied ONCE, to the alien as a unit. Scaling three sprites separately would need the eyes'
	// offsets scaled by hand and would drift out of the sockets the moment the head tilted.
	//
	// scripts/build-coil-art.py cuts the layers and emits every placement below. The head texture has
	// its eye sockets painted over with the face's own green, so a drifting eye can never expose a
	// hole; the cut is only good for a drift of about 2% of the symbol box, which is where GAZE_X and
	// GAZE_Y come from.
	//
	// One rAF per cell — same pattern as <SymbolWinFx>, <ScatterSymbol>, <BatterySymbol>,
	// <CompassSymbol>, <MagnetSymbol>, <EmDeviceSymbol>, <LightningSymbol>, <PortalSymbol> and
	// <WildSymbol>.

	type Props = {
		/** Base texture key — the helmet alone (desktop / mobile / landscape variant). */
		assetKey: string;
		x: number;
		y: number;
		width: number;
		height: number;
		alpha?: number;
		zIndex?: number;
		/** 0..1 — de-phases every cell so two astronauts never look the same way at the same time. */
		phase?: number;
		/** Win choreography: the head zooms and shakes. */
		winning?: boolean;
	};
	const props: Props = $props();

	// Fractions of the symbol BOX, offsets from centre. Generated by scripts/build-coil-art.py.
	// HEAD is dead centre of the helmet; the eyes are offsets from the HEAD's centre, because that
	// is the container they live in.
	const HEAD = { dx: 0.0, dy: 0.0, w: 0.392, h: 0.4827 };
	const EYE_R = { dx: -0.1054, dy: 0.0512, w: 0.1414, h: 0.217 };
	const EYE_L = { dx: 0.103, dy: 0.0399, w: 0.1439, h: 0.2326 };

	/** Where the gaze goes, in units of GAZE_X / GAZE_Y. Centre appears twice: an eye that never
	 *  rests forward looks nervous rather than curious. */
	const GAZE = [
		[0, 0],
		[1, -0.2],
		[-0.95, -0.1],
		[0, 0],
		[0.55, 0.55],
		[-0.7, 0.45],
		[0.2, -0.6],
		[-0.35, 0.6],
	];
	/** How far the pair may travel, as a fraction of the symbol box. Under the 0.02 the cut allows. */
	const GAZE_X = 0.013;
	const GAZE_Y = 0.009;
	/** Seconds each direction is held, and how fast the flick to the next one is. */
	const GAZE_HOLD = 1.45;
	const GAZE_TAU = 0.045;

	/** Seconds per win beat: one jump, one landing, one flash. */
	const BEAT = 0.78;
	/** The share of the beat spent in the air. The rest is the recoil. */
	const AIR = 0.72;
	/** How far the alien rises, as a fraction of the symbol box. */
	const HOP = 0.075;
	/** Stretch on the way up and squash on the landing, as scale deltas. */
	const STRETCH = 0.14;
	const SQUASH = 0.24;
	/** The lean at the top of a hop, radians. Alternates side per beat. */
	const LEAN = 0.34;
	/** Sideways travel into the lean, as a fraction of the symbol box. */
	const SWING = 0.03;
	/** How much wider the eyes go at the top of the hop. */
	const EYE_POP = 0.34;
	/** The light: the visor's steady burn, and the extra it throws on each landing. */
	const GLOW = 0.3;
	const GLOW_HIT = 0.55;
	/** Idle breath — small enough to be felt rather than seen, so the cell is never fully static. */
	const BREATH = 0.008;
	const BREATH_HZ = 0.42;
	/** How long the head takes to spin up into (or settle out of) the win. */
	const WIN_TAU = 0.16;

	let headScale = $state(1);
	let headScaleY = $state(1);
	let headTilt = $state(0);
	let headX = $state(0);
	let headY = $state(0);
	let eyeScale = $state(1);
	let gazeX = $state(0);
	let gazeY = $state(0);
	/** Additive ghost of the helmet: the light, which a tint alone can never make. */
	let visorFlash = $state(0);

	type G = {
		destroyed: boolean;
		clear: () => void;
		circle: (x: number, y: number, r: number) => unknown;
		fill: (s: object) => void;
		stroke: (s: object) => void;
	};
	let ringG = $state<G | null>(null);

	const W = $derived(props.width);
	const H = $derived(props.height);

	$effect(() => {
		const t0 = performance.now();
		let raf = 0;
		// Carried across frames: where the gaze actually is (it chases the target), and how much of
		// the win choreography is currently applied.
		let gx = 0;
		let gy = 0;
		let amp = 0;
		let last = 0;

		const tick = () => {
			raf = requestAnimationFrame(tick);
			const t = (performance.now() - t0) / 1000;
			const dt = Math.min(0.05, t - last);
			last = t;
			const p = props.phase ?? 0;
			const win = props.winning === true;

			amp += ((win ? 1 : 0) - amp) * (1 - Math.exp(-dt / WIN_TAU));

			// --- the beat ---------------------------------------------------------------------
			// One jump per BEAT. `air` is the arc, `land` the recoil after it, and `side` flips every
			// beat so two hops running are not the same frame twice.
			const beat = t / BEAT + p;
			const u = ((beat % 1) + 1) % 1;
			const side = Math.floor(beat) % 2 ? 1 : -1;
			// **0.65 flattens the top of the arc. A plain sine spends its time at the extremes and
			// rushes the middle; the alien needs to HANG up there for the lean to be legible.
			const air = u < AIR ? Math.sin((u / AIR) * Math.PI) ** 0.65 : 0;
			const land = u >= AIR ? Math.exp(-(u - AIR) * 22) : 0;

			// --- the gaze ---------------------------------------------------------------------
			// On a win the eyes go WIDE and follow the lean. They used to snap forward and hold, and
			// eyes locked dead ahead through a jump read as a stare -- half of why this was dull.
			const step = Math.floor(t / GAZE_HOLD + p * GAZE.length);
			const target = win
				? [side * air * 0.8, -air * 0.55]
				: GAZE[((step % GAZE.length) + GAZE.length) % GAZE.length];
			const k = 1 - Math.exp(-dt / GAZE_TAU);
			gx += (target[0] - gx) * k;
			gy += (target[1] - gy) * k;
			gazeX = gx * GAZE_X * W;
			gazeY = gy * GAZE_Y * H;
			eyeScale = 1 + amp * EYE_POP * air;

			// --- the head ---------------------------------------------------------------------
			// The breath runs all the time and the win rides on top of it, so the moment a win ends
			// the head is already doing something rather than freezing at the scale it stopped on.
			const breath = BREATH * Math.sin(t * BREATH_HZ * Math.PI * 2 + p * 6.28);
			// Volume is roughly conserved: narrow and tall in the air, wide and flat on the landing.
			// That is what sells a jump. Driving both axes the same way is a zoom -- which is exactly
			// what this was before.
			headScale = 1 + breath + amp * (-STRETCH * 0.55 * air + SQUASH * land);
			headScaleY = 1 + breath + amp * (STRETCH * air - SQUASH * 0.85 * land);
			headTilt = amp * side * (LEAN * air - LEAN * 0.35 * land);
			headX = amp * side * SWING * W * air;
			headY = amp * (-HOP * H * air + HOP * 0.22 * H * land);
			visorFlash = amp * (GLOW * air + GLOW_HIT * land);

			// --- the light --------------------------------------------------------------------
			if (ringG?.destroyed) ringG = null;
			const gr = ringG;
			if (gr) {
				gr.clear();
				if (amp > 0.02) {
					// A halo around the helmet that breathes with the hop...
					for (let i = 0; i < 4; i++) {
						gr.circle(0, 0, W * (0.34 + i * 0.055));
						gr.fill({ color: 0x8fe6ff, alpha: (0.09 * amp * (0.4 + air)) / (1 + i * 1.3) });
					}
					// ...and a ring thrown outward by the landing. It expands and thins at the same
					// time: a ring that only expands reads as a growing circle, not an impact.
					if (land > 0.02) {
						gr.circle(0, 0, W * (0.3 + 0.34 * (1 - land)));
						gr.stroke({ width: W * 0.05 * land, color: 0xffffff, alpha: 0.5 * amp * land });
					}
				}
			}
		};
		raf = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(raf);
	});
</script>

<Container x={props.x} y={props.y} alpha={props.alpha ?? 1} zIndex={props.zIndex}>
	<!-- The light, behind everything: a halo that breathes with the hop, a ring on each landing. -->
	<Graphics blendMode="add" draw={(gr) => (ringG = gr as unknown as G)} />
	<!-- The helmet. Still: the brief moves the alien inside it, not the suit. -->
	<Sprite key={props.assetKey} anchor={0.5} width={W} height={H} />
	<!-- The visor lighting up: the same helmet drawn again additively. Kept mounted at alpha 0
	     rather than {#if}-toggled -- it changes every frame of a win, and mounting a Pixi child per
	     frame costs more than an empty batched draw. -->
	<Sprite key={props.assetKey} anchor={0.5} blendMode="add" alpha={visorFlash} width={W} height={H} />
	<!-- The alien. Everything below moves with this container, which is what keeps the eyes in
	     their sockets while the head zooms and shakes. -->
	<Container
		x={HEAD.dx * W + headX}
		y={HEAD.dy * H + headY}
		scale={{ x: headScale, y: headScaleY }}
		rotation={headTilt}
	>
		<Sprite key="coilHead" anchor={0.5} x={0} y={0} width={HEAD.w * W} height={HEAD.h * H} />
		<Sprite
			key="coilEyeR"
			anchor={0.5}
			x={EYE_R.dx * W + gazeX}
			y={EYE_R.dy * H + gazeY}
			width={EYE_R.w * W * eyeScale}
			height={EYE_R.h * H * eyeScale}
		/>
		<Sprite
			key="coilEyeL"
			anchor={0.5}
			x={EYE_L.dx * W + gazeX}
			y={EYE_L.dy * H + gazeY}
			width={EYE_L.w * W * eyeScale}
			height={EYE_L.h * H * eyeScale}
		/>
	</Container>
</Container>
