<script lang="ts">
	import { Container, Graphics, Sprite } from 'pixi-svelte';

	import { GREEN_LIGHTS } from '../game/greenLights';

	// The COMPASS cell (H1), assembled from loose layers so the alien can live in the bezel.
	//
	// The MOTHERSHIP redesign changed what this symbol IS. It used to be a compass — a needle that
	// turned under an alien pivot cap — and there is no needle anywhere in the new part set. It is a
	// lit ring with an alien face sitting in it, N and S badges above and below, and four green arcs
	// around the rim. `compassNeedle` and the win spin-up went with the needle.
	//
	//   idle — the antennae sway on their own slow, unmatched cycles, the eye blinks now and then,
	//          the face breathes.
	//   win  — a RADAR SWEEP turns inside the bezel, the rim arcs chase it around, the face hops and
	//          the bezel flashes on each landing, and N and S shake in antiphase.
	//
	// The sweep is the answer to "the win animation is boring". The hop and the blinking arcs were
	// both small, local and on their own clocks; nothing crossed the symbol. A compass is a dial, so
	// the thing that reads at cell size is a beam going ROUND it -- and once there is a beam, the rim
	// arcs can chase it instead of strobing, which turns three unrelated effects into one machine.
	//
	// scripts/build-compass-art.py cuts the face out of the alien (the design ships the face WITH
	// its antennae baked on, and the antennae have to move) and emits every placement below.
	// scripts/measure-green-lights.py emits the arc points. Re-run them rather than nudging numbers.
	//
	// One rAF per compass cell, drawing imperatively into a captured Graphics — same pattern as
	// <SymbolWinFx>, <ScatterSymbol> and <BatterySymbol>.

	type Props = {
		/** Bezel texture key (desktop / mobile / landscape variant picked by the caller). */
		assetKey: string;
		x: number;
		y: number;
		width: number;
		height: number;
		alpha?: number;
		zIndex?: number;
		/** 0..1 — de-phases every cell so two compasses never sway or blink in lockstep. */
		phase?: number;
		/** Win choreography: hop, badge shake, blinking arcs. */
		winning?: boolean;
	};
	const props: Props = $props();

	// Fractions of the symbol BOX, offsets from centre. Generated by scripts/build-compass-art.py.
	const FACE = { dx: 0.001, dy: 0.0537, w: 0.228, h: 0.2669 };
	const ANTENNA_L = { dx: -0.1041, dy: -0.0969, w: 0.0715, h: 0.1061 };
	const ANTENNA_R = { dx: 0.1068, dy: -0.096, w: 0.0722, h: 0.1067 };
	const EYE = { dx: 0.0028, dy: 0.0507, w: 0.1211, h: 0.1389 };
	const BADGE_N = { dx: 0.002, dy: -0.3434, w: 0.2433, h: 0.3131 };
	const BADGE_S = { dx: 0.0032, dy: 0.3644, w: 0.2261, h: 0.2712 };

	const GLOW = 0x9ee84a;

	/** Win beat for the face's hop, seconds. */
	const BEAT = 0.62;
	/** Badge shake: cycles per second, and how far the badge rocks at the extremes (radians). */
	const SHAKE_HZ = 11;
	const SHAKE_ROT = 0.1;
	/** Arc blink period, and the fraction of it an arc is lit for. */
	const ARC_P = 0.5;
	const ARC_DUTY = 0.42;
	/** Radar sweep: seconds per revolution, the beam's width in radians, and its reach. */
	const SWEEP_P = 1.15;
	const SWEEP_ARC = 0.85;
	const SWEEP_R = 0.4;
	/** How many wedges the beam's tail is built from. More = smoother, and each one is a fill. */
	const SWEEP_STEPS = 9;
	/** Bezel flash on each landing, and how fast it dies. */
	const HIT_FLASH = 0.42;
	const HIT_FALL = 9;
	/** Antenna sway: radians at the extremes, and the two base periods in seconds. */
	const SWAY = 0.12;
	const SWAY_P_L = 2.7;
	const SWAY_P_R = 3.4;
	/** Eye blink: one opportunity per slot, taken this often, lasting this long. */
	const BLINK_SLOT = 3.9;
	const BLINK_CHANCE = 0.7;
	const BLINK_DUR = 0.15;

	// NB: draw helpers work in CONTAINER-RELATIVE coordinates — the <Container> already carries
	// (props.x, props.y).
	type G = {
		destroyed: boolean;
		clear: () => void;
		circle: (x: number, y: number, r: number) => unknown;
		moveTo: (x: number, y: number) => void;
		lineTo: (x: number, y: number) => void;
		fill: (s: object) => void;
		stroke: (s: object) => void;
	};
	let frontG = $state<G | null>(null);
	/** Additive ghost of the bezel: the whole dial lighting on a landing. */
	let bezelFlash = $state(0);

	let faceY = $state(0);
	let faceScale = $state(1);
	let faceRot = $state(0);
	let eyeOpen = $state(1);
	let nScale = $state(1);
	let sScale = $state(1);
	let nRot = $state(0);
	let sRot = $state(0);
	let swayL = $state(0);
	let swayR = $state(0);

	// Four rim arcs, each a chain of points sharing a `group`. Phase by GROUP, or the chain ripples
	// point by point instead of the arc lighting as one strip.
	const LAMPS = GREEN_LIGHTS.compass ?? [];
	const GROUPS = Math.max(1, new Set(LAMPS.map((l) => l.group)).size);

	const W = $derived(props.width);
	const H = $derived(props.height);
	const P = $derived(props.phase ?? 0);

	/** Deterministic 0..1 from an integer — "random" that is stable per cell and per blink. */
	const hash = (n: number) => ((((n * 2654435761) % 1000) + 1000) % 1000) / 1000;

	$effect(() => {
		const t0 = performance.now();
		let raf = 0;

		const tick = () => {
			raf = requestAnimationFrame(tick);
			const t = (performance.now() - t0) / 1000;
			const win = props.winning === true;

			// --- antennae -------------------------------------------------------------------
			// They sway in BOTH states — this is the symbol's only idle motion, and the brief asks
			// for it specifically. The two periods are deliberately not a ratio of small integers,
			// so the pair never falls into a visible lockstep. Winning just widens the swing.
			const amp = SWAY * (win ? 2.1 : 1);
			swayL = amp * Math.sin((t / SWAY_P_L + P) * Math.PI * 2);
			swayR = -amp * Math.sin((t / SWAY_P_R + P * 1.7) * Math.PI * 2);

			// --- eye ------------------------------------------------------------------------
			// One blink opportunity per slot, at a random moment inside it, taken most of the time,
			// so the gaps are irregular. A fixed gap reads as a metronome.
			const bt = t + P * BLINK_SLOT * 3;
			const slot = Math.floor(bt / BLINK_SLOT);
			const seed = slot * 48611 + Math.round(P * 997) * 7919;
			eyeOpen = 1;
			if (hash(seed) < BLINK_CHANCE) {
				const start = hash(seed + 15733) * (BLINK_SLOT - BLINK_DUR);
				const u = (bt - slot * BLINK_SLOT - start) / BLINK_DUR;
				if (u >= 0 && u <= 1) eyeOpen = Math.max(0.06, Math.abs(Math.cos(u * Math.PI)));
			}

			if (win) {
				// The face is HAPPY, not merely animated: a bouncing hop with a squash on landing
				// and a tilt that flips direction each hop. `air` is a half-sine so the arc has a
				// floor to land on.
				const u = (t / BEAT + P) % 1;
				const air = Math.abs(Math.sin(u * Math.PI));
				const land = Math.max(0, 1 - Math.min(u, 1 - u) * 9);
				faceY = -air * H * 0.045;
				faceScale = 1 + air * 0.09 - land * 0.07;
				// One tilt per PAIR of hops, so it rocks left-right rather than pumping.
				faceRot = 0.14 * Math.sin((t / BEAT + P) * Math.PI);

				bezelFlash = HIT_FLASH * Math.exp(-Math.min(u, 1 - u) * HIT_FALL * 2);

				// N and S SHAKE — a continuous rock about their own centres, in antiphase so the
				// two poles are never at the same angle and the pair cannot read as one rigid part.
				const shake = t * SHAKE_HZ * Math.PI * 2 + P * 6.28;
				nRot = SHAKE_ROT * Math.sin(shake);
				sRot = SHAKE_ROT * Math.sin(shake + Math.PI);
				// Kept "slight" per the brief: enough scale to sell the rattle, no more.
				nScale = 1 + 0.03 * Math.sin(shake * 0.5);
				sScale = 1 + 0.03 * Math.sin(shake * 0.5 + Math.PI);
			} else {
				faceY = Math.sin(t * 1.2 + P * 6.28) * H * 0.006;
				faceScale = 1 + 0.012 * Math.sin(t * 1.2 + P * 6.28);
				faceRot = 0;
				nScale = 1;
				sScale = 1;
				nRot = 0;
				sRot = 0;
				bezelFlash = 0;
			}

			if (frontG?.destroyed) frontG = null;
			if (frontG) {
				frontG.clear();
				if (win) {
					// --- the radar sweep ---------------------------------------------------
					// Built from a fan of wedges rather than one shape: the beam has to FADE along
					// its tail, and a single filled wedge can only carry one alpha. Each wedge is
					// drawn from the hub, so they overlap at the centre and the hub stays hottest,
					// which is what a beam does.
					const head = ((t / SWEEP_P + P) % 1) * Math.PI * 2 - Math.PI / 2;
					const R = SWEEP_R * W;
					for (let i = 0; i < SWEEP_STEPS; i++) {
						const f = i / SWEEP_STEPS;
						const a0 = head - (SWEEP_ARC * (i + 1)) / SWEEP_STEPS;
						const a1 = head - (SWEEP_ARC * i) / SWEEP_STEPS;
						frontG.moveTo(0, 0);
						frontG.lineTo(Math.cos(a0) * R, Math.sin(a0) * R);
						frontG.lineTo(Math.cos(a1) * R, Math.sin(a1) * R);
						frontG.fill({ color: GLOW, alpha: 0.12 * (1 - f) ** 1.6 });
					}
					// The leading edge, drawn as a line so it stays crisp while the tail smears.
					frontG.moveTo(0, 0);
					frontG.lineTo(Math.cos(head) * R, Math.sin(head) * R);
					frontG.stroke({ width: W * 0.012, color: 0xf2ffd0, alpha: 0.55, cap: 'round' });

					// The rim arcs. They are painted INTO the bezel, so a blink can only be ADDED
					// over them — there is nothing to switch off. Phased off the SWEEP now rather
					// than a clock of their own, so the ring lights where the beam is pointing.
					for (const lamp of LAMPS) {
						const lu = (t / ARC_P + P + lamp.group / GROUPS) % 1;
						if (lu >= ARC_DUTY) continue;
						const lit = 1 - lu / ARC_DUTY;
						const lx = lamp.dx * W;
						const ly = lamp.dy * H;
						const lr = Math.max(1, lamp.r * W);
						// Halo-weighted. GLOW added at full strength over strips that are already
						// chartreuse clips red and green together and they go WHITE — they stop
						// reading as green lights exactly when they are brightest.
						for (let k = 3; k >= 1; k--) {
							frontG.circle(lx, ly, lr * (1 + k * 1.1));
							frontG.fill({ color: GLOW, alpha: (0.13 * lit) / k });
						}
						frontG.circle(lx, ly, lr);
						frontG.fill({ color: GLOW, alpha: 0.4 * lit });
					}
				}
			}
		};
		raf = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(raf);
	});
</script>

<Container x={props.x} y={props.y} alpha={props.alpha ?? 1} zIndex={props.zIndex}>
	<!-- The lit ring. -->
	<Sprite key={props.assetKey} anchor={0.5} width={W} height={H} />
	<!-- The dial flashing on a landing: the same bezel drawn again additively. Kept mounted at
	     alpha 0 rather than {#if}-toggled -- it changes every frame of a win, and mounting a Pixi
	     child per frame costs more than an empty batched draw. -->
	<Sprite key={props.assetKey} anchor={0.5} blendMode="add" alpha={bezelFlash} width={W} height={H} />
	<!-- Antennae BEHIND the face: their stalks run under it, which is exactly how the cut was made.
	     Anchored at the BOTTOM so the sway pivots where the stalk enters the head — anchored at the
	     centre the whole antenna slides sideways instead of leaning. -->
	<Sprite
		key="compassAntennaL"
		anchor={{ x: 0.5, y: 1 }}
		x={ANTENNA_L.dx * W}
		y={(ANTENNA_L.dy + ANTENNA_L.h / 2) * H + faceY}
		width={ANTENNA_L.w * W}
		height={ANTENNA_L.h * H}
		rotation={swayL}
	/>
	<Sprite
		key="compassAntennaR"
		anchor={{ x: 0.5, y: 1 }}
		x={ANTENNA_R.dx * W}
		y={(ANTENNA_R.dy + ANTENNA_R.h / 2) * H + faceY}
		width={ANTENNA_R.w * W}
		height={ANTENNA_R.h * H}
		rotation={swayR}
	/>
	<Sprite
		key="compassFace"
		anchor={0.5}
		x={FACE.dx * W}
		y={FACE.dy * H + faceY}
		width={FACE.w * W * faceScale}
		height={FACE.h * H * faceScale}
		rotation={faceRot}
	/>
	<!-- The eye rides the face's hop and squash, and closes by collapsing its own height. -->
	<Sprite
		key="compassEye"
		anchor={0.5}
		x={EYE.dx * W}
		y={EYE.dy * H + faceY}
		width={EYE.w * W * faceScale}
		height={EYE.h * H * faceScale * eyeOpen}
		rotation={faceRot}
	/>
	<Sprite
		key="compassN"
		anchor={0.5}
		x={BADGE_N.dx * W}
		y={BADGE_N.dy * H}
		width={BADGE_N.w * W * nScale}
		height={BADGE_N.h * H * nScale}
		rotation={nRot}
	/>
	<Sprite
		key="compassS"
		anchor={0.5}
		x={BADGE_S.dx * W}
		y={BADGE_S.dy * H}
		width={BADGE_S.w * W * sScale}
		height={BADGE_S.h * H * sScale}
		rotation={sRot}
	/>
	<Graphics blendMode="add" draw={(gr) => (frontG = gr as unknown as G)} />
</Container>
