<script lang="ts">
	import { Container, Graphics, Sprite } from 'pixi-svelte';

	// The COMPASS cell (H1), assembled from loose layers so the needle can turn.
	//
	// scripts/build-compass-art.py bakes the bezel and its two chevrons into compass.webp and emits
	// the needle, the alien face and the N/S badges separately.
	//
	//   idle — the needle drifts gently, never settling, the way a real compass hunts for north.
	//   win  — the needle spins up hard, the alien zooms in and out, and N and S pop in alternation.
	//
	// Unlike the scatter and the battery there is NO Figma lockup for this symbol: the arrangement
	// is authored (see the build script). The placements below still come from that script, so the
	// layers stay on the grid it baked the base at.
	//
	// One rAF per compass cell, drawing imperatively into a captured Graphics — same pattern as
	// <SymbolWinFx>, <ScatterSymbol> and <BatterySymbol>.

	type Props = {
		assetKey: string;
		x: number;
		y: number;
		width: number;
		height: number;
		alpha?: number;
		zIndex?: number;
		/** 0..1 — de-phases every cell so two compasses never spin in lockstep. */
		phase?: number;
		winning?: boolean;
	};
	const props: Props = $props();

	// Fractions of the symbol BOX, offsets from centre. Generated by scripts/build-compass-art.py.
	const NEEDLE = { dx: 0.0012, dy: 0.0153, w: 0.0856, h: 0.638 };
	const ALIEN = { dx: 0.0012, dy: 0.0337, w: 0.2678, h: 0.319 };
	const BADGE_N = { dx: 0.0012, dy: -0.3589, w: 0.2184, h: 0.2454 };
	const BADGE_S = { dx: 0.0012, dy: 0.3896, w: 0.1816, h: 0.2086 };

	const GLOW = 0x9ee84a;

	/** Win spin, revolutions per second. */
	const SPIN_RPS = 2.4;
	/** Win beat for the alien zoom and the badge pops, seconds. */
	const BEAT = 0.62;

	// NB: draw helpers work in CONTAINER-RELATIVE coordinates — the <Container> already carries
	// (props.x, props.y).
	type G = {
		destroyed: boolean;
		clear: () => void;
		circle: (x: number, y: number, r: number) => unknown;
		ellipse: (x: number, y: number, rx: number, ry: number) => unknown;
		stroke: (s: object) => void;
		fill: (s: object) => void;
	};
	let frontG = $state<G | null>(null);

	let needleRot = $state(0);
	let alienScale = $state(1);
	let nScale = $state(1);
	let sScale = $state(1);

	const W = $derived(props.width);
	const H = $derived(props.height);
	const P = $derived(props.phase ?? 0);

	$effect(() => {
		const t0 = performance.now();
		let raf = 0;
		// Carried across frames so the needle never JUMPS when the cell flips into its win state —
		// the spin accelerates away from wherever the idle drift had left it.
		let angle = 0;
		let last = 0;

		const tick = () => {
			raf = requestAnimationFrame(tick);
			const t = (performance.now() - t0) / 1000;
			const dt = Math.min(0.05, t - last);
			last = t;
			const win = props.winning === true;

			if (win) {
				angle += dt * SPIN_RPS * Math.PI * 2;
				needleRot = angle;

				// Alien zoom in/out on the beat.
				const u = (t / BEAT + P) % 1;
				alienScale = 1 + 0.16 * Math.sin(u * Math.PI * 2);

				// N and S pop in alternation — a sharp decaying kick each, half a beat apart, so
				// the poles read as taking turns rather than flashing together.
				const kick = (o: number) => {
					const k = (t / BEAT + P + o) % 1;
					return 1 + 0.26 * Math.exp(-k * 7) * Math.sin(k * 20);
				};
				nScale = kick(0);
				sScale = kick(0.5);
			} else {
				// Gentle hunt: two slow sines that never line up, so the needle wanders instead of
				// ticking metronomically back and forth.
				angle =
					0.11 * Math.sin(t * 0.42 + P * 6.28) + 0.05 * Math.sin(t * 0.97 + P * 3.1);
				needleRot = angle;
				alienScale = 1 + 0.012 * Math.sin(t * 1.2 + P * 6.28);
				nScale = 1;
				sScale = 1;
			}

			if (frontG?.destroyed) frontG = null;
			if (frontG) {
				frontG.clear();
				if (win) {
					// A charge ring under the rotating needle, so the spin reads as powered.
					const pulse = 0.5 + 0.5 * Math.sin(t * 8 + P * 6.28);
					for (let k = 0; k < 3; k++) {
						frontG.circle(NEEDLE.dx * W, NEEDLE.dy * H, Math.min(W, H) * (0.2 + 0.05 * k));
						frontG.stroke({
							width: Math.min(W, H) * 0.012,
							color: GLOW,
							alpha: (0.22 - 0.06 * k) * (0.4 + 0.6 * pulse),
						});
					}
				}
			}
		};
		raf = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(raf);
	});
</script>

<Container x={props.x} y={props.y} alpha={props.alpha ?? 1} zIndex={props.zIndex}>
	<!-- Bezel with the chevrons baked in. -->
	<Sprite key={props.assetKey} anchor={0.5} width={W} height={H} />
	<!-- Needle BEHIND the alien: the alien is the pivot cap it turns under. -->
	<Sprite
		key="compassNeedle"
		anchor={0.5}
		x={NEEDLE.dx * W}
		y={NEEDLE.dy * H}
		width={NEEDLE.w * W}
		height={NEEDLE.h * H}
		rotation={needleRot}
	/>
	<Sprite
		key="compassAlien"
		anchor={0.5}
		x={ALIEN.dx * W}
		y={ALIEN.dy * H}
		width={ALIEN.w * W * alienScale}
		height={ALIEN.h * H * alienScale}
	/>
	<Sprite
		key="compassN"
		anchor={0.5}
		x={BADGE_N.dx * W}
		y={BADGE_N.dy * H}
		width={BADGE_N.w * W * nScale}
		height={BADGE_N.h * H * nScale}
	/>
	<Sprite
		key="compassS"
		anchor={0.5}
		x={BADGE_S.dx * W}
		y={BADGE_S.dy * H}
		width={BADGE_S.w * W * sScale}
		height={BADGE_S.h * H * sScale}
	/>
	<Graphics blendMode="add" draw={(gr) => (frontG = gr as unknown as G)} />
</Container>
