<script lang="ts">
	import { Container, Graphics, Sprite } from 'pixi-svelte';

	// The ELECTROMAGNETIC DEVICE cell (H4), assembled live so its antennae can move and discharge.
	//
	//   idle — the antennae shake very slightly, on two unmatched periods.
	//   win  — they swing wider and faster, and current arcs from ball to ball over the top.
	//
	// scripts/build-emdevice-art.py cuts the layers and emits every number below. Unlike the magnet,
	// the four source rasters share a frame AND are already positioned, so the placements are just
	// each part's box in that frame — there is no reference-matching involved. Re-run the script
	// rather than nudging the constants.
	//
	// One rAF per device cell, drawing imperatively into a captured Graphics — same pattern as
	// <SymbolWinFx>, <ScatterSymbol>, <BatterySymbol>, <CompassSymbol> and <MagnetSymbol>.

	type Props = {
		/** Base texture key — body + arm (desktop / mobile / landscape variant picked by the caller). */
		assetKey: string;
		x: number;
		y: number;
		width: number;
		height: number;
		alpha?: number;
		zIndex?: number;
		/** 0..1 — de-phases every cell so two devices never shake or discharge in lockstep. */
		phase?: number;
		/** Win choreography: faster antennae, current across the balls. */
		winning?: boolean;
	};
	const props: Props = $props();

	// Fractions of the symbol BOX, offsets from centre. Generated by scripts/build-emdevice-art.py.
	const ANTENNA_L = { dx: -0.2661, dy: -0.2377, w: 0.1856, h: 0.2728 };
	const ANTENNA_R = { dx: 0.277, dy: -0.3701, w: 0.1751, h: 0.2598 };
	const LENS = { dx: -0.3141, dy: 0.1407, w: 0.1281, h: 0.2176 };
	/** Where each stalk enters its drum, as an anchor inside the antenna's own box. */
	const PIVOT_L = { x: 0.6716, y: 0.9541 };
	const PIVOT_R = { x: 0.328, y: 0.9541 };
	/** The two green ball centres: the terminals the current jumps between. */
	const TERM_L = { dx: -0.2991, dy: -0.3036 };
	const TERM_R = { dx: 0.3074, dy: -0.4318 };

	const SPARK = 0xb6ff5a;
	const SPARK_HOT = 0xffffff;

	/** Antenna sway, radians at the extremes, and the two base periods in seconds. */
	const SWAY_IDLE = 0.095;
	const SWAY_WIN = 0.11;
	const SWAY_P_L = 3.1;
	const SWAY_P_R = 2.6;
	/** Idle antennae are a MOOD, not a metronome. A permanent low-amplitude sine reads as a nervous
	 *  jitter — the cell never sits still and never does anything either. Instead they REST, and
	 *  every few seconds give one short, gently decaying happy wiggle. `phase` staggers the cells,
	 *  so a board of them ripples rather than twitching in unison. */
	const IDLE_EVERY = 7.4;
	const IDLE_DUR = 1.05;
	const IDLE_HZ = 3.4;
	/** How much faster the antennae run on a win. */
	const WIN_RATE = 3.4;
	/** Arc: strikes per second, how long a strike lasts, and how many kinks it has. */
	const ARC_HZ = 6;
	const ARC_DUR = 0.07;
	const ARC_SEGMENTS = 9;
	/**
	 * How far above the terminals the bolt bows, as a fraction of the symbol HEIGHT.
	 *
	 * The ceiling is the symbol box, not the art: pixi does not clip a Container, so a bolt that
	 * peaks past dy -0.5 is drawn over whatever cell sits in the row above. The antennae are now
	 * placed where the design puts them -- high, and at DIFFERENT heights (dy -0.304 and -0.432) --
	 * so there is far less headroom than the first pass assumed: the midpoint is already at -0.368
	 * and the old 0.27 would peak near -0.64, a quarter of a cell into the row above. 0.09 plus the
	 * kink's vertical share peaks near -0.47.
	 */
	const ARC_BOW = 0.09;

	// NB: draw helpers work in CONTAINER-RELATIVE coordinates — the <Container> already carries
	// (props.x, props.y).
	type G = {
		destroyed: boolean;
		clear: () => void;
		circle: (x: number, y: number, r: number) => unknown;
		moveTo: (x: number, y: number) => void;
		lineTo: (x: number, y: number) => void;
		stroke: (s: object) => void;
		fill: (s: object) => void;
	};
	let frontG = $state<G | null>(null);

	let swayL = $state(0);
	let swayR = $state(0);
	let lensFlash = $state(0);

	const W = $derived(props.width);
	const H = $derived(props.height);
	const P = $derived(props.phase ?? 0);

	/** Deterministic 0..1 from an integer — stable per cell and per strike. */
	const hash = (n: number) => ((((n * 2654435761) % 1000) + 1000) % 1000) / 1000;

	/**
	 * One bolt from ball to ball, re-kinked every strike.
	 *
	 * The spine is a parabola bowing up over the device, and the kinks ride it, tapered by
	 * sin(u * PI) so they vanish at both ends. That taper is what keeps the bolt LANDING on the two
	 * balls however wild the middle gets — uniform jitter leaves the ends dancing off the terminals,
	 * which reads as a loose wire rather than an arc.
	 */
	const drawArc = (g: G, strike: number, life: number) => {
		const x0 = TERM_L.dx * W;
		const y0 = TERM_L.dy * H;
		const x1 = TERM_R.dx * W;
		const y1 = TERM_R.dy * H;
		const len = Math.hypot(x1 - x0, y1 - y0) || 1;
		const spread = len * 0.09;

		const pts: Array<[number, number]> = [];
		for (let i = 0; i <= ARC_SEGMENTS; i++) {
			const u = i / ARC_SEGMENTS;
			const taper = Math.sin(u * Math.PI); // 0 at both terminals, 1 in the middle
			const k = (hash(strike * 7919 + i * 104729) - 0.5) * 2 * spread * taper;
			pts.push([x0 + (x1 - x0) * u + k, y0 + (y1 - y0) * u - taper * ARC_BOW * H + k * 0.4]);
		}

		// Wide soft pass, then the hot core, so the bolt glows rather than ending in a hard edge.
		for (const [w, color, alpha] of [
			[len * 0.05, SPARK, 0.26 * life],
			[len * 0.02, SPARK, 0.65 * life],
			[len * 0.007, SPARK_HOT, 0.95 * life],
		] as const) {
			g.moveTo(pts[0][0], pts[0][1]);
			for (let i = 1; i < pts.length; i++) g.lineTo(pts[i][0], pts[i][1]);
			g.stroke({ width: w, color, alpha, cap: 'round', join: 'round' });
		}

		// Both balls flare while the bolt is live.
		for (const [tx, ty] of [
			[x0, y0],
			[x1, y1],
		]) {
			for (let k = 3; k >= 1; k--) {
				g.circle(tx, ty, len * 0.035 * k);
				g.fill({ color: SPARK, alpha: (0.15 * life) / k });
			}
		}
	};

	$effect(() => {
		const t0 = performance.now();
		let raf = 0;
		// Carried across frames: the sway RATE changes when the cell flips into its win state, and
		// advancing a phase rather than sampling sin(t * rate) means the antennae speed up from
		// wherever they happen to be instead of snapping to a new position.
		let phaseL = 0;
		let phaseR = 0;
		let last = 0;

		const tick = () => {
			raf = requestAnimationFrame(tick);
			const t = (performance.now() - t0) / 1000;
			const dt = Math.min(0.05, t - last);
			last = t;
			const win = props.winning === true;

			const rate = win ? WIN_RATE : 1;
			// The win phases keep advancing even while idle, so a cell that flips into its win
			// state picks the sway up mid-stroke instead of snapping to zero.
			phaseL += (dt / SWAY_P_L) * rate * Math.PI * 2;
			phaseR += (dt / SWAY_P_R) * rate * Math.PI * 2;
			if (win) {
				swayL = SWAY_WIN * Math.sin(phaseL + P * 6.28);
				swayR = -SWAY_WIN * Math.sin(phaseR + P * 5.1);
			} else {
				const since = ((t / IDLE_EVERY + P) % 1) * IDLE_EVERY;
				const wiggle =
					since < IDLE_DUR ? Math.exp(-since * 2.6) * Math.sin(since * IDLE_HZ * Math.PI * 2) : 0;
				swayL = SWAY_IDLE * wiggle;
				swayR = -SWAY_IDLE * wiggle * 0.78;
			}

			if (frontG?.destroyed) frontG = null;
			if (frontG) {
				frontG.clear();
				if (win) {
					// Strikes are discrete, not a continuous ribbon: an arc that never goes out
					// reads as a drawn wire between the balls rather than as electricity.
					const s = t * ARC_HZ + P * 3;
					const strike = Math.floor(s);
					const age = (s - strike) / (ARC_HZ * ARC_DUR);
					if (age < 1) {
						drawArc(frontG, strike, 1 - age);
						// The eye answers the discharge. Without this the bolt looks pasted on top
						// of a symbol that has not noticed it.
						lensFlash = 0.34 * (1 - age);
					} else {
						lensFlash = 0;
					}
				} else {
					lensFlash = 0;
				}
			}
		};
		raf = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(raf);
	});
</script>

<Container x={props.x} y={props.y} alpha={props.alpha ?? 1} zIndex={props.zIndex}>
	<!-- Drums + the green arm over them. -->
	<Sprite key={props.assetKey} anchor={0.5} width={W} height={H} />
	<!-- Antennae UNDER the lens: their stalks run behind it, which is exactly how the art is drawn,
	     and it is what hides each joint while the antenna leans. Anchored at the stalk base rather
	     than the box centre, or the whole antenna slides sideways instead of pivoting. -->
	<Sprite
		key="emAntennaL"
		anchor={PIVOT_L}
		x={(ANTENNA_L.dx + ANTENNA_L.w * (PIVOT_L.x - 0.5)) * W}
		y={(ANTENNA_L.dy + ANTENNA_L.h * (PIVOT_L.y - 0.5)) * H}
		width={ANTENNA_L.w * W}
		height={ANTENNA_L.h * H}
		rotation={swayL}
	/>
	<Sprite
		key="emAntennaR"
		anchor={PIVOT_R}
		x={(ANTENNA_R.dx + ANTENNA_R.w * (PIVOT_R.x - 0.5)) * W}
		y={(ANTENNA_R.dy + ANTENNA_R.h * (PIVOT_R.y - 0.5)) * H}
		width={ANTENNA_R.w * W}
		height={ANTENNA_R.h * H}
		rotation={swayR}
	/>
	<Sprite
		key="emLens"
		anchor={0.5}
		x={LENS.dx * W}
		y={LENS.dy * H}
		width={LENS.w * W}
		height={LENS.h * H}
	/>
	<!-- An additive GHOST of the lens, kept mounted at alpha 0 rather than toggled with {#if}: a
	     tint can only scale a texture's channels DOWN, so it can darken the eye but never light it.
	     Mounting and unmounting per strike would churn a texture six times a second. -->
	<Sprite
		key="emLens"
		blendMode="add"
		alpha={lensFlash}
		anchor={0.5}
		x={LENS.dx * W}
		y={LENS.dy * H}
		width={LENS.w * W}
		height={LENS.h * H}
	/>
	<Graphics blendMode="add" draw={(gr) => (frontG = gr as unknown as G)} />
</Container>
