<script lang="ts">
	import { Container, Graphics, Sprite } from 'pixi-svelte';

	// The LIGHTNING badge (H2), assembled live so the bolt can pop and blink.
	//
	//   idle — the bolt breathes and the four corner balls twinkle slowly.
	//   win  — the bolt pops hard and blinks, and the balls chase.
	//
	// scripts/build-lightning-art.py cuts the layers and emits every number below. The bolt ships as
	// TWO svgs, a white shape over an orange one, and the script bakes them into one texture: nothing
	// in the brief moves them apart, and keeping them together means the pop moves one sprite.
	//
	// One rAF per cell, drawing imperatively into a captured Graphics — same pattern as
	// <SymbolWinFx>, <ScatterSymbol>, <BatterySymbol>, <CompassSymbol>, <MagnetSymbol>,
	// <EmDeviceSymbol> and <WildSymbol>.

	type Props = {
		/** Base texture key — frame, face and the four balls (desktop / mobile / landscape variant). */
		assetKey: string;
		x: number;
		y: number;
		width: number;
		height: number;
		alpha?: number;
		zIndex?: number;
		/** 0..1 — de-phases every cell so two badges never pop or blink in lockstep. */
		phase?: number;
		/** Win choreography: hard pop, blink, chasing balls. */
		winning?: boolean;
	};
	const props: Props = $props();

	// Fractions of the symbol BOX, offsets from centre. Generated by scripts/build-lightning-art.py.
	const BOLT = { dx: 0.0158, dy: 0.0115, w: 0.2925, h: 0.5047 };
	/** The four green corner balls, in reading order. */
	const BALLS = [
		{ dx: -0.2867, dy: -0.4038, r: 0.0764 },
		{ dx: 0.282, dy: -0.4038, r: 0.0764 },
		{ dx: -0.303, dy: 0.3836, r: 0.0764 },
		{ dx: 0.2983, dy: 0.4038, r: 0.0764 },
	];

	const BALL_GLOW = 0xc8ff5a;
	const BOLT_FLASH = 0xfff2c0;

	/** Bolt pop: period in seconds, and how far it scales at the two extremes. */
	const POP_P = 0.5;
	const POP_IDLE = 0.03;
	const POP_WIN = 0.26;
	/**
	 * Bolt blink. Deliberately NOT a divisor of POP_P: on a period that divides the pop the two land
	 * together every cycle and the eye reads one event rather than a bolt that is both growing and
	 * flashing.
	 */
	const BLINK_P = 0.31;
	const BLINK_DUTY = 0.42;
	/** Ball chase period, and the fraction of it a ball is lit for. */
	const BALL_P = 0.46;
	const BALL_DUTY = 0.5;

	// NB: draw helpers work in CONTAINER-RELATIVE coordinates — the <Container> already carries
	// (props.x, props.y).
	type G = {
		destroyed: boolean;
		clear: () => void;
		circle: (x: number, y: number, r: number) => unknown;
		fill: (s: object) => void;
	};
	let frontG = $state<G | null>(null);

	let boltScale = $state(1);
	let boltFlash = $state(0);
	let boltTint = $state(0xffffff);

	const W = $derived(props.width);
	const H = $derived(props.height);
	const P = $derived(props.phase ?? 0);

	$effect(() => {
		const t0 = performance.now();
		let raf = 0;

		const tick = () => {
			raf = requestAnimationFrame(tick);
			const t = (performance.now() - t0) / 1000;
			const win = props.winning === true;

			// --- the pop --------------------------------------------------------------------
			// A fast punch out and a slower settle back, so it reads as a discharge rather than a
			// sine wave. Idle keeps the same curve at a tenth of the depth.
			const u = (t / POP_P + P) % 1;
			const punch = u < 0.28 ? u / 0.28 : 1 - (u - 0.28) / 0.72;
			const eased = Math.sin(punch * Math.PI * 0.5) ** 2;
			boltScale = 1 + (win ? POP_WIN : POP_IDLE) * eased;

			// --- the blink ------------------------------------------------------------------
			// An additive ghost of the bolt, not a tint: a tint can only scale a texture's channels
			// DOWN, so it can darken the bolt but never light it. The warm tint underneath just
			// stops the white going flat while the ghost is on.
			if (win) {
				const bu = (t / BLINK_P + P * 3) % 1;
				const lit = bu < BLINK_DUTY ? 1 - bu / BLINK_DUTY : 0;
				boltFlash = 0.7 * Math.sqrt(lit);
				boltTint = lit > 0 ? 0xfff6d8 : 0xffffff;
			} else {
				boltFlash = 0;
				boltTint = 0xffffff;
			}

			if (frontG?.destroyed) frontG = null;
			if (frontG) {
				frontG.clear();
				for (let i = 0; i < BALLS.length; i++) {
					const ball = BALLS[i];
					let lit: number;
					if (win) {
						const bu = (t / BALL_P + P + i / BALLS.length) % 1;
						lit = bu < BALL_DUTY ? 1 - bu / BALL_DUTY : 0;
					} else {
						lit = 0.2 * (0.5 + 0.5 * Math.sin(t * 1.5 + i * 1.9 + P * 6.28));
					}
					if (lit <= 0.001) continue;
					const lx = ball.dx * W;
					const ly = ball.dy * H;
					const lr = Math.max(1, ball.r * W);
					// Halo-weighted. BALL_GLOW added at full strength over balls that are already
					// chartreuse clips red and green together and they go WHITE — they stop reading
					// as green lights exactly when they are brightest.
					for (let k = 3; k >= 1; k--) {
						frontG.circle(lx, ly, lr * (1 + k * 0.5));
						frontG.fill({ color: BALL_GLOW, alpha: (0.12 * lit) / k });
					}
					frontG.circle(lx, ly, lr);
					frontG.fill({ color: BALL_GLOW, alpha: 0.3 * lit });
				}
			}
		};
		raf = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(raf);
	});
</script>

<Container x={props.x} y={props.y} alpha={props.alpha ?? 1} zIndex={props.zIndex}>
	<!-- Frame, face and the four corner balls. -->
	<Sprite key={props.assetKey} anchor={0.5} width={W} height={H} />
	<Sprite
		key="lightningBolt"
		tint={boltTint}
		anchor={0.5}
		x={BOLT.dx * W}
		y={BOLT.dy * H}
		width={BOLT.w * W * boltScale}
		height={BOLT.h * H * boltScale}
	/>
	<!-- The blink's ghost, kept mounted at alpha 0 rather than toggled with {#if}: mounting and
	     unmounting three times a second would churn a texture for nothing. -->
	<Sprite
		key="lightningBolt"
		blendMode="add"
		tint={BOLT_FLASH}
		alpha={boltFlash}
		anchor={0.5}
		x={BOLT.dx * W}
		y={BOLT.dy * H}
		width={BOLT.w * W * boltScale}
		height={BOLT.h * H * boltScale}
	/>
	<Graphics blendMode="add" draw={(gr) => (frontG = gr as unknown as G)} />
</Container>
