<script lang="ts">
	import { Container, Graphics, Sprite } from 'pixi-svelte';

	// The MAGNET cell (L2, the horseshoe), assembled live so its antennae can move and its
	// terminals can arc.
	//
	//   idle — the antennae shake VERY slightly, the face breathes.
	//   win  — the antennae speed up and swing wide, and electricity arcs between - and +.
	//
	// scripts/build-magnet-art.py cuts the parts and emits every placement below. It is worth
	// knowing why that script is not a simple composite: the design ships the loose parts as ONE
	// sheet in the same 1536x1024 frame as the body, which looks like it should drop straight on
	// top, but the sheet is a LAYOUT, not a composition — the face sits low across the magnet's
	// gap and the hands sit on the caps. The real arrangement only exists in the designer's
	// reference image, so the art comes from the sheet and the placement from the reference.
	//
	// One rAF per magnet cell, drawing imperatively into a captured Graphics — same pattern as
	// <SymbolWinFx>, <ScatterSymbol>, <BatterySymbol> and <CompassSymbol>.

	type Props = {
		/** Body texture key (desktop / mobile / landscape variant picked by the caller). */
		assetKey: string;
		x: number;
		y: number;
		width: number;
		height: number;
		alpha?: number;
		zIndex?: number;
		/** 0..1 — de-phases every cell so two magnets never shake or arc in lockstep. */
		phase?: number;
		/** Win choreography: faster antennae, electricity across the terminals. */
		winning?: boolean;
	};
	const props: Props = $props();

	// Fractions of the symbol BOX, offsets from centre. Generated by scripts/build-magnet-art.py.
	const FACE = { dx: 0.0019, dy: -0.1498, w: 0.3648, h: 0.243 };
	const ANTENNA_L = { dx: -0.2101, dy: -0.3969, w: 0.1282, h: 0.2062 };
	const ANTENNA_R = { dx: 0.2312, dy: -0.3867, w: 0.1331, h: 0.2266 };
	const HAND_L = { dx: -0.3415, dy: 0.1003, w: 0.092, h: 0.1797 };
	const HAND_R = { dx: 0.3298, dy: 0.1095, w: 0.097, h: 0.1736 };
	/** The green - and + marks on the caps: the endpoints the arc jumps between. */
	const TERM_MINUS = { dx: -0.279, dy: 0.2942 };
	const TERM_PLUS = { dx: 0.2586, dy: 0.2942 };

	const SPARK = 0x8ce6ff;
	const SPARK_HOT = 0xffffff;

	/** Antenna sway, radians at the extremes, and the two base periods in seconds. */
	const SWAY_IDLE = 0.035;
	const SWAY_WIN = 0.2;
	const SWAY_P_L = 2.9;
	const SWAY_P_R = 3.6;
	/** How much faster the antennae run on a win. */
	const WIN_RATE = 4.2;
	/** Arc: strikes per second, how long a strike lasts, and how many kinks it has. */
	const ARC_HZ = 5.5;
	const ARC_DUR = 0.11;
	const ARC_SEGMENTS = 7;

	// NB: draw helpers work in CONTAINER-RELATIVE coordinates — the <Container> already carries
	// (props.x, props.y).
	type G = {
		destroyed: boolean;
		clear: () => void;
		circle: (x: number, y: number, r: number) => unknown;
		moveTo: (x: number, y: number) => void;
		lineTo: (x: number, y: number) => void;
		stroke: (s: object) => void;
		fill: (s: object) => void;
	};
	let frontG = $state<G | null>(null);

	let swayL = $state(0);
	let swayR = $state(0);
	let faceScale = $state(1);

	const W = $derived(props.width);
	const H = $derived(props.height);
	const P = $derived(props.phase ?? 0);

	/** Deterministic 0..1 from an integer — stable per cell and per strike. */
	const hash = (n: number) => ((((n * 2654435761) % 1000) + 1000) % 1000) / 1000;

	/**
	 * One lightning bolt from - to +, re-kinked every strike.
	 *
	 * Drawn as a polyline whose interior points are pushed off the straight line by a random amount
	 * that is largest in the middle and zero at both ends, so the bolt always LANDS on the two
	 * terminals however wild the middle gets. A uniform jitter would leave the ends dancing off the
	 * caps, which reads as a loose wire rather than an arc.
	 */
	const drawArc = (g: G, strike: number, life: number) => {
		const x0 = TERM_MINUS.dx * W;
		const y0 = TERM_MINUS.dy * H;
		const x1 = TERM_PLUS.dx * W;
		const y1 = TERM_PLUS.dy * H;
		const dx = x1 - x0;
		const dy = y1 - y0;
		const len = Math.hypot(dx, dy) || 1;
		// Unit normal to the bolt's axis: the kinks are perpendicular to it, not vertical, so the
		// arc still reads correctly if the terminals are ever not level.
		const nx = -dy / len;
		const ny = dx / len;
		const spread = len * 0.16;

		const pts: Array<[number, number]> = [];
		for (let i = 0; i <= ARC_SEGMENTS; i++) {
			const u = i / ARC_SEGMENTS;
			const taper = Math.sin(u * Math.PI); // 0 at both terminals, 1 in the middle
			const k = (hash(strike * 7919 + i * 104729) - 0.5) * 2 * spread * taper;
			pts.push([x0 + dx * u + nx * k, y0 + dy * u + ny * k]);
		}

		// Wide soft pass, then the hot core, so the bolt has a glow rather than a hard edge.
		for (const [w, color, alpha] of [
			[len * 0.055, SPARK, 0.3 * life],
			[len * 0.022, SPARK, 0.7 * life],
			[len * 0.008, SPARK_HOT, 0.95 * life],
		] as const) {
			g.moveTo(pts[0][0], pts[0][1]);
			for (let i = 1; i < pts.length; i++) g.lineTo(pts[i][0], pts[i][1]);
			g.stroke({ width: w, color, alpha, cap: 'round', join: 'round' });
		}

		// Both terminals flare while the bolt is live.
		for (const [tx, ty] of [
			[x0, y0],
			[x1, y1],
		]) {
			for (let k = 3; k >= 1; k--) {
				g.circle(tx, ty, len * 0.03 * k);
				g.fill({ color: SPARK, alpha: (0.16 * life) / k });
			}
		}
	};

	$effect(() => {
		const t0 = performance.now();
		let raf = 0;
		// Carried across frames: the sway RATE changes when the cell flips into its win state, and
		// advancing a phase rather than sampling sin(t * rate) means the antennae speed up from
		// wherever they happen to be instead of snapping to a new position.
		let phaseL = 0;
		let phaseR = 0;
		let last = 0;

		const tick = () => {
			raf = requestAnimationFrame(tick);
			const t = (performance.now() - t0) / 1000;
			const dt = Math.min(0.05, t - last);
			last = t;
			const win = props.winning === true;

			const rate = win ? WIN_RATE : 1;
			phaseL += (dt / SWAY_P_L) * rate * Math.PI * 2;
			phaseR += (dt / SWAY_P_R) * rate * Math.PI * 2;
			const amp = win ? SWAY_WIN : SWAY_IDLE;
			swayL = amp * Math.sin(phaseL + P * 6.28);
			swayR = -amp * Math.sin(phaseR + P * 5.1);

			faceScale = win
				? 1 + 0.05 * Math.abs(Math.sin(t * 6 + P * 6.28))
				: 1 + 0.012 * Math.sin(t * 1.4 + P * 6.28);

			if (frontG?.destroyed) frontG = null;
			if (frontG) {
				frontG.clear();
				if (win) {
					// Strikes are discrete, not a continuous ribbon: an arc that never goes out
					// reads as a drawn line between the caps rather than as electricity.
					const s = t * ARC_HZ + P * 3;
					const strike = Math.floor(s);
					const age = (s - strike) / (ARC_HZ * ARC_DUR);
					if (age < 1) drawArc(frontG, strike, 1 - age);
				}
			}
		};
		raf = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(raf);
	});
</script>

<Container x={props.x} y={props.y} alpha={props.alpha ?? 1} zIndex={props.zIndex}>
	<!-- Antennae BEHIND the body: their stalks disappear under the arch. Anchored at the BOTTOM so
	     the shake pivots where the stalk meets the body — anchored at the centre the whole antenna
	     slides sideways instead of leaning. -->
	<Sprite
		key="magnetAntennaL"
		anchor={{ x: 0.5, y: 1 }}
		x={ANTENNA_L.dx * W}
		y={(ANTENNA_L.dy + ANTENNA_L.h / 2) * H}
		width={ANTENNA_L.w * W}
		height={ANTENNA_L.h * H}
		rotation={swayL}
	/>
	<Sprite
		key="magnetAntennaR"
		anchor={{ x: 0.5, y: 1 }}
		x={ANTENNA_R.dx * W}
		y={(ANTENNA_R.dy + ANTENNA_R.h / 2) * H}
		width={ANTENNA_R.w * W}
		height={ANTENNA_R.h * H}
		rotation={swayR}
	/>
	<!-- The horseshoe itself. -->
	<Sprite key={props.assetKey} anchor={0.5} width={W} height={H} />
	<Sprite
		key="magnetHandL"
		anchor={0.5}
		x={HAND_L.dx * W}
		y={HAND_L.dy * H}
		width={HAND_L.w * W}
		height={HAND_L.h * H}
	/>
	<Sprite
		key="magnetHandR"
		anchor={0.5}
		x={HAND_R.dx * W}
		y={HAND_R.dy * H}
		width={HAND_R.w * W}
		height={HAND_R.h * H}
	/>
	<Sprite
		key="magnetFace"
		anchor={0.5}
		x={FACE.dx * W}
		y={FACE.dy * H}
		width={FACE.w * W * faceScale}
		height={FACE.h * H * faceScale}
	/>
	<Graphics blendMode="add" draw={(gr) => (frontG = gr as unknown as G)} />
</Container>
