<script lang="ts">
	import { Container, Sprite } from 'pixi-svelte';

	// The PORTAL cell (H3), assembled live so the galaxy in the middle can turn.
	//
	//   idle — the core is STILL, and blinks: a double pulse, then a pause.
	//   win  — the core spins up and runs fast, and the alien's antennae flap.
	//
	// The core does not snap between the two. It carries an angular VELOCITY that eases towards its
	// target, so a win spins it up over a few tenths of a second and the end of a win lets it coast
	// down. Sampling `rotation = t * rate` instead would teleport the galaxy to a new angle on every
	// state change, which reads as a glitch rather than a machine starting.
	//
	// scripts/build-portal-art.py cuts the layers and emits every placement below. The core is drawn
	// BEHIND the base: the base is the ring with its own hole punched back out, and the four pins
	// whose stalks run under the ring band.
	//
	// One rAF per cell — same pattern as <SymbolWinFx>, <ScatterSymbol>, <BatterySymbol>,
	// <CompassSymbol>, <MagnetSymbol>, <EmDeviceSymbol>, <LightningSymbol> and <WildSymbol>.

	type Props = {
		/** Base texture key — the ring and the four pins (desktop / mobile / landscape variant). */
		assetKey: string;
		x: number;
		y: number;
		width: number;
		height: number;
		alpha?: number;
		zIndex?: number;
		/** 0..1 — de-phases every cell so two portals never blink or sit at the same angle. */
		phase?: number;
		/** Win choreography: the core spins fast, the antennae flap. */
		winning?: boolean;
	};
	const props: Props = $props();

	// Fractions of the symbol BOX, offsets from centre. Generated by scripts/build-portal-art.py.
	const CORE = { dx: -0.0043, dy: 0.0394, w: 0.4463, h: 0.5595 };
	const HEAD = { dx: 0.004, dy: -0.3481, w: 0.1548, h: 0.1923 };
	const ANTENNA_L = { dx: -0.0626, dy: -0.4566, w: 0.0603, h: 0.0868 };
	const ANTENNA_R = { dx: 0.0691, dy: -0.4586, w: 0.0572, h: 0.0828 };
	/** Where each antenna's stalk meets the head, as a fraction of its own box — its pivot. */
	const PIVOT_L = { x: 0.7996, y: 0.8561 };
	const PIVOT_R = { x: 0.1833, y: 0.866 };

	const CORE_GLOW = 0x8a5cff;

	/** Core spin, radians per second, and how long it takes to reach (or shed) that speed. */
	const SPIN_WIN = 5.6;
	const SPIN_TAU = 0.35;
	/** Idle blink: the period, when inside it the two pulses land, and how long each one lasts. */
	const BLINK_P = 2.4;
	const BLINK_AT = [0, 0.15];
	const BLINK_DUR = 0.1;
	const BLINK_PEAK = 0.5;
	/** Win glow: a steady shimmer rather than a blink, at this rate and between these two levels. */
	const GLOW_HZ = 2.6;
	const GLOW_LOW = 0.16;
	const GLOW_HIGH = 0.36;
	/** Antenna flap: radians at the extremes, and the two periods in seconds. Deliberately not a
	 *  ratio of small integers, so the pair never falls into a visible lockstep. */
	const FLAP = 0.26;
	const FLAP_P_L = 0.34;
	const FLAP_P_R = 0.41;
	/** How far the alien rides up and down, as a fraction of the symbol's height. */
	const BOB_IDLE = 0.004;
	const BOB_WIN = 0.012;

	let coreRot = $state(0);
	let coreFlash = $state(0);
	let flapL = $state(0);
	let flapR = $state(0);
	let headY = $state(0);

	const W = $derived(props.width);
	const H = $derived(props.height);
	const P = $derived(props.phase ?? 0);

	$effect(() => {
		const t0 = performance.now();
		let raf = 0;
		// Carried across frames: the core's angular velocity, and the angle it has reached.
		let spin = 0;
		let angle = Math.PI * 2 * (props.phase ?? 0);
		let phaseL = 0;
		let phaseR = 0;
		let amp = 0;
		let last = 0;

		const tick = () => {
			raf = requestAnimationFrame(tick);
			const t = (performance.now() - t0) / 1000;
			const dt = Math.min(0.05, t - last);
			last = t;
			const win = props.winning === true;

			// --- the core -------------------------------------------------------------------
			spin += ((win ? SPIN_WIN : 0) - spin) * (1 - Math.exp(-dt / SPIN_TAU));
			angle += spin * dt;
			coreRot = angle;

			if (win) {
				coreFlash =
					GLOW_LOW +
					(GLOW_HIGH - GLOW_LOW) * (0.5 + 0.5 * Math.sin(t * GLOW_HZ * Math.PI * 2 + P * 6.28));
			} else {
				// Two quick pulses close together, then most of the period dark. One evenly spaced
				// pulse per period reads as a metronome; the pair reads as something alive blinking.
				const u = (t / BLINK_P + P) % 1;
				const half = BLINK_DUR / BLINK_P / 2;
				let lit = 0;
				for (const at of BLINK_AT) {
					const d = Math.abs(u - at);
					lit = Math.max(lit, 1 - Math.min(d, 1 - d) / half);
				}
				coreFlash = BLINK_PEAK * Math.max(0, lit) ** 2;
			}

			// --- the alien ------------------------------------------------------------------
			// The antennae flap on a win only, per the brief. The AMPLITUDE eases in rather than the
			// flap switching on: the phase runs all the time, so gating it would start the antennae
			// at whatever angle the sine happened to be at. The bob is the alien's one piece of idle
			// life, and it is tiny — the brief asks for a core that blinks while everything else
			// holds still, not for a symbol that never settles.
			amp += ((win ? FLAP : 0) - amp) * (1 - Math.exp(-dt / SPIN_TAU));
			phaseL += (dt / FLAP_P_L) * Math.PI * 2;
			phaseR += (dt / FLAP_P_R) * Math.PI * 2;
			flapL = amp * Math.sin(phaseL + P * 6.28);
			flapR = -amp * Math.sin(phaseR + P * 5.1);
			headY = (win ? BOB_WIN : BOB_IDLE) * H * Math.sin(t * (win ? 6.2 : 1.3) + P * 6.28);
		};
		raf = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(raf);
	});
</script>

<Container x={props.x} y={props.y} alpha={props.alpha ?? 1} zIndex={props.zIndex}>
	<!-- The galaxy, BEHIND the ring: the base texture has the ring's hole punched out of it, and the
	     core is what shows through. It is wider than that hole, so its own rim stays hidden. -->
	<Sprite
		key="portalCore"
		anchor={0.5}
		x={CORE.dx * W}
		y={CORE.dy * H}
		width={CORE.w * W}
		height={CORE.h * H}
		rotation={coreRot}
	/>
	<!-- The blink's ghost, kept mounted at alpha 0 rather than toggled with {#if}: a tint can only
	     scale a texture's channels DOWN, so it can darken the galaxy but never light it. -->
	<Sprite
		key="portalCore"
		blendMode="add"
		tint={CORE_GLOW}
		alpha={coreFlash}
		anchor={0.5}
		x={CORE.dx * W}
		y={CORE.dy * H}
		width={CORE.w * W}
		height={CORE.h * H}
		rotation={coreRot}
	/>
	<!-- The ring and the four pins. -->
	<Sprite key={props.assetKey} anchor={0.5} width={W} height={H} />
	<!-- Antennae UNDER the head: they were cut at the head's own circle, so the head is what hides
	     each joint while the antenna leans. Anchored at the stalk base rather than the box centre,
	     or the whole antenna slides sideways instead of pivoting. -->
	<Sprite
		key="portalAntennaL"
		anchor={PIVOT_L}
		x={(ANTENNA_L.dx + ANTENNA_L.w * (PIVOT_L.x - 0.5)) * W}
		y={(ANTENNA_L.dy + ANTENNA_L.h * (PIVOT_L.y - 0.5)) * H + headY}
		width={ANTENNA_L.w * W}
		height={ANTENNA_L.h * H}
		rotation={flapL}
	/>
	<Sprite
		key="portalAntennaR"
		anchor={PIVOT_R}
		x={(ANTENNA_R.dx + ANTENNA_R.w * (PIVOT_R.x - 0.5)) * W}
		y={(ANTENNA_R.dy + ANTENNA_R.h * (PIVOT_R.y - 0.5)) * H + headY}
		width={ANTENNA_R.w * W}
		height={ANTENNA_R.h * H}
		rotation={flapR}
	/>
	<Sprite
		key="portalHead"
		anchor={0.5}
		x={HEAD.dx * W}
		y={HEAD.dy * H + headY}
		width={HEAD.w * W}
		height={HEAD.h * H}
	/>
</Container>
