<script lang="ts">
	import { Container, Graphics, Sprite } from 'pixi-svelte';

	// The SCATTER cell, assembled live from three textures instead of drawn as one flat symbol.
	//
	// The Figma lockup is a single flat composition, so scripts/build-scatter-art.py cuts it into
	// the machine with an EMPTY tube (scatter.webp) plus the alien and its eye as loose layers.
	// That split exists for one reason: the alien has to move independently of the capsule, and the
	// bubbles have to pass BEHIND it. Both are impossible against baked art.
	//
	// Why this owns the cell rather than extending the board's shared idle Graphics: that Graphics
	// is one board-wide additive layer drawn in FRONT of every symbol, so anything drawn into it
	// sits on top of the alien and reads as light on the glass, not as bubbles in the fluid. Here
	// the draw order is base -> bubbles -> alien -> eye -> arcs, so depth is real.
	//
	//   idle — the eye blinks on its own schedule, a few bubbles drift up the tube, both glowing
	//          bands breathe, and a shine crosses the baked SCATTER glyphs.
	//   win  — the alien hops with squash-and-stretch, the tube fills with bubbles, and lightning
	//          arcs across the dome visor and the lower band together.
	//
	// One rAF per scatter cell, drawing imperatively into captured Graphics — the same pattern as
	// <SymbolWinFx>, so no Svelte reactivity sits in the render path.

	type Props = {
		/** Base capsule texture key (desktop / mobile / landscape variant picked by the caller). */
		assetKey: string;
		x: number;
		y: number;
		width: number;
		height: number;
		alpha?: number;
		zIndex?: number;
		/** 0..1 — de-phases every cell so two scatters never blink or bubble in lockstep. */
		phase?: number;
		/** Win choreography: hop, dense bubbles, lightning across both bands. */
		winning?: boolean;
	};
	const props: Props = $props();

	// Placements as fractions of the symbol BOX, offset from its centre. Generated by
	// scripts/build-scatter-art.py from the Figma node rects — re-run it rather than nudging these,
	// or the layers drift off the capsule they were cut from.
	const ALIEN = { dx: -0.0012, dy: -0.0311, w: 0.309, h: 0.4725 };
	const EYE = { dx: -0.0012, dy: -0.0458, w: 0.1188, h: 0.1476 };
	const DOME_BAND = { dx: -0.0008, dy: -0.2862, w: 0.1679, h: 0.0591 };
	const LOWER_BAND = { dx: -0.0004, dy: 0.2261, w: 0.1306, h: 0.0437 };
	const TUBE = { dx: -0.001, dy: -0.0452, w: 0.4015, h: 0.4152 };
	const WORD = { dx: 0.0015, dy: 0.3163, w: 0.564, h: 0.1932 };
	// The lid, drawn again over the alien. Full canvas width, top-aligned.
	const DOME_FRONT = { dy: -0.375, h: 0.25 };

	const GLASS = 0x7fe6ff;
	const BAND = 0xc06bff;
	const BAND_HOT = 0xffffff;
	const WORD_COLOR = 0xa9e64b;

	/** Seconds between blinks, and how long one takes. */
	const BLINK_GAP = 4.2;
	const BLINK_DUR = 0.16;
	/** Win hop period, seconds. */
	const HOP_P = 0.72;
	// Hop height, fraction of the box. The alien clears its lid by only 0.0187 of the box at rest
	// (measured by build-scatter-art.py, printed as HOP_LIMIT), so a hop worth seeing MUST go
	// behind <scatterDome> -- which is exactly why that layer exists. Raising this past ~0.09 just
	// buries more of the head with no more apparent travel.
	const HOP_H = 0.07;
	const IDLE_BUBBLES = 4;
	const WIN_BUBBLES = 14;

	// NB: every draw helper below works in CONTAINER-RELATIVE coordinates. The <Container> is
	// already translated to (props.x, props.y), so adding those again puts the bubbles and arcs a
	// whole cell away from the capsule they belong to.
	type G = {
		destroyed: boolean;
		clear: () => void;
		circle: (x: number, y: number, r: number) => unknown;
		ellipse: (x: number, y: number, rx: number, ry: number) => unknown;
		moveTo: (x: number, y: number) => void;
		lineTo: (x: number, y: number) => void;
		stroke: (s: object) => void;
		fill: (s: object) => void;
	};
	let backG = $state<G | null>(null);
	let frontG = $state<G | null>(null);

	// Layer transforms, written by the rAF; the Sprites just bind them.
	let alienY = $state(0);
	let alienSX = $state(1);
	let alienSY = $state(1);
	let eyeOpen = $state(1);
	let rot = $state(0);
	let pulse = $state(1);

	const W = $derived(props.width);
	const H = $derived(props.height);
	const P = $derived(props.phase ?? 0);

	/** Deterministic 0..1 from an integer — used to make "random" bubbles reproducible per cell. */
	const hash = (n: number) => (((n * 2654435761) % 1000) + 1000) % 1000 / 1000;

	// Bubbles rise on independent loops. Each one's horizontal drift, size and speed come from its
	// index, and every cycle re-rolls whether it appears at all — that is what "only a few, at
	// random" means here: a fixed column of bubbles reads as a machine, not a liquid.
	const drawBubbles = (g: G, t: number, count: number, dense: boolean) => {
		const tubeX = TUBE.dx * W;
		const tubeY = TUBE.dy * H;
		const tw = TUBE.w * W;
		const th = TUBE.h * H;
		for (let i = 0; i < count; i++) {
			const seed = i + 1;
			const speed = (dense ? 0.62 : 0.3) * (0.7 + hash(seed * 17) * 0.6);
			const cycle = t * speed + hash(seed * 31) + P;
			const turn = Math.floor(cycle);
			// Re-rolled per lap, so a bubble that skipped this lap can appear on the next.
			if (!dense && hash(turn * 7919 + seed * 104729) > 0.55) continue;
			const u = cycle - turn; // 0..1 up the tube
			const rise = 1 - u;
			// Sideways sway, plus a per-lap column so they do not retrace one path.
			const lane = hash(turn * 6151 + seed * 3571) - 0.5;
			const bx = tubeX + lane * tw * 0.72 + Math.sin(u * 6.28 * 1.5 + seed) * tw * 0.05;
			const by = tubeY + (rise - 0.5) * th * 0.92;
			const r = tw * (0.018 + hash(seed * 53) * 0.022) * (dense ? 1.15 : 1);
			// Fade in off the floor and out at the surface so none of them pop.
			const fade = Math.min(1, u * 6) * Math.min(1, rise * 5);
			g.circle(bx, by, r);
			g.fill({ color: GLASS, alpha: 0.5 * fade });
			g.circle(bx - r * 0.3, by - r * 0.3, r * 0.4);
			g.fill({ color: 0xffffff, alpha: 0.5 * fade });
		}
	};

	/** A jagged arc across one band, redrawn every frame so it crackles rather than loops. */
	const drawBandArc = (
		g: G,
		band: { dx: number; dy: number; w: number; h: number },
		t: number,
		fire: number,
	) => {
		if (fire <= 0.01) return;
		const cx = band.dx * W;
		const cy = band.dy * H;
		const bw = band.w * W;
		const bh = band.h * H;

		// Charge glow first, so the arc reads as sitting inside a lit band.
		for (let k = 0; k < 3; k++) {
			g.ellipse(cx, cy, (bw / 2) * (0.9 + 0.16 * k), (bh / 2) * (1.1 + 0.7 * k));
			g.fill({ color: BAND, alpha: 0.16 * fire * (1 - k * 0.28) });
		}

		const SEGS = 9;
		for (let pass = 0; pass < 2; pass++) {
			g.moveTo(cx - bw / 2, cy);
			for (let i = 1; i <= SEGS; i++) {
				const f = i / SEGS;
				// Pinned at both ends, loosest in the middle — an arc bridging the band's terminals.
				const spread = Math.sin(f * Math.PI);
				const jit = Math.sin(t * 53 + i * 2.7 + P * 6 + pass) * bh * 0.42 * spread;
				g.lineTo(cx - bw / 2 + bw * f, cy + jit);
			}
			g.stroke({
				width: bh * (pass === 0 ? 0.34 : 0.14),
				color: pass === 0 ? BAND : BAND_HOT,
				alpha: (pass === 0 ? 0.6 : 0.95) * fire,
				cap: 'round',
				join: 'round',
			});
		}
	};

	/** Idle breathing on a band — the machine is powered even between spins. */
	const drawBandGlow = (
		g: G,
		band: { dx: number; dy: number; w: number; h: number },
		pulseAmt: number,
	) => {
		const cx = band.dx * W;
		const cy = band.dy * H;
		for (let k = 0; k < 3; k++) {
			g.ellipse(cx, cy, (band.w * W / 2) * (0.86 + 0.14 * k), (band.h * H / 2) * (1 + 0.6 * k));
			g.fill({ color: BAND, alpha: (0.09 - 0.024 * k) * (0.45 + 0.55 * pulseAmt) });
		}
	};

	// The word SCATTER is baked into the plate, so the glyphs cannot be animated — but light can be
	// moved across them. Additive, so this reads as a shine crossing the letters.
	const WORD_PERIOD = 3.1;
	const WORD_FRAC = 0.22;
	const drawWordShine = (g: G, t: number) => {
		const cx = WORD.dx * W;
		const cy = WORD.dy * H;
		const bw = WORD.w * W;
		const bh = WORD.h * H;
		const cycle = (t / WORD_PERIOD + P) % 1;
		if (cycle > WORD_FRAC) return;
		const u = cycle / WORD_FRAC;
		const strength = Math.sin(u * Math.PI) ** 0.7;
		const sx = cx - bw / 2 + bw * u;
		for (let k = 0; k < 3; k++) {
			g.ellipse(sx, cy, bw * (0.05 + 0.03 * k), bh * (0.5 + 0.16 * k));
			g.fill({ color: WORD_COLOR, alpha: (0.2 - 0.05 * k) * strength });
		}
	};

	$effect(() => {
		const t0 = performance.now();
		let raf = 0;
		const tick = () => {
			raf = requestAnimationFrame(tick);
			const t = (performance.now() - t0) / 1000;
			const win = props.winning === true;

			// --- eye ------------------------------------------------------------------------
			// Blinks are scheduled, not sinusoidal: a sine would leave the eye half-shut most of
			// the time, which reads as sleepy rather than alive.
			const bt = (t + P * BLINK_GAP) % BLINK_GAP;
			if (bt < BLINK_DUR) {
				const u = bt / BLINK_DUR;
				eyeOpen = Math.max(0.06, Math.abs(Math.cos(u * Math.PI)));
			} else {
				eyeOpen = 1;
			}

			// --- alien ----------------------------------------------------------------------
			if (win) {
				// Hop with anticipation: squash on the floor, stretch off it, squash on landing.
				const u = (t / HOP_P + P) % 1;
				const air = Math.sin(u * Math.PI); // 0 on the ground, 1 at apex
				alienY = -(air ** 0.7) * H * HOP_H;
				const land = Math.max(0, 1 - Math.abs(u - 0) * 8, 1 - Math.abs(u - 1) * 8);
				alienSY = 1 + air * 0.1 - land * 0.16;
				alienSX = 1 - air * 0.06 + land * 0.12;
				pulse = 1 + 0.03 * air;
				rot = 0.02 * Math.sin(t * 3.3 + P * 6);
			} else {
				// A slow float so the alien is never dead still between spins.
				alienY = Math.sin(t * 1.15 + P * 6.28) * H * 0.008;
				alienSX = 1;
				alienSY = 1;
				pulse = 1;
				rot = 0;
			}

			// --- draw -----------------------------------------------------------------------
			if (backG?.destroyed) backG = null;
			if (frontG?.destroyed) frontG = null;
			if (backG) {
				backG.clear();
				drawBubbles(backG, t, win ? WIN_BUBBLES : IDLE_BUBBLES, win);
			}
			if (frontG) {
				frontG.clear();
				const breathe = 0.5 + 0.5 * Math.sin(t * 1.5 + P * 6.28);
				if (win) {
					// Both bands fire, the lower one a half-beat behind so the machine reads as
					// discharging upward rather than flashing as one lamp.
					const beat = 0.5 + 0.5 * Math.sin((t / 0.42 + P) * 6.28);
					drawBandArc(frontG, DOME_BAND, t, 0.55 + 0.45 * beat);
					drawBandArc(frontG, LOWER_BAND, t + 0.21, 0.55 + 0.45 * (1 - beat));
				} else {
					drawBandGlow(frontG, DOME_BAND, breathe);
					drawBandGlow(frontG, LOWER_BAND, breathe);
				}
				drawWordShine(frontG, t);
			}
		};
		raf = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(raf);
	});
</script>

<Container x={props.x} y={props.y} alpha={props.alpha ?? 1} zIndex={props.zIndex}>
	<!-- The machine, with an empty tube. -->
	<Sprite key={props.assetKey} anchor={0.5} width={W * pulse} height={H * pulse} rotation={rot} />
	<!-- Bubbles sit between the glass and the alien — this is the whole reason the alien is a
	     separate texture rather than part of the plate. -->
	<Graphics blendMode="add" draw={(gr) => (backG = gr as unknown as G)} />
	<Sprite
		key="scatterAlien"
		anchor={0.5}
		x={ALIEN.dx * W}
		y={ALIEN.dy * H + alienY}
		width={ALIEN.w * W * alienSX}
		height={ALIEN.h * H * alienSY}
	/>
	<!-- The eye rides the alien's hop and squash, and closes by collapsing its own height. -->
	<Sprite
		key="scatterEye"
		anchor={0.5}
		x={EYE.dx * W}
		y={EYE.dy * H + alienY + (ALIEN.h * H * (alienSY - 1)) * 0.18}
		width={EYE.w * W * alienSX}
		height={EYE.h * H * alienSY * eyeOpen}
	/>
	<!-- The lid again, ON TOP: this is what lets the alien hop without drawing over the machine's
	     metal top. At rest it composites pixel-identically over the base. -->
	<Sprite
		key="scatterDome"
		anchor={0.5}
		x={0}
		y={DOME_FRONT.dy * H}
		width={W * pulse}
		height={DOME_FRONT.h * H * pulse}
	/>
	<Graphics blendMode="add" draw={(gr) => (frontG = gr as unknown as G)} />
</Container>
