<script lang="ts" module>
	// MOTHERSHIP splash (design composite 9041:26790): the observation deck, its sky carrying two
	// drifting clouds, a green moon and a small planet, the logo centred, and three feature panels
	// in a row. Everything here is generated by scripts/build-splash-art.py, which also MEASURES the
	// placements below off the design composite.
	//
	// The pillar machine and the loose floor parts (coil / chip / magnet / cable / ring) that this
	// splash used to carry are gone: the new design has a clean floor, and the pillar was the magnet
	// capsule, which was removed from the game entirely.
	const roomSrc = './assets/components/splash/room.webp?v=20260901c';
	// The mobile splash is its own painting (Figma 4277:5883, backdrop node 9128:28701): a TALL
	// window over the same valley, not the landscape room centre-cropped. Cropping the landscape one
	// to 9:16 threw away both window jambs and most of the valley, which is why the portrait splash
	// never matched the design.
	const roomMobileSrc = './assets/components/splash/room_mobile.webp?v=20260911';
	// Same URL (incl. ?v=) as assets.ts, so the browser reuses the bytes pixi already downloaded
	// instead of fetching the same plate twice under two versions.
	const logoSrc = './assets/components/splash/logo_plate.webp?v=20260901b';
	// PORTRAIT flies the lockup in as two pieces — the plate WITHOUT its baked saucer, and that
	// saucer on its own, arriving from deep in the sky. Both are cut from the one lockup by
	// scripts/build-room-art.py, so when they land they ARE logo_plate.webp, which is what
	// GameLogoFrame draws on the other side of the hand-off.
	//
	// The saucer is the lockup's own and not ui/ufo_ship.webp, the design's standalone sky ship:
	// that one's dome is empty, and this is the mark's saucer, so it has to have the alien in it
	// (user, 2026-09-11).
	const logoBareSrc = './assets/components/splash/logo_plate_bare.webp?v=20260911';
	const shipSrc = './assets/components/splash/logo_saucer.webp?v=20260911';
	const panelSrc = './assets/components/splash/panel.webp?v=20260901c';
	const moonSrc = './assets/components/splash/moon.webp?v=20260911';
	const planetSrc = './assets/components/splash/planet.webp?v=20260911';
	const cloudASrc = './assets/components/splash/cloud_a.webp?v=20260901c';
	const cloudBSrc = './assets/components/splash/cloud_b.webp?v=20260901c';
	const polaritySrc = './assets/components/splash/polarity.webp?v=20260902';
	// Same URL (incl. ?v=) as assets.ts so the browser reuses the bytes pixi already downloaded.
	const brandSrc = './assets/components/ui/press_play_logo.webp?v=20260709';

	// Everything this splash paints, for LoadingController's HTML-image pass (these are plain <img>/CSS
	// images, invisible to the pixi loader). Built from the consts above so a path or ?v= edit can
	// never desync the preload list.
	export const SPLASH_INTRO_IMAGES = [
		roomSrc,
		roomMobileSrc,
		logoSrc,
		logoBareSrc,
		shipSrc,
		panelSrc,
		moonSrc,
		planetSrc,
		cloudASrc,
		cloudBSrc,
		brandSrc,
	];
</script>

<script lang="ts">
	import { onMount } from 'svelte';
	import { fade } from 'svelte/transition';
	import { stateI18nDerived } from 'state-shared';
	import LoadingMark from './LoadingMark.svelte';
	import { getContext } from '../game/context';
	import { PORTRAIT_SHIP_RISE_OF_LOGO, PORTRAIT_SHIP_W_OF_LOGO } from '../game/stateGame.svelte';
	import { MAX_WIN_LABEL } from '../game/config';

	// `loading` = the pre-game phase (Figma node 7219:5322): the SAME room backdrop this splash uses,
	// dimmed and blurred, with the Press Play progress mark on it. It is one component and one DOM
	// subtree on purpose — the handover to the splash proper is then just the backdrop easing back to
	// full brightness while the splash pieces fly in over it, with nothing reloaded or re-created.
	type Props = {
		onpress: () => void;
		ondone: () => void;
		loading?: boolean;
		progress?: number;
	};
	const props: Props = $props();
	const loading = $derived(props.loading ?? false);

	const context = getContext();

	// The backdrop is the first pixel the player sees, so fade it in the moment it decodes rather
	// than letting it pop mid-load. (LoadingController warms the same URL in its HTML pass; the
	// browser serves both from one request.)
	// ── Cloud field ──
	// The design scatters a handful of clouds across the sky; the brief is for them to move. Rather
	// than animate the design's exact positions (which would read as a repeating strip), each cloud
	// gets its own lane, size, speed and phase, drawn ONCE on mount. Periods are deliberately
	// coprime-ish and long, so no two clouds ever line up twice in a session.
	//
	// Pure CSS animation from here: six transforms the compositor owns, no rAF, nothing reactive.
	const CLOUD_COUNT = 6;
	const clouds = Array.from({ length: CLOUD_COUNT }, (_, id) => {
		const big = id % 2 === 0;
		return {
			id,
			big,
			// Kept in the upper sky: above ~9% is the window's top frame (the sky layer is clipped to
			// the opening, so a cloud placed higher would simply be cut in half), and below ~34% the
			// panels and the logo take over.
			top: 9 + Math.random() * 23,
			// Widths as a % of the frame. The two source shapes differ, so the big one is given less
			// spread — at the top of its range it starts to read as scenery rather than a cloud.
			size: big ? 9 + Math.random() * 4 : 4.5 + Math.random() * 3,
			dur: 70 + Math.random() * 90,
			// Negative delay starts each one mid-crossing, so the sky is populated on the first frame
			// instead of filling up from the left edge over the first minute.
			delay: -Math.random() * 90,
			fade: (0.5 + Math.random() * 0.4).toFixed(2),
		};
	});

	let roomReady = $state(false);
	onMount(() => {
		const img = new Image();
		img.onload = img.onerror = () => (roomReady = true);
		img.src = roomSrc;
	});

	const t = (key: string) => stateI18nDerived.translate(key);

	// Titles are fixed-size with `white-space: pre` (no wrapping), so long words in some languages
	// (e.g. Russian "РАСШИРЯЮЩИЕСЯ") overflow the card. Shrink the font to fit the card width.
	function fitTitle(node: HTMLElement, _dep?: unknown) {
		const apply = () => {
			const parent = node.parentElement;
			if (!parent) return;
			node.style.fontSize = '';
			const target = parent.clientWidth * 0.92;
			const natural = node.scrollWidth;
			if (target > 0 && natural > target) {
				const base = parseFloat(getComputedStyle(node).fontSize);
				node.style.fontSize = `${Math.max(6, (base * target) / natural)}px`;
			}
		};
		const ro = new ResizeObserver(apply);
		if (node.parentElement) ro.observe(node.parentElement);
		requestAnimationFrame(apply);
		(document as Document).fonts?.ready.then(apply);
		return { update: apply, destroy: () => ro.disconnect() };
	}

	// Mobile = portrait viewport: show the three feature panels one at a time, 3s each.
	let isPortrait = $state(false);
	let slide = $state(0);
	const SLIDE_COUNT = 3;
	const updateOrientation = () => (isPortrait = window.innerWidth < window.innerHeight);

	// ── Console lamps ──
	// The room painting has a lit control console under the window's left chamfer: four pink pills
	// on a slanted plate. They are PAINT — the same flat pink whatever the scene does — and the ask
	// (2026-09-21) was for them to read as real lights. Each pill's box is measured off the art
	// itself (bright pink ink, R>200 B>200 G<190: bboxes x116-152 / 123-160 / 129-166 / 136-173,
	// rows 840-850 / 861-871 / 881-891 / 902-912 of room.webp 1920x1072; x52-85 ... x71-102, rows
	// 1567-1643 of room_mobile.webp 1080x1919), as percentages of the art. Both rooms are drawn
	// `cover` on a stage of the art's own aspect (1201/671 vs 1920/1072; 9/16 vs 1080/1919), so
	// art fractions are stage fractions to within a pixel. The pills lean ~4° with the plate.
	const CONSOLE_LAMPS_LANDSCAPE = [
		{ x: 6.98, y: 78.82, w: 1.93, h: 1.03 },
		{ x: 7.37, y: 80.78, w: 1.93, h: 1.03 },
		{ x: 7.68, y: 82.65, w: 1.93, h: 1.03 },
		{ x: 8.05, y: 84.61, w: 1.93, h: 1.03 },
	];
	const CONSOLE_LAMPS_PORTRAIT = [
		{ x: 6.34, y: 81.92, w: 3.15, h: 0.63 },
		{ x: 6.9, y: 83.06, w: 3.15, h: 0.63 },
		{ x: 7.45, y: 84.16, w: 3.15, h: 0.63 },
		{ x: 8.01, y: 85.3, w: 3.15, h: 0.63 },
	];
	const consoleLamps = $derived(isPortrait ? CONSOLE_LAMPS_PORTRAIT : CONSOLE_LAMPS_LANDSCAPE);

	onMount(updateOrientation);

	$effect(() => {
		if (!isPortrait) {
			slide = 0;
			return;
		}
		const id = setInterval(() => (slide = (slide + 1) % SLIDE_COUNT), 3000);
		return () => clearInterval(id);
	});

	// ── logo handoff ──
	// On press the game mounts BEHIND this overlay (onpress), the scenery fades out, and the logo
	// plate flies (FLIP) from its splash spot to the exact rect where GameLogoFrame will draw the
	// same art. GameLogoFrame keeps its sprite hidden (stateGame.logoHandoffActive) until `finish`,
	// so the landing is a seamless swap under the overlay's closing fade (ondone).
	let leaving = $state(false);
	let flyStyle = $state('');
	let shipFlyStyle = $state('');
	let logoEl: HTMLImageElement | undefined = $state();
	let shipEl: HTMLImageElement | undefined = $state();
	let finished = false;

	// Where GameLogoFrame draws the logo, in viewport CSS px — the same maths as GameLogoFrame,
	// then main-coords → canvas px → client px via the live canvas rect.
	function targetLogoRect() {
		const main = context.stateLayoutDerived.mainLayout();
		const canvas = context.stateLayoutDerived.canvasSizes();
		const scale = main.scale || 1;
		const canvasEl = document.querySelector('canvas');
		if (!canvasEl || !canvas.width) return null;
		const cRect = canvasEl.getBoundingClientRect();
		const unit = cRect.width / canvas.width;
		const canvasLeftMain = main.width * 0.5 - canvas.width / (2 * scale);
		const canvasTopMain = main.height * 0.5 - canvas.height / (2 * scale);
		let cx: number, cy: number, w: number;
		if (context.stateLayoutDerived.layoutType() === 'portrait') {
			// Straight from stateGame, which is also what GameLogoFrame draws — these were literal
			// copies of its old numbers, so every resize of the in-game logo left the plate flying to
			// a stale spot at a stale size.
			cx = main.width * 0.5;
			cy = context.stateGameDerived.portraitLogoCY();
			w = context.stateGameDerived.portraitLogoWidth();
		} else {
			// The SAME rect GameLogoFrame draws, not a second copy of its formula — a copy is what made
			// the mark jump on landing the moment the landscape logo moved onto its design spot.
			const rect = context.stateGameDerived.landscapeLogoRect();
			cx = rect.cx;
			cy = rect.cy;
			w = rect.w;
		}
		return {
			cx: cRect.left + (cx - canvasLeftMain) * scale * unit,
			cy: cRect.top + (cy - canvasTopMain) * scale * unit,
			w: w * scale * unit,
		};
	}

	function finish() {
		if (finished) return;
		finished = true;
		context.stateGame.logoHandoffActive = false;
		props.ondone();
	}

	function handlePress() {
		if (leaving || loading) return;
		leaving = true;
		const rect = logoEl?.getBoundingClientRect();
		const target = rect && rect.width > 0 ? targetLogoRect() : null;
		if (target) {
			const dx = target.cx - (rect!.left + rect!.width / 2);
			const dy = target.cy - (rect!.top + rect!.height / 2);
			flyStyle = `--fly-x:${dx.toFixed(1)}px;--fly-y:${dy.toFixed(1)}px;--fly-s:${(target.w / rect!.width).toFixed(4)}`;
			// The saucer flies WITH the plate, on the same scale and the same curve, to where it sits
			// on the in-game lockup — the two pieces travel as one object and land as one sprite. It
			// cannot share the plate's deltas: each element's scale acts about its OWN centre, so the
			// saucer needs its own translate to keep the gap between the two shrinking with them.
			const sRect = shipEl?.getBoundingClientRect();
			if (sRect && sRect.width > 0) {
				const shipCX = target.cx;
				const shipCY = target.cy - PORTRAIT_SHIP_RISE_OF_LOGO * target.w;
				shipFlyStyle =
					`--fly-x:${(shipCX - (sRect.left + sRect.width / 2)).toFixed(1)}px;` +
					`--fly-y:${(shipCY - (sRect.top + sRect.height / 2)).toFixed(1)}px;` +
					`--fly-s:${((PORTRAIT_SHIP_W_OF_LOGO * target.w) / sRect.width).toFixed(4)}`;
			}
			context.stateGame.logoHandoffActive = true;
		}
		props.onpress();
		if (!target) {
			finish();
			return;
		}
		// animationend on the flight is the happy path; the timeout catches it if the animation
		// never runs (display quirk, reduced-motion edge) so the overlay can never get stuck.
		setTimeout(finish, 1400);
	}
	function handleLogoAnimEnd(e: AnimationEvent) {
		if (e.animationName.includes('logo-fly')) finish();
	}
	function handleKey(e: KeyboardEvent) {
		if (e.code === 'Space' || e.code === 'Enter') handlePress();
	}

	/** The BONUS GAMES card's three scatter tiers, in the design's order. */
	const TIERS = [
		{ count: 3, key: 'SPLASH GRAVITY BREACH' },
		{ count: 4, key: 'SPLASH CORE OVERLOAD' },
		{ count: 5, key: 'SPLASH ZERO POINT' },
	] as const;

	/**
	 * "%count% scatters for" with the NUMBER lifted out, so it can take its own colour the way the
	 * design sets it. Split on the placeholder rather than formatting the string and then hunting
	 * for the digit: the count does not come first in every locale.
	 */
	const scatterLine = (count: number) => {
		const [before, after] = t('SPLASH SCATTERS FOR').split('%count%');
		return { before: before ?? '', after: after ?? '' };
	};
</script>

<svelte:window onkeydown={handleKey} onresize={updateOrientation} />

<div
	class="splash-intro"
	class:leaving
	class:loading
	role="button"
	tabindex="0"
	onclick={handlePress}
	onkeydown={handleKey}
>
	<!-- Per-panel content by index (0 = BONUS GAMES, 1 = POLARITY SHIFTER, 2 = MAX WIN). -->
	{#snippet panelText(i: number)}
		{#if i === 0}
			<div class="f-title f-green" use:fitTitle={t('SPLASH BONUS TITLE')}>
				{t('SPLASH BONUS TITLE')}
			</div>
			{#each TIERS as tier (tier.count)}
				{@const line = scatterLine(tier.count)}
				<div class="f-sub">
					{line.before}<span class="f-count">{tier.count}</span>{line.after}
				</div>
				<div class="f-key f-gold">{t(tier.key)}</div>
			{/each}
		{:else if i === 1}
			<div class="f-title f-pink" use:fitTitle={t('SPLASH POLARITY TITLE')}>
				{t('SPLASH POLARITY TITLE')}
			</div>
			<img class="f-icon" src={polaritySrc} alt="" draggable="false" />
			<div class="f-sub">{t('SPLASH POLARITY BODY')}</div>
		{:else}
			<div class="f-title f-gold" use:fitTitle={t('SPLASH MAX TITLE')}>{t('SPLASH MAX TITLE')}</div>
			<div class="f-sub">{t('SPLASH UP TO')}</div>
			<div class="f-value f-pink">{MAX_WIN_LABEL}X</div>
			<div class="f-sub">{t('SPLASH MULTIPLIER')}</div>
		{/if}
	{/snippet}

	<!-- Sky. Placements are MEASURED off the design composite by scripts/build-splash-art.py; the
	     clouds are the exception — the design scatters them, and the brief is for them to drift, so
	     each one gets its own lane, size, speed and start offset. Six clouds from two shapes, with no
	     two sharing a lane or a period, so the sky never resolves into a visible loop. -->
	{#snippet sky()}
		<!-- Everything in here is OUTSIDE, so it is clipped to the window's opening: the room art is a
		     bulkhead with a hole in it, and a cloud that drifts over the frame's metal reads as a
		     cloud inside the ship. -->
		<span class="sky-clip">
			<span class="sky-hold moon-hold">
				<img class="sky-body moon" src={moonSrc} alt="" draggable="false" />
			</span>
			<span class="sky-hold planet-hold">
				<img class="sky-body planet" src={planetSrc} alt="" draggable="false" />
			</span>
			{#each clouds as c (c.id)}
				<img
					class="cloud"
					src={c.big ? cloudASrc : cloudBSrc}
					style={`--top:${c.top}%;--size:${c.size}%;--dur:${c.dur}s;--delay:${c.delay}s;--fade:${c.fade}`}
					alt=""
					draggable="false"
				/>
			{/each}
		</span>
	{/snippet}

	<!-- ONE stage for both phases. `.stage` owns the geometry (and is the container the cq units in
	     this file resolve against); `.shake` inside it carries the impact animations, so those can
	     start when the intro starts without restarting the stage's own fade-in. `.room-bg` lives
	     outside the phase branch and is never re-created: loading→intro is a pure CSS transition on
	     it, which is exactly why the handover has no reload flash. -->
	<div class="stage" class:stage--m={isPortrait}>
		<div class="shake" class:shake--intro={!loading}>
			<div
				class="room-bg"
				class:room-bg--ready={roomReady}
				class:room-bg--dim={loading}
				style={`background-image: url('${isPortrait ? roomMobileSrc : roomSrc}')`}
			>
				<!-- The console's four lamps, lit: a hot core over the painted pill and a spill of its
				     own pink over the plate, chasing down the column. Inside .room-bg so they take its
				     loading dim/blur and its handover fade with the paint they sit on. -->
				{#each consoleLamps as lamp, i (i)}
					<span
						class="console-lamp"
						style:left="{lamp.x}%"
						style:top="{lamp.y}%"
						style:width="{lamp.w}%"
						style:height="{lamp.h}%"
						style:--i={i}
					></span>
				{/each}
			</div>

			{#if loading}
				<!-- Figma 7219:5322 — the lockup sits dead centre of the frame. -->
				<div class="loader" out:fade={{ duration: 280 }}>
					<LoadingMark progress={props.progress ?? 0} />
				</div>
			{:else if isPortrait}
				<!-- Portrait: same pieces recomposed — sky + logo up top, one panel at a time below. -->
				<img class="brand brand--m" src={brandSrc} alt="Press Play" draggable="false" />
				{@render sky()}
				<!-- The lockup's own saucer, arriving from deep in the sky onto the plate it was cut
				     off. It sits OVER the plate, where the lockup draws it, and it flies to the
				     in-game lockup with the plate rather than fading out with the scenery. -->
				<img
					class="ship-m"
					class:ship-m--fly={leaving && shipFlyStyle}
					style={shipFlyStyle}
					bind:this={shipEl}
					src={shipSrc}
					alt=""
					draggable="false"
				/>
				<img
					class="logo logo--m"
					class:logo--fly={leaving && flyStyle}
					style={flyStyle}
					bind:this={logoEl}
					onanimationend={handleLogoAnimEnd}
					src={logoBareSrc}
					alt="Magnetic Mothership"
					draggable="false"
				/>

				<div class="panel panel-m">
					<img class="panel-img" src={panelSrc} alt="" draggable="false" />
					<div class="panel-body">
						{@render panelText(slide)}
					</div>
				</div>

				<div class="dots">
					{#each Array(SLIDE_COUNT) as _, i}
						<span class="dot" class:dot--on={slide === i}></span>
					{/each}
				</div>

				<p class="press-label press-label--m">{t('SPLASH PRESS')} →</p>
			{:else}
				<!-- Landscape: the full 1201x671 Figma stage, height-fit and centred. -->
				<img class="brand" src={brandSrc} alt="Press Play" draggable="false" />
				{@render sky()}
				<img
					class="logo"
					class:logo--fly={leaving && flyStyle}
					style={flyStyle}
					bind:this={logoEl}
					onanimationend={handleLogoAnimEnd}
					src={logoSrc}
					alt="Magnetic Megachain"
					draggable="false"
				/>

				{#each [0, 1, 2] as i}
					<div class="panel panel-{i}">
						<img class="panel-img" src={panelSrc} alt="" draggable="false" />
						<div class="panel-body">
							{@render panelText(i)}
						</div>
					</div>
				{/each}

				<p class="press-label">{t('SPLASH PRESS')} →</p>
			{/if}
		</div>
	</div>
</div>

<style>
	.splash-intro {
		position: absolute;
		inset: 0;
		z-index: 10;
		cursor: pointer;
		outline: none;
		user-select: none;
		overflow: hidden;
		background: #05070f;
		transition: background-color 400ms ease;
		/* The wrapper in Game.svelte is pointer-events:none; re-enable here so the splash itself
		   stays pressable until the handoff starts. */
		pointer-events: auto;
	}

	/* Handoff: the overlay goes see-through and click-through while the LOCKUP flies to its in-game
	   spot; everything else fades. `animation: none` is required — several children carry finished
	   fill-mode:both animations whose final opacity:1 keyframe would override the fade
	   (their base poses equal the animations' end poses, so dropping them doesn't shift anything).
	   The portrait saucer is exempt alongside the plate: it is half of the mark, not scenery, and
	   this rule was both fading it out and killing the flight animation it had just been given —
	   the ship vanished at the hand-off while the wordmark flew on without it (user, 2026-09-11). */
	.splash-intro.leaving {
		background: transparent;
		pointer-events: none;
		cursor: default;
	}
	/* Nothing on the loading screen is pressable — the game is still downloading. */
	.splash-intro.loading {
		cursor: default;
	}
	.leaving .shake > :not(.logo):not(.ship-m) {
		animation: none;
		opacity: 0;
		transition: opacity 320ms ease;
	}

	/* Height-fit 16:9-ish stage (Figma frame is 1201x671), sized to the splash CONTAINER so overlays
	   stay locked to the artwork even when the game area is smaller than the browser window. */
	.stage {
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		height: 100%;
		aspect-ratio: 1201 / 671;
		container-type: size;
		animation: stage-fade 250ms ease-out both;
	}

	/* Impact shakes live on an inner layer rather than on .stage. The stage is mounted for the whole
	   loading phase, so a shake declared there would either have fired during the download or — if
	   toggled by a class — have restarted .stage's own fade and flashed the backdrop. This element
	   fills the stage exactly, so the keyframes are plain deltas around 0 instead of deviations
	   around the stage's centring translate(-50%, -50%). */
	.shake {
		position: absolute;
		inset: 0;
	}
	.shake--intro {
		animation:
			stage-jolt 300ms ease-out 830ms both,
			stage-slam 420ms ease-out 1750ms both;
	}

	/* Room art lives on its own layer (not the stage itself) so the handoff can fade it out while
	   the logo — also a stage child — keeps flying at full opacity.

	   It is also the ONE element shared by the loading screen and the splash. Loading dims and
	   blurs it (Figma 7219:5322: 60% over black, 2px blur); handing over to the splash just drops
	   that class, so the same never-reloaded bitmap eases up to full brightness. */
	.room-bg {
		position: absolute;
		inset: 0;
		background-size: cover;
		background-position: center;
		background-repeat: no-repeat;
		opacity: 0;
		transition:
			opacity 620ms ease,
			filter 620ms ease,
			transform 620ms ease;
	}
	.room-bg--ready {
		opacity: 1;
	}
	/* Scaled a hair so the blur's soft edge stays outside the frame. */
	.room-bg--ready.room-bg--dim {
		opacity: 0.6;
		filter: blur(2px);
		transform: scale(1.012);
	}

	/* A lit lamp over the painted one. `screen` is what makes it light rather than a sticker: the
	   near-white core pushes the pink ink to a hot centre, and the box-shadow rings are the spill
	   over the plate, wide and faint. The whole column breathes in a slow chase, one lamp after the
	   next, and never goes fully dark — a running light is on, it just breathes. Sizes are in cq
	   units so the spill scales with the stage like the pills themselves do. */
	.console-lamp {
		position: absolute;
		display: block;
		transform: translate(-50%, -50%) rotate(-4deg);
		border-radius: 999px;
		background: #ffe0f8;
		mix-blend-mode: screen;
		box-shadow:
			0 0 0.22cqw 0.04cqw #ffb8f0,
			0 0 0.8cqw 0.12cqw #ff6be0,
			0 0 2cqw 0.35cqw rgba(255, 107, 224, 0.55);
		animation: console-chase 2.8s ease-in-out infinite;
		animation-delay: calc(var(--i) * -0.7s);
		pointer-events: none;
	}
	.stage--m .console-lamp {
		transform: translate(-50%, -50%) rotate(-3deg);
		box-shadow:
			0 0 0.5cqw 0.08cqw #ffb8f0,
			0 0 1.6cqw 0.25cqw #ff6be0,
			0 0 4cqw 0.7cqw rgba(255, 107, 224, 0.55);
	}
	@keyframes console-chase {
		0%,
		100% {
			opacity: 0.62;
		}
		30% {
			opacity: 1;
		}
		60% {
			opacity: 0.72;
		}
	}

	/* Loading lockup, centred in the frame. --mark is the tile edge; LoadingMark derives the gap and
	   wordmark from it. Landscape uses cqh (86/671 of the Figma frame), portrait cqw — the portrait
	   stage is taller than the viewport, so its height is not a usable reference. */
	.loader {
		position: absolute;
		left: 50%;
		top: 50%;
		transform: translate(-50%, -50%);
		--mark: 12.82cqh;
		animation: soft-in 450ms ease-out both;
	}
	.stage--m .loader {
		--mark: 18cqw;
	}

	/* Portrait stage: fixed-aspect tall box filling the viewport width, centre-cropped room art. */
	.stage--m {
		width: 100vw;
		height: max(100vh, calc(100vw * 16 / 9));
		aspect-ratio: auto;
	}

	/* ------------------------------------------------------------------ set dressing */

	/* Studio logo, top-right like the design (desktop) / top-centre (portrait). */
	.brand {
		position: absolute;
		right: 2.2%;
		top: 4%;
		width: 9.4%;
		object-fit: contain;
		filter: drop-shadow(0 2px 8px rgba(0, 0, 0, 0.7));
		animation: soft-in 400ms ease-out 150ms both;
	}
	.brand--m {
		right: auto;
		left: 50%;
		transform: translateX(-50%);
		top: 1.5%;
		width: 22%;
	}

	/* ---- sky ----
	   Moon and planet are placed from the design composite (build-splash-art.py prints the numbers).
	   Both turn: the moon slowly on its own axis, the planet faster and the other way, so they read
	   as two separate bodies rather than one animation applied twice. The periods are minutes long —
	   at this size anything quicker looks like a spinning coin, not a world. */
	/* Two layers per body on purpose: the HOLDER drifts and the IMAGE spins. Both are transforms, so
	   on one element the later animation would simply win and one of the two would never run. */
	/* The window's opening, as a share of the stage — an octagon: a top edge between the two upper
	   chamfers, straight sides, and the sill along the bottom. Measured off room.webp.
	   Portrait keeps only the horizontal edges: `background-size: cover` there scales the art to the
	   stage HEIGHT and centre-crops the width, so the vertical fractions still hold but the opening's
	   left and right edges are far outside the viewport. */
	.sky-clip {
		position: absolute;
		inset: 0;
		display: block;
		pointer-events: none;
		clip-path: polygon(12.5% 7.4%, 87.5% 7.4%, 98.6% 27.6%, 98.6% 78%, 1.4% 78%, 1.4% 27.6%);
	}
	/* Portrait runs on a different backdrop (room_mobile.webp), whose window is both taller and
	   higher up: centre-column samples put the sky at 0.052 of the art and the valley's floor at
	   0.828. The old 7.4%..78% came off the landscape room and would have cut the moon's crown. */
	.stage--m .sky-clip {
		clip-path: polygon(0 5.5%, 100% 5.5%, 100% 82%, 0 82%);
	}

	.sky-hold {
		position: absolute;
		display: block;
		transform: translate(-50%, -50%);
	}

	.sky-body {
		display: block;
		width: 100%;
	}

	.moon-hold {
		left: 83.18%;
		top: 27.75%;
		width: 11.17%;
		animation:
			soft-in 600ms ease-out 260ms both,
			moon-float 34s ease-in-out infinite;
	}

	.planet-hold {
		left: 74.6%;
		top: 30.4%;
		width: 4.1%;
		animation:
			soft-in 600ms ease-out 340ms both,
			planet-float 26s ease-in-out infinite;
	}

	/* Minutes per revolution. At this size anything quicker reads as a spinning coin, not a world —
	   and the two differ in speed and direction so they never look like one animation used twice. */
	/* Portrait places both bodies from the mobile design's own frame (nodes 9128:28881 and
	   9128:28882 in the 360x800 board): the moon high on the right, the planet low on the left,
	   where landscape has them side by side near the window's right chamfer. The frame is the
	   stage, so its boxes are stage fractions directly — and `cover` scales the portrait art to
	   the stage HEIGHT, so nothing here needs a background-fraction conversion. */
	.stage--m .moon-hold {
		left: 85.28%;
		top: 18%;
		width: 24.44%;
	}

	.stage--m .planet-hold {
		left: 12.36%;
		top: 27.44%;
		width: 19.72%;
	}

	.moon {
		animation: body-turn 240s linear infinite;
	}

	.planet {
		animation: body-turn-rev 150s linear infinite;
	}

	/* Clouds drift left to right across the whole frame and a bit past both edges, so they enter and
	   leave rather than popping. Every per-cloud value arrives as a CSS var from the field seeded in
	   the script. */
	.cloud {
		position: absolute;
		top: var(--top);
		left: 0;
		width: var(--size);
		opacity: var(--fade);
		pointer-events: none;
		will-change: transform;
		animation: cloud-drift var(--dur) linear var(--delay) infinite;
	}

	.stage--m .cloud {
		/* Portrait shows a narrow slice of the room, so the same widths read tiny. */
		width: calc(var(--size) * 2.1);
	}

	/* Logo plate, dropped like a stone onto the pillar's top drum. Centre-anchored (translate
	   -50%,-50%) at the trimmed art's centre: Figma box 266x199 at top -17 → content centre 76px. */
	/* Measured on the design composite: the lockup (saucer included) spans x 0.291..0.718 and
	   y 0.082..0.549 of the frame, so it overlaps the panels' top edge — which is what seats it on
	   the row rather than floating above it. */
	/* Sized and placed by MEASURING the logo's green wordmark against the design composite, not from
	   the lockup's box: the art carries transparent skirt, so box-to-box matching left it small and
	   high and it stopped meeting the panel row. */
	.logo {
		position: absolute;
		/* ABOVE the panel row. The logo comes first in the DOM (it has to: it is the element the
		   hand-off flight animates, and mount order drives the entrance timings), so without this
		   the panels paint over its lower plate and the alien badge. The design has the lockup
		   sitting ON the row. */
		z-index: 3;
		left: 50.5%;
		top: 31cqh;
		transform: translate(-50%, -50%);
		width: 44cqw;
		filter: drop-shadow(0 4px 18px rgba(0, 0, 0, 0.75));
		--drop-from: -30cqh;
		animation: logo-drop 700ms linear 500ms both;
	}
	/* Portrait logo: 46 -> 42cqw (user pass 2026-08-10, "make logo a bit smaller"). The centre drops
	   0.5cqh with it so the plate's BOTTOM edge stays seated on the pillar drum instead of lifting
	   off it as the art shrinks.

	   Portrait art is the BARE plate (aspect 2.719 against the lockup's 1.664), so at the same width
	   it is shorter and a centre-anchored swap would ride up. The margin puts its centre back where
	   the lockup's plate sat: fitting the bare art into the lockup puts it at y 0.382..0.995, i.e.
	   0.1133 logo WIDTHS below the lockup's centre — 0.1133 x 42cqw. */
	.logo--m {
		top: 14cqh;
		margin-top: 4.76cqw;
		width: 42cqw;
		--drop-from: -22cqh;
	}

	/* The arriving ship, portrait only. Width and offset are the same two fractions the in-game
	   composition uses (PORTRAIT_SHIP_W_OF_LOGO 0.4586 and PORTRAIT_SHIP_RISE_OF_LOGO 0.265 of the
	   plate's width), so the splash and the game park it in the same place:
	     width  0.4586 x 42cqw = 19.26cqw
	     centre 0.265  x 42cqw = 11.13cqw above the plate's centre, i.e. 4.76 - 11.13 = -6.37cqw
	   z-index 2 keeps it under the plate (z-index 3) and over the sky. */
	/* Sized and placed from the saucer's own measured seat on the plate (stateGame.svelte.ts):
	   0.4598 of the plate's width, its centre 0.277 plate-widths above the plate's. The plate is
	   42cqw wide with its centre at 4.76cqw below `top`, so: 0.4598*42 = 19.31cqw across, and
	   4.76 - 0.277*42 = -6.87cqw. z-index 4 puts it OVER the plate, which is how the lockup draws
	   it — its rim and its beam mouth overlap the plate's top edge. */
	.ship-m {
		position: absolute;
		z-index: 4;
		left: 50.5%;
		top: 14cqh;
		margin-top: -6.87cqw;
		width: 19.31cqw;
		transform: translate(-50%, -50%);
		filter: drop-shadow(0 4px 18px rgba(0, 0, 0, 0.55));
		animation: ship-arrive 1900ms linear 200ms both;
	}
	/* Arrival is PROJECTIVE, not a linear zoom: the stops trace 1/(1 + k.distance) with k set by the
	   0.06 start scale, so it barely grows over the first half of the run and then rushes the camera.
	   A linear ramp reads as a zoom; this reads as something flying in. Same model as the in-game
	   flight in Background.svelte, written out as keyframes because CSS has no easing for it. */
	@keyframes ship-arrive {
		0% {
			transform: translate(-50%, calc(-50% - 30cqh)) scale(0.06);
			opacity: 0;
		}
		10% {
			opacity: 1;
		}
		50% {
			transform: translate(-50%, calc(-50% - 16cqh)) scale(0.11);
		}
		75% {
			transform: translate(-50%, calc(-50% - 8cqh)) scale(0.25);
		}
		90% {
			transform: translate(-50%, calc(-50% - 2.5cqh)) scale(0.55);
		}
		100% {
			transform: translate(-50%, -50%) scale(1);
		}
	}

	/* Handoff flight: FLIP to the in-game logo rect. --fly-x/y are viewport-px deltas between the
	   two centres, --fly-s the width ratio; scale acts about the img's own centre so translate alone
	   lands the centre. Declared after .logo so it replaces the entrance animation. */
	.logo--fly,
	.ship-m--fly {
		animation: logo-fly 640ms cubic-bezier(0.55, 0.05, 0.15, 1) both;
	}
	@keyframes logo-fly {
		0% {
			transform: translate(-50%, -50%);
		}
		100% {
			transform: translate(calc(-50% + var(--fly-x)), calc(-50% + var(--fly-y))) scale(var(--fly-s));
		}
	}

	/* ------------------------------------------------------------------ feature panels */

	/* Figma: full panel art squeezed into a 319x280 box at top 263; trimmed art maps to a
	   266x240 box centred at y 397.5 (59.2cqh). Width/height both set: the art is stretched
	   exactly like the design squeezes its square source.

	   Entrances: BONUS GAMES slides in from the LEFT, CORE OVERLOAD from the BOTTOM, MAX WIN from
	   the RIGHT — accelerating approach, then each skids past its mark with a squash along the
	   motion axis. All three are home by ~1750ms, which is when stage-slam + the floor hops fire. */
	/* MEASURED off the design composite, per panel (the middle one's top edge is occluded by the
	   logo there, so the outer two are the reference): interior 0.1983w x 0.4170h at cy 0.7214. The
	   interior is 0.9889 of the art's width and 0.9787 of its height, giving the box below.
	   The design DOES stretch the plate about 13% taller than its native 0.97 aspect — matched here
	   rather than "corrected", because a plate at its native aspect sits visibly short and low and
	   stops meeting the logo.
	   Columns are NOT the design's (0.2569 / 0.4884 / 0.7189): the user asked for them closer and
	   centred, so the row is a symmetric 21.6cqw pitch about the middle of the frame — the design's
	   own row sits 1.2% left of centre. */
	.panel {
		position: absolute;
		top: 72.14cqh;
		transform: translate(-50%, -50%);
		width: 20.05cqw;
		height: 42.61cqh;
	}
	.panel-0 {
		left: 28.4%;
		animation: panel-from-left 650ms linear 1050ms both;
	}
	.panel-1 {
		left: 50%;
		animation: panel-from-bottom 650ms linear 1150ms both;
	}
	.panel-2 {
		left: 71.6%;
		animation: panel-from-right 650ms linear 1250ms both;
	}
	.panel-img {
		position: absolute;
		inset: 0;
		width: 100%;
		height: 100%;
	}
	.panel-body {
		position: absolute;
		inset: 8% 8%;
		display: flex;
		flex-direction: column;
		align-items: center;
		/* space-evenly, not center: the three cards hold wildly different amounts of copy (8 lines,
		   3 blocks, 4 lines) and the design spreads each set across the SAME plate rather than
		   stacking it at a fixed rhythm. `gap` is only a floor under that distribution. */
		justify-content: space-evenly;
		gap: 0.25cqw;
		text-align: center;
		pointer-events: none;
	}

	/* Portrait: single panel centred between logo and floor parts, entering from the bottom. */
	/* 52 -> 56cqh (user pass 2026-08-10): the card crowded the tube above it and left dead space
	   over the floor parts. The dots track it. */
	.panel-m {
		left: 50%;
		top: 56cqh;
		width: 64cqw;
		height: calc(64cqw * 240 / 266);
		animation: panel-from-bottom 650ms linear 1050ms both;
	}
	.panel-m .panel-body {
		gap: 0.8cqw;
	}

	/* ------------------------------------------------------------------ panel typography */

	/* FACES, off the design's own text nodes (9078:18632): Audiowide 400 carries the card headings
	   and the max-win numeral, Poppins the running text under them. Chakra Petch — which this whole
	   block used to be set in — is the HUD's face, not the splash's; it reads narrower and squarer
	   than the design's wide geometric headings, which is what made the splash look wrong next to
	   every other MOTHERSHIP screen.
	   AUDIOWIDE SHIPS 400 ONLY (see static/fonts/web/fonts.css), so the weight is pinned: asking for
	   700 gets a synthesised smear, not a bolder cut. */
	.f-title {
		font-family: 'Audiowide', 'Chakra Petch', sans-serif;
		font-weight: 400;
		font-size: 2.65cqw;
		line-height: 1.12;
		letter-spacing: 0.03em;
		text-transform: uppercase;
		/* pre-LINE, not pre: the design breaks every title over two lines, and the break has to come
		   from the copy (some locales are one long word and must stay on one line, shrunk by
		   fitTitle). fitTitle measures scrollWidth, which on a pre-line block is its widest line, so
		   the two stay compatible. */
		white-space: pre-line;
		filter: drop-shadow(0 0 0.55em rgba(0, 0, 0, 0.55));
	}
	/* Body copy: Poppins Regular 16px in the design (9078:18661 / 18667), which is 1.33cqw of the
	   1200-wide stage. The bold scatter counts inside it are .f-count below. */
	.f-sub {
		font-family: 'Poppins', 'Inter', sans-serif;
		font-weight: 400;
		font-size: 1.32cqw;
		line-height: 1.25;
		color: #ffffff;
		letter-spacing: 0.03em;
		text-shadow: 0 2px 5px rgba(0, 0, 0, 0.6);
		max-width: 100%;
		overflow-wrap: break-word;
	}
	/* The bonus names under each scatter count: Poppins Bold 16px uppercase (9078:18672 / 18675 /
	   18692) — the same face as the line above them, one weight up. */
	.f-key {
		font-family: 'Poppins', 'Inter', sans-serif;
		font-weight: 700;
		font-size: 1.3cqw;
		line-height: 1.15;
		letter-spacing: 0.03em;
		text-transform: uppercase;
		filter: drop-shadow(0 0 0.4em rgba(0, 0, 0, 0.5));
		max-width: 100%;
		overflow-wrap: break-word;
	}
	/* The max-win numeral: Audiowide 400 at 36px (9078:18663) = 3.0cqw. Same face as the headings —
	   it is the one number on this screen and the design sets every big numeral in Audiowide. */
	.f-value {
		font-family: 'Audiowide', 'Chakra Petch', sans-serif;
		font-weight: 400;
		font-size: 3.05cqw;
		line-height: 1;
		letter-spacing: 0.03em;
		filter: drop-shadow(0 0 0.35em rgba(0, 0, 0, 0.5));
	}
	/* Card ink, sampled off design 9078:18632. The 2026-08 splash set its titles as CLIPPED
	   GRADIENTS; this design sets them flat, one colour per card, which is also why the type can
	   carry a text-shadow again — a shadow under `background-clip: text` prints as a smear behind
	   transparent glyphs. */
	.f-green {
		color: #94f051;
	}
	.f-pink {
		color: #f782fe;
	}
	.f-gold {
		color: #fece06;
	}
	/* The scatter count is set BIGGER than the line it sits in — 1.6em, measured off the design. Its
	   line-height is pulled under 1 so the taller glyph does not inflate the line box and push the
	   card's six lines apart. */
	.f-count {
		color: #f782fe;
		font-weight: 700;
		font-size: 1.6em;
		line-height: 0.85;
	}
	/* The POLARITY SHIFTER card is the only one carrying art. Sized off the card, not the stage, so
	   it holds its share of the panel in both layouts. */
	.f-icon {
		width: 40%;
		max-width: 40%;
		filter: drop-shadow(0 0.25em 0.35em rgba(0, 0, 0, 0.45));
	}

	/* Portrait panel type. NOT the design's card-relative percentages: the portrait plate is WIDER
	   than it is tall (266x240) while the landscape one is much taller than wide, so type set at the
	   design's share of the card width overflows the short plate. Sized to fit the tallest card
	   (POLARITY SHIFTER: two title lines + the icon + three body lines) instead. */
	.panel-m .f-title {
		font-size: 7.2cqw;
	}
	.panel-m .f-sub {
		font-size: 3.6cqw;
	}
	.panel-m .f-key {
		font-size: 3.55cqw;
	}
	.panel-m .f-value {
		font-size: 9cqw;
	}
	.panel-m .f-icon {
		width: 30%;
		max-width: 30%;
	}

	/* ------------------------------------------------------------------ floor parts */

	.place {
		position: absolute;
		transform: translate(-50%, -50%);
		pointer-events: none;
	}
	.place img {
		display: block;
		width: 100%;
		filter: drop-shadow(0 0.6cqh 1cqh rgba(0, 0, 0, 0.5));
	}
	/* Positions are the Figma placements converted to stage fractions, not eyeballed: each part's
	   node box (e.g. cable at -69,498 / 280x187) intersected with the trimmed art's own alpha bbox
	   inside its source image, so `left`/`top` land on the VISIBLE centre and `width` is the visible
	   width — the raw art carries a lot of empty margin. */

	/* Panel flights: offscreen → accelerate in (the 0% timing function), skid a touch past the
	   mark with a squash along the motion axis, settle. All keyframes repeat translate(-50%,-50%)
	   because that is what centres a panel on its anchor. */
	@keyframes panel-from-left {
		0% {
			transform: translate(calc(-50% - 90cqw), -50%);
			animation-timing-function: cubic-bezier(0.4, 0, 0.85, 0.55);
		}
		76% {
			transform: translate(-50%, -50%);
			animation-timing-function: ease-out;
		}
		85% {
			transform: translate(calc(-50% + 1cqw), -50%) scale(0.955, 1.035);
			animation-timing-function: ease-in-out;
		}
		100% {
			transform: translate(-50%, -50%) scale(1, 1);
		}
	}
	@keyframes panel-from-right {
		0% {
			transform: translate(calc(-50% + 90cqw), -50%);
			animation-timing-function: cubic-bezier(0.4, 0, 0.85, 0.55);
		}
		76% {
			transform: translate(-50%, -50%);
			animation-timing-function: ease-out;
		}
		85% {
			transform: translate(calc(-50% - 1cqw), -50%) scale(0.955, 1.035);
			animation-timing-function: ease-in-out;
		}
		100% {
			transform: translate(-50%, -50%) scale(1, 1);
		}
	}
	@keyframes panel-from-bottom {
		0% {
			transform: translate(-50%, calc(-50% + 85cqh));
			animation-timing-function: cubic-bezier(0.4, 0, 0.85, 0.55);
		}
		76% {
			transform: translate(-50%, -50%);
			animation-timing-function: ease-out;
		}
		85% {
			transform: translate(-50%, calc(-50% - 1.2cqh)) scale(1.035, 0.955);
			animation-timing-function: ease-in-out;
		}
		100% {
			transform: translate(-50%, -50%) scale(1, 1);
		}
	}

	/* ------------------------------------------------------------------ press label */

	/* Under the panel row, not on it. The panels are centred at 72.14cqh and are 42.61cqh tall, so
	   their bottom edge is at 93.44cqh — the old 92.8% put this line across their lower frame. */
	.press-label {
		position: absolute;
		left: 50%;
		top: 97.2%;
		transform: translate(-50%, -50%);
		margin: 0;
		white-space: nowrap;
		/* The design node for this screen has no press line, so the face comes from the same string on
		   its sibling screen — the free-spins-won board (9276:31989), Audiowide 400 with 0.03em. */
		font-family: 'Audiowide', 'Chakra Petch', sans-serif;
		font-weight: 400;
		font-size: clamp(14px, 1.5cqw, 22px);
		letter-spacing: 0.06em;
		color: #ffffff;
		text-shadow: 0 2px 8px rgba(0, 0, 0, 0.85);
		animation:
			soft-in 350ms ease-out 2150ms both,
			blink 1.6s ease-in-out 2500ms infinite;
	}
	.press-label--m {
		top: 97%;
		font-size: clamp(15px, 4.4cqw, 26px);
	}

	/* Slide indicator dots (portrait) — just below the panel. */
	.dots {
		position: absolute;
		left: 50%;
		top: 78%;
		transform: translateX(-50%);
		display: flex;
		gap: 3cqw;
		pointer-events: none;
	}
	.dot {
		width: 2.2cqw;
		height: 2.2cqw;
		border-radius: 50%;
		background: rgba(255, 255, 255, 0.35);
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.6);
	}
	.dot--on {
		background: #4aa8ff;
	}

	/* ------------------------------------------------------------------ shared keyframes */

	@keyframes soft-in {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}
	@keyframes stage-fade {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}
	/* Every keyframe repeats translate(-50%, -50%) because that is what centres the logo on its
	   anchor point — dropping it from one frame would snap the logo a full half-size sideways. */
	@keyframes logo-drop {
		0% {
			transform: translate(-50%, -50%) translateY(var(--drop-from)) scale(0.94, 1.09);
			animation-timing-function: cubic-bezier(0.55, 0, 0.95, 0.42);
		}
		46% {
			transform: translate(-50%, -50%) scale(0.94, 1.09);
			animation-timing-function: cubic-bezier(0.18, 0.7, 0.35, 1);
		}
		57% {
			transform: translate(-50%, -50%) translateY(1.5%) scale(1.1, 0.87);
			animation-timing-function: ease-out;
		}
		72% {
			transform: translate(-50%, -50%) translateY(-3.5%) scale(0.99, 1.02);
			animation-timing-function: ease-in;
		}
		86% {
			transform: translate(-50%, -50%) translateY(0.6%) scale(1.015, 0.985);
		}
		100% {
			transform: translate(-50%, -50%) scale(1, 1);
		}
	}

	/* Both shakes run on `.shake`, which fills the stage, so the offsets are percentages of the
	   stage size around a resting 0. `stage-jolt` = logo touchdown; `stage-slam` = the magnet
	   landing (the big hit). */
	@keyframes stage-jolt {
		0% {
			transform: translate(0, 0);
		}
		22% {
			transform: translate(0, 0.7%);
		}
		48% {
			transform: translate(-0.25%, -0.35%);
		}
		74% {
			transform: translate(0.12%, 0.12%);
		}
		100% {
			transform: translate(0, 0);
		}
	}
	@keyframes stage-slam {
		0% {
			transform: translate(0, 0);
		}
		18% {
			transform: translate(-0.4%, 1.1%);
		}
		40% {
			transform: translate(0.4%, -0.7%);
		}
		62% {
			transform: translate(-0.25%, 0.4%);
		}
		82% {
			transform: translate(0.1%, -0.2%);
		}
		100% {
			transform: translate(0, 0);
		}
	}

	@keyframes blink {
		0%,
		100% {
			opacity: 1;
		}
		50% {
			opacity: 0.55;
		}
	}

	@media (prefers-reduced-motion: reduce) {
		.stage,
		.stage *,
		.press-label {
			animation-duration: 0.01ms !important;
			animation-delay: 0ms !important;
			animation-iteration-count: 1 !important;
		}
	}
	@keyframes body-turn {
		from {
			transform: rotate(0deg);
		}
		to {
			transform: rotate(360deg);
		}
	}

	@keyframes body-turn-rev {
		from {
			transform: rotate(0deg);
		}
		to {
			transform: rotate(-360deg);
		}
	}

	/* A very slight hover, in container units so it scales with the stage. The two bodies use
	   different periods and paths, so they drift independently rather than in step. */
	@keyframes moon-float {
		0%,
		100% {
			transform: translate(-50%, -50%);
		}
		33% {
			transform: translate(calc(-50% + 0.55cqw), calc(-50% - 0.75cqh));
		}
		66% {
			transform: translate(calc(-50% - 0.4cqw), calc(-50% + 0.6cqh));
		}
	}

	@keyframes planet-float {
		0%,
		100% {
			transform: translate(-50%, -50%);
		}
		50% {
			transform: translate(calc(-50% - 0.7cqw), calc(-50% + 1cqh));
		}
	}

	/* Starts and ends fully off-frame so a cloud is never seen appearing or vanishing. */
	@keyframes cloud-drift {
		from {
			transform: translateX(-120%);
		}
		to {
			transform: translateX(calc(100vw + 120%));
		}
	}
</style>
