<script lang="ts">
	import { Container, Graphics, Sprite } from 'pixi-svelte';

	// The WILD cell, assembled live so the eye can blink, the bolt can pop and the plaque can light.
	//
	//   idle — the eye blinks on its own irregular schedule, the bolt breathes, the studs twinkle.
	//   win  — the bolt pops hard and flashes, the WILD letters light, the studs chase.
	//
	// scripts/build-wild-art.py cuts the layers and emits every number below. Two things about that
	// script are worth knowing before touching a constant here:
	//
	//   * Every placement is measured in the DESIGNER'S REFERENCE, not in the parts. The five source
	//     rasters do not share a frame, so their own coordinates say nothing about each other.
	//   * The N and S caps are placed separately from the arch, because the design seats them 27
	//     reference-px higher than the magnet raster does. That is why the base texture is not just
	//     magnet_ns.png rescaled.
	//
	// One rAF per wild cell, drawing imperatively into a captured Graphics — same pattern as
	// <SymbolWinFx>, <ScatterSymbol>, <BatterySymbol>, <CompassSymbol>, <MagnetSymbol> and
	// <EmDeviceSymbol>.

	type Props = {
		/** Base texture key — the magnet with its caps (desktop / mobile / landscape variant). */
		assetKey: string;
		x: number;
		y: number;
		width: number;
		height: number;
		alpha?: number;
		zIndex?: number;
		/** 0..1 — de-phases every cell so two wilds never blink or pop in lockstep. */
		phase?: number;
		/** Win choreography: hard bolt pop, lit letters, chasing studs. */
		winning?: boolean;
		/**
		 * When > 1 the bolt is replaced by the multiplier disc, exactly as the design does it. The
		 * disc takes the bolt's own pop and flash — "the same animation as the normal wild" — so
		 * there is one choreography here, not two.
		 */
		multiplier?: number;
	};
	const props: Props = $props();

	// Fractions of the symbol BOX, offsets from centre. Generated by scripts/build-wild-art.py.
	const PLAQUE = { dx: 0.0, dy: 0.3639, w: 0.7614, h: 0.2721 };
	const BLOB = { dx: 0.0115, dy: -0.3359, w: 0.2061, h: 0.3283 };
	const EYE = { dx: 0.0078, dy: -0.3853, w: 0.1147, h: 0.1424 };
	const BOLT = { dx: -0.0036, dy: -0.0045, w: 0.1426, h: 0.2652 };
	/** The multiplier disc and its number, both from scripts/build-wild-mult-art.py. */
	const DISC = { dx: -0.0015, dy: 0.0746, w: 0.3429, h: 0.3686 };
	const NUM = { dx: -0.0015, dy: 0.0926, w: 0.2683, h: 0.1742 };
	/** Multipliers the game can roll, and the texture key for each. */
	const MULT_KEYS: Record<number, string> = {
		2: 'wildMultX2',
		3: 'wildMultX3',
		4: 'wildMultX4',
		5: 'wildMultX5',
		7: 'wildMultX7',
		9: 'wildMultX9',
		10: 'wildMultX10',
	};
	/** The plaque's four green studs — the "wild lights". */
	const STUDS = [
		{ dx: -0.3147, dy: 0.3233, r: 0.0227 },
		{ dx: -0.2816, dy: 0.4059, r: 0.0199 },
		{ dx: 0.284, dy: 0.4059, r: 0.0197 },
		{ dx: 0.3158, dy: 0.3233, r: 0.0225 },
	];

	const STUD_GLOW = 0xc8ff5a;

	/** Bolt: pop period in seconds, and how far it scales at the two extremes. */
	const POP_P = 0.46;
	const POP_IDLE = 0.035;
	const POP_WIN = 0.3;
	/** Eye blink: one opportunity per slot, taken this often, lasting this long. */
	const BLINK_SLOT = 3.4;
	const BLINK_CHANCE = 0.75;
	const BLINK_DUR = 0.14;
	/** How much faster the eye blinks on a win. */
	const BLINK_WIN_RATE = 2.6;
	/** Stud chase period, and the fraction of it a stud is lit for. */
	const STUD_P = 0.44;
	const STUD_DUTY = 0.5;

	// NB: draw helpers work in CONTAINER-RELATIVE coordinates — the <Container> already carries
	// (props.x, props.y).
	type G = {
		destroyed: boolean;
		clear: () => void;
		circle: (x: number, y: number, r: number) => unknown;
		fill: (s: object) => void;
	};
	let frontG = $state<G | null>(null);

	let boltScale = $state(1);
	let boltFlash = $state(0);
	let eyeOpen = $state(1);
	let wordLight = $state(0);

	const W = $derived(props.width);
	const H = $derived(props.height);
	const P = $derived(props.phase ?? 0);
	/**
	 * Snapped to the nearest multiplier that has a texture, the same way getSpriteKeyByName does it,
	 * so a value the math produces but the art does not cover renders the closest number rather than
	 * nothing at all.
	 */
	const multKey = $derived.by(() => {
		const m = props.multiplier ?? 1;
		if (m <= 1) return null;
		const levels = Object.keys(MULT_KEYS).map(Number);
		const snapped = levels.reduce((a, b) => (Math.abs(b - m) < Math.abs(a - m) ? b : a));
		return MULT_KEYS[snapped];
	});

	/** Deterministic 0..1 from an integer — "random" that is stable per cell and per blink. */
	const hash = (n: number) => ((((n * 2654435761) % 1000) + 1000) % 1000) / 1000;

	$effect(() => {
		const t0 = performance.now();
		let raf = 0;

		const tick = () => {
			raf = requestAnimationFrame(tick);
			const t = (performance.now() - t0) / 1000;
			const win = props.winning === true;

			// --- the bolt -------------------------------------------------------------------
			// One asymmetric pop per period: a fast punch out and a slower settle back, so it
			// reads as a discharge rather than as a sine wave. Idle keeps the same shape at a
			// tenth of the depth, which is why there is one curve here and not two.
			const u = (t / POP_P + P) % 1;
			const punch = u < 0.28 ? u / 0.28 : 1 - (u - 0.28) / 0.72;
			const eased = Math.sin(punch * Math.PI * 0.5) ** 2;
			boltScale = 1 + (win ? POP_WIN : POP_IDLE) * eased;
			boltFlash = win ? 0.55 * eased : 0;

			// --- the eye --------------------------------------------------------------------
			// One blink opportunity per slot, at a random moment inside it, taken most of the
			// time, so the gaps are irregular. A fixed gap reads as a metronome.
			const slotLen = BLINK_SLOT / (win ? BLINK_WIN_RATE : 1);
			const bt = t + P * slotLen * 3;
			const slot = Math.floor(bt / slotLen);
			const seed = slot * 48611 + Math.round(P * 997) * 7919;
			eyeOpen = 1;
			if (hash(seed) < BLINK_CHANCE) {
				const start = hash(seed + 15733) * (slotLen - BLINK_DUR);
				const bu = (bt - slot * slotLen - start) / BLINK_DUR;
				if (bu >= 0 && bu <= 1) eyeOpen = Math.max(0.05, Math.abs(Math.cos(bu * Math.PI)));
			}

			// --- the letters ----------------------------------------------------------------
			// The word is an additive GHOST of the plaque's own pink pixels, so this only ever
			// adds light to the letters — it cannot wash the purple bar out with them.
			wordLight = win ? 0.22 + 0.42 * (0.5 + 0.5 * Math.sin(t * 7 + P * 6.28)) : 0;

			if (frontG?.destroyed) frontG = null;
			if (frontG) {
				frontG.clear();
				for (let i = 0; i < STUDS.length; i++) {
					const s = STUDS[i];
					// Winning: a chase around the four studs. Idle: a slow, shallow twinkle, so
					// the wild is never completely still on the board.
					let lit: number;
					if (win) {
						const su = (t / STUD_P + P + i / STUDS.length) % 1;
						lit = su < STUD_DUTY ? 1 - su / STUD_DUTY : 0;
					} else {
						lit = 0.22 * (0.5 + 0.5 * Math.sin(t * 1.6 + i * 1.7 + P * 6.28));
					}
					if (lit <= 0.001) continue;
					const lx = s.dx * W;
					const ly = s.dy * H;
					const lr = Math.max(1, s.r * W);
					// Halo-weighted. STUD_GLOW added at full strength over studs that are already
					// chartreuse clips red and green together and they go WHITE — they stop
					// reading as green lights exactly when they are brightest.
					for (let k = 3; k >= 1; k--) {
						frontG.circle(lx, ly, lr * (1 + k * 0.85));
						frontG.fill({ color: STUD_GLOW, alpha: (0.14 * lit) / k });
					}
					frontG.circle(lx, ly, lr);
					frontG.fill({ color: STUD_GLOW, alpha: 0.42 * lit });
				}
			}
		};
		raf = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(raf);
	});
</script>

<Container x={props.x} y={props.y} alpha={props.alpha ?? 1} zIndex={props.zIndex}>
	<!-- The horseshoe with its N and S caps already seated. -->
	<Sprite key={props.assetKey} anchor={0.5} width={W} height={H} />
	<!-- The magnet's gap holds EITHER the bolt or the multiplier disc — the design swaps one for the
	     other rather than stacking them — and whichever is there takes the same pop. -->
	{#if multKey}
		<Sprite
			key="wildDisc"
			anchor={0.5}
			x={DISC.dx * W}
			y={DISC.dy * H}
			width={DISC.w * W * boltScale}
			height={DISC.h * H * boltScale}
		/>
		<Sprite
			key={multKey}
			anchor={0.5}
			x={NUM.dx * W}
			y={NUM.dy * H}
			width={NUM.w * W * boltScale}
			height={NUM.h * H * boltScale}
		/>
		<Sprite
			key="wildDisc"
			blendMode="add"
			alpha={boltFlash}
			anchor={0.5}
			x={DISC.dx * W}
			y={DISC.dy * H}
			width={DISC.w * W * boltScale}
			height={DISC.h * H * boltScale}
		/>
	{:else}
		<!-- The bolt sits in the magnet's gap, so it can grow without touching either limb. -->
		<Sprite
			key="wildBolt"
			anchor={0.5}
			x={BOLT.dx * W}
			y={BOLT.dy * H}
			width={BOLT.w * W * boltScale}
			height={BOLT.h * H * boltScale}
		/>
		<!-- An additive GHOST of the bolt, kept mounted at alpha 0 rather than toggled with {#if}:
		     a tint can only scale a texture's channels DOWN, so it can darken the bolt but never
		     light it. Mounting and unmounting per pop would churn a texture twice a second. -->
		<Sprite
			key="wildBolt"
			blendMode="add"
			alpha={boltFlash}
			anchor={0.5}
			x={BOLT.dx * W}
			y={BOLT.dy * H}
			width={BOLT.w * W * boltScale}
			height={BOLT.h * H * boltScale}
		/>
	{/if}
	<!-- The plaque covers the bottom of both caps; that overlap is in the design, not an accident. -->
	<Sprite
		key="wildPlaque"
		anchor={0.5}
		x={PLAQUE.dx * W}
		y={PLAQUE.dy * H}
		width={PLAQUE.w * W}
		height={PLAQUE.h * H}
	/>
	<!-- The letters only: the plaque's own pixels masked to the pink, drawn at the plaque's exact
	     placement so the glow lands on the glyphs and nowhere else. -->
	<Sprite
		key="wildWord"
		blendMode="add"
		alpha={wordLight}
		anchor={0.5}
		x={PLAQUE.dx * W}
		y={PLAQUE.dy * H}
		width={PLAQUE.w * W}
		height={PLAQUE.h * H}
	/>
	<Sprite
		key="wildBlob"
		anchor={0.5}
		x={BLOB.dx * W}
		y={BLOB.dy * H}
		width={BLOB.w * W}
		height={BLOB.h * H}
	/>
	<!-- The eye closes by collapsing its own height against the blob behind it. -->
	<Sprite
		key="wildEye"
		anchor={0.5}
		x={EYE.dx * W}
		y={EYE.dy * H}
		width={EYE.w * W}
		height={EYE.h * H * eyeOpen}
	/>
	<Graphics blendMode="add" draw={(gr) => (frontG = gr as unknown as G)} />
</Container>
