const assets = {
	// The MOTHERSHIP room (Figma 9032:23054). All six are generated by scripts/build-room-art.py
	// from one landscape painting: the portrait pair is rebuilt (the source cannot be cropped to
	// 0.5625) and the bonus pair is the same room under a coloured lamp — magenta for the freegame,
	// green for the superspin. Unlike the blue-lab set these replaced, nothing is blurred or
	// pre-dimmed; the board carries its own opaque plate now.
	bgBase: {
		type: 'sprite',
		src: './assets/components/backgrounds/bg_base.webp?v=20260901b'
	},
	bgBonus: {
		type: 'sprite',
		src: './assets/components/backgrounds/bg_bonus.webp?v=20260901b'
	},
	bgSuper: {
		type: 'sprite',
		src: './assets/components/backgrounds/bg_super.webp?v=20260901b'
	},
	bgMobileBase: {
		type: 'sprite',
		src: './assets/components/backgrounds/bg_mobile_base.webp?v=20260901b'
	},
	bgMobileBonus: {
		type: 'sprite',
		src: './assets/components/backgrounds/bg_mobile_bonus.webp?v=20260901b'
	},
	bgMobileSuper: {
		type: 'sprite',
		src: './assets/components/backgrounds/bg_mobile_super.webp?v=20260901b'
	},
	// Small-win amount plate (design's own art, built by scripts/build-ui-art.py). The plate this
	// replaced was drawn in WinAmountPlaque itself — a dark bed with a gold hairline.
	winPlaque: {
		type: 'sprite',
		src: './assets/components/ui/win_plaque.webp?v=20260901c'
	},
	// The ship hanging in the room's right-hand window, as the designer's own loose parts (built by
	// scripts/build-ufo-art.py) so hull and antenna can be animated apart. Its tractor beam is no
	// longer art at all — Background.svelte draws it.
	ufoHull: {
		type: 'sprite',
		src: './assets/components/ui/ufo_hull.webp?v=20260901d'
	},
	ufoAntenna: {
		type: 'sprite',
		src: './assets/components/ui/ufo_antenna.webp?v=20260901d'
	},
	smallPadMobile: {
		type: 'sprite',
		src: './assets/components/ui/small_pad_mobile.webp?v=20260709'
	},
	// Backdrop for BOTH congratulations screens (Version2, Figma 7022-6844 / 7069-9311). Cropped
	// straight out of the artist's source PNG, which already carries real alpha — no keying, and
	// no purple arcs: the design mock composites those from a separate layer and the user asked for
	// the clean frame. 2048x1162.
	fsWonFrame: {
		type: 'sprite',
		src: './assets/components/ui/fs_won_frame.webp?v=20260807b'
	},
	// Per-cell boxes: a stationary 7x7 grid of these sits behind the rolling symbols. Winning cells
	// swap to the win-state box.
	symbolPad: {
		type: 'sprite',
		src: './assets/components/frames/symbol_pad.webp?v=20260625'
	},
	counterFrame: {
		type: 'sprite',
		src: './assets/components/ui/confirm_frame.webp?v=20260625'
	},
	magneticLogo: {
		type: 'sprite',
		src: './assets/components/splash/logo_plate.webp?v=20260901b'
	},
	pressPlayLogo: {
		type: 'sprite',
		src: './assets/components/ui/press_play_logo.webp?v=20260709'
	},
	// Win-state flipbook sheets are gone: winning cells now play the procedural <SymbolWinFx>
	// choreography over the hi-res static win art. The 9–10 frame sheets looped at ~14fps with no
	// real object motion — the Stake review's "poor animations".
	aTile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/nut.webp?v=20260902' },
	// The magnet's loose layers: the antennae shake, the face breathes, and the win state arcs
	// electricity between the caps -- see MagnetSymbol.svelte and scripts/build-magnet-art.py.
	magnetFace: { type: 'sprite', src: './assets/components/symbols/magnetic/low/magnet_face.webp?v=20260902' },
	magnetAntennaL: { type: 'sprite', src: './assets/components/symbols/magnetic/low/magnet_antenna_l.webp?v=20260902' },
	magnetAntennaR: { type: 'sprite', src: './assets/components/symbols/magnetic/low/magnet_antenna_r.webp?v=20260902' },
	magnetHandL: { type: 'sprite', src: './assets/components/symbols/magnetic/low/magnet_hand_l.webp?v=20260902' },
	magnetHandR: { type: 'sprite', src: './assets/components/symbols/magnetic/low/magnet_hand_r.webp?v=20260902' },
	aWinTile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/nut.webp?v=20260902' },
	aTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/nut_mobile.webp?v=20260902' },
	aWinTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/nut_mobile.webp?v=20260902' },
	kTile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/coil.webp?v=20260902' },
	kWinTile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/coil.webp?v=20260902' },
	kTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/coil_mobile.webp?v=20260902' },
	kWinTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/coil_mobile.webp?v=20260902' },
	// The astronaut's HEAD and its two eyes, loose so <CoilSymbol> can zoom and shake the head and
	// let the eyes look around inside it. The helmet stays baked into the base, and the head texture
	// has its eye sockets painted over in the face's own green so a drifting eye never exposes a
	// hole. See scripts/build-coil-art.py.
	coilHead: { type: 'sprite', src: './assets/components/symbols/magnetic/low/coil_head.webp?v=20260902' },
	coilEyeL: { type: 'sprite', src: './assets/components/symbols/magnetic/low/coil_eye_l.webp?v=20260902' },
	coilEyeR: { type: 'sprite', src: './assets/components/symbols/magnetic/low/coil_eye_r.webp?v=20260902' },
	// The alien on the circuit chip -- its face plate, its mouth, one eye (used twice) -- plus the two
	// slime blobs, loose so <CircuitSymbol> can ooze the slime, blink and grin. The mouth is cut OFF
	// the face plate and its hole filled with the plate's own green, because the art ships only a
	// neutral mouth and the win has to grow it into a grin. See scripts/build-circuit-art.py.
	circuitFace: { type: 'sprite', src: './assets/components/symbols/magnetic/low/circuit_face.webp?v=20260902' },
	circuitMouth: { type: 'sprite', src: './assets/components/symbols/magnetic/low/circuit_mouth.webp?v=20260902' },
	circuitEye: { type: 'sprite', src: './assets/components/symbols/magnetic/low/circuit_eye.webp?v=20260902' },
	circuitSlimeA: { type: 'sprite', src: './assets/components/symbols/magnetic/low/circuit_slime_a.webp?v=20260902' },
	circuitSlimeB: { type: 'sprite', src: './assets/components/symbols/magnetic/low/circuit_slime_b.webp?v=20260902' },
	qTile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/energy_screw.webp?v=20260902' },
	qWinTile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/energy_screw.webp?v=20260902' },
	qTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/energy_screw_mobile.webp?v=20260902' },
	qWinTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/energy_screw_mobile.webp?v=20260902' },
	wildTile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild.webp?v=20260902' },
	wildWinTile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild.webp?v=20260902' },
	wildTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_mobile.webp?v=20260902' },
	wildWinTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_mobile.webp?v=20260902' },
	wild2xTile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x2.webp?v=20260806' },
	wild3xTile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x3.webp?v=20260806' },
	wild4xTile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x4.webp?v=20260806' },
	wild5xTile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x5.webp?v=20260806' },
	wild7xTile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x7.webp?v=20260806' },
	wild9xTile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x9.webp?v=20260806' },
	wild10xTile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x10.webp?v=20260806' },
	wild2xTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x2_mobile.webp?v=20260806' },
	wild3xTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x3_mobile.webp?v=20260806' },
	wild4xTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x4_mobile.webp?v=20260806' },
	wild5xTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x5_mobile.webp?v=20260806' },
	wild7xTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x7_mobile.webp?v=20260806' },
	wild9xTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x9_mobile.webp?v=20260806' },
	wild10xTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x10_mobile.webp?v=20260806' },
	// Radial electric burst played BEHIND every stacked (locked) symbol. 10 independent bursts
	// rather than a rendered animation, so the cycle is a crackle, not motion — order carries no
	// meaning. Regenerate with scripts/build-stack-zap-sheet.py <src-dir>.
	scatterCustom: { type: 'sprite', src: './assets/components/symbols/magnetic/special/scatter.webp?v=20260902bb' },
	scatterWin: { type: 'sprite', src: './assets/components/symbols/magnetic/special/scatter.webp?v=20260902bb' },
	scatterCustomMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/scatter_mobile.webp?v=20260902bb' },
	scatterWinMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/special/scatter_mobile.webp?v=20260902bb' },
	// The capsule's loose layers. scatter.webp is the machine with an EMPTY tube; these two ride on
	// top so the alien can jump and the eye can blink (see ScatterSymbol.svelte, and
	// scripts/build-scatter-art.py for how they were cut out of the flat Figma lockup).
	scatterAlien: { type: 'sprite', src: './assets/components/symbols/magnetic/special/scatter_alien.webp?v=20260902bb' },
	scatterEye: { type: 'sprite', src: './assets/components/symbols/magnetic/special/scatter_eye.webp?v=20260902bb' },
	// The lid, re-drawn IN FRONT of the alien so it can hop up behind it instead of over it.
	scatterDome: { type: 'sprite', src: './assets/components/symbols/magnetic/special/scatter_dome.webp?v=20260902bb' },
	// The word SCATTER, cut off the plate so the win state can zoom it. A copy scaled on top of a
	// baked-in original just shows the original poking out -- see scripts/build-scatter-art.py,
	// which also inpaints the plaque it leaves behind.
	scatterWord: { type: 'sprite', src: './assets/components/symbols/magnetic/special/scatter_word.webp?v=20260902b' },
	foxTile:      { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass.webp?v=20260902' },
	// Compass loose layers: the needle turns, the alien zooms and the poles pop. The bezel and its
	// chevrons stay baked in compass.webp -- see scripts/build-compass-art.py, which also owns the
	// LAYOUT, since Figma has no composed lockup for this symbol.
	// The MOTHERSHIP compass has no needle -- see CompassSymbol.svelte. The alien arrives as a face
	// plus two loose antennae so they can sway, cut by scripts/build-compass-art.py.
	compassFace: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass_face.webp?v=20260902' },
	compassAntennaL: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass_antenna_l.webp?v=20260902' },
	compassAntennaR: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass_antenna_r.webp?v=20260902' },
	compassEye: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass_eye.webp?v=20260902' },
	compassN: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass_n.webp?v=20260902' },
	compassS: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass_s.webp?v=20260902' },
	// The electromagnetic device's moving layers. Loose so the antennae can lean on their own
	// stalks and the eye can flash when the cell discharges -- see EmDeviceSymbol.svelte and
	// scripts/build-emdevice-art.py.
	emAntennaL: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/em_antenna_l.webp?v=20260902' },
	emAntennaR: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/em_antenna_r.webp?v=20260902' },
	emLens: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/em_lens.webp?v=20260902' },
	// The wild's moving layers. wild.webp is the magnet WITH its N/S caps re-seated where the
	// design puts them -- see WildSymbol.svelte and scripts/build-wild-art.py. wildWord is the
	// plaque masked to its pink letters, used only as an additive glow.
	wildPlaque: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_plaque.webp?v=20260902' },
	wildWord: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_word.webp?v=20260902' },
	wildBlob: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_blob.webp?v=20260902' },
	wildEye: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_eye.webp?v=20260902' },
	wildBolt: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_bolt.webp?v=20260902' },
	// The multiplier wild is the SAME lockup with the bolt swapped for a disc -- both references
	// line up to within 1px -- so it reuses every wild layer above and only adds these.
	// scripts/build-wild-mult-art.py. The numbers are set in Chakra Petch: the design's rounded
	// display face was never delivered, and Chakra Petch is what the rest of the redesigned UI
	// already uses.
	wildDisc: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_disc.webp?v=20260902' },
	wildMultX2: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_mult_x2.webp?v=20260902' },
	wildMultX3: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_mult_x3.webp?v=20260902' },
	wildMultX4: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_mult_x4.webp?v=20260902' },
	wildMultX5: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_mult_x5.webp?v=20260902' },
	wildMultX7: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_mult_x7.webp?v=20260902' },
	wildMultX9: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_mult_x9.webp?v=20260902' },
	wildMultX10: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_mult_x10.webp?v=20260902' },
	wolfTile:     { type: 'sprite', src: './assets/components/symbols/magnetic/premium/lightning.webp?v=20260902' },
	// The lightning badge's BOLT, loose so <LightningSymbol> can pop and blink it. The badge's
	// four green corner balls stay baked into the base -- they only ever glow, and a Graphics
	// halo over the baked art does that without a fifth texture.
	lightningBolt: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/lightning_bolt.webp?v=20260902' },
	bearTile:     { type: 'sprite', src: './assets/components/symbols/magnetic/premium/portal.webp?v=20260902' },
	// The portal's galaxy CORE, its alien head and the alien's two antennae, loose so <PortalSymbol>
	// can spin the core and flap the antennae. The ring and the four pink pins stay baked into the
	// base, and the base has the ring's hole punched out of it -- the core is drawn behind it and
	// shows through. See scripts/build-portal-art.py.
	portalCore: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/portal_core.webp?v=20260902' },
	portalHead: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/portal_head.webp?v=20260902' },
	portalAntennaL: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/portal_antenna_l.webp?v=20260902' },
	portalAntennaR: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/portal_antenna_r.webp?v=20260902' },
	rabbitTile:   { type: 'sprite', src: './assets/components/symbols/magnetic/premium/electromagnetic_device.webp?v=20260902' },
	magnetTile:   { type: 'sprite', src: './assets/components/ui/magnet_win.webp?v=20260709' },
	squirrelTile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/battery.webp?v=20260902' },
	squirrelTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/battery_mobile.webp?v=20260902' },
	// The battery character that sits inside the housing's panel and pops on a win. Loose so the
	// balloons can drift behind it -- see BatterySymbol.svelte and scripts/build-battery-art.py.
	batteryCell: { type: 'sprite', src: './assets/components/symbols/magnetic/low/battery_cell.webp?v=20260902' },
	// The battery's WIN variant on the mobile sheet. It was the one hole in the base/Mobile/Land
	// matrix: utils.ts SYMBOL_WIN_ASSET_MOBILE maps L1 -> 'squirrelWinTileMobile', so in portrait a
	// winning battery resolved to an undefined key and the cell simply drew nothing.
	squirrelWinTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/battery_mobile.webp?v=20260902' },
	// Premium mobile (portrait) symbol art.
	foxTileMobile:       { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass_mobile.webp?v=20260902' },
	foxWinTileMobile:    { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass_mobile.webp?v=20260902' },
	wolfTileMobile:      { type: 'sprite', src: './assets/components/symbols/magnetic/premium/lightning_mobile.webp?v=20260902' },
	wolfWinTileMobile:   { type: 'sprite', src: './assets/components/symbols/magnetic/premium/lightning_mobile.webp?v=20260902' },
	bearTileMobile:      { type: 'sprite', src: './assets/components/symbols/magnetic/premium/portal_mobile.webp?v=20260902' },
	bearWinTileMobile:   { type: 'sprite', src: './assets/components/symbols/magnetic/premium/portal_mobile.webp?v=20260902' },
	rabbitTileMobile:    { type: 'sprite', src: './assets/components/symbols/magnetic/premium/electromagnetic_device_mobile.webp?v=20260902' },
	rabbitWinTileMobile: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/electromagnetic_device_mobile.webp?v=20260902' },
	// Landscape (mobile horizontal) symbol art.
	foxTileLand:       { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass.webp?v=20260902' },
	foxWinTileLand:    { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass.webp?v=20260902' },
	wolfTileLand:      { type: 'sprite', src: './assets/components/symbols/magnetic/premium/lightning.webp?v=20260902' },
	wolfWinTileLand:   { type: 'sprite', src: './assets/components/symbols/magnetic/premium/lightning.webp?v=20260902' },
	bearTileLand:      { type: 'sprite', src: './assets/components/symbols/magnetic/premium/portal.webp?v=20260902' },
	bearWinTileLand:   { type: 'sprite', src: './assets/components/symbols/magnetic/premium/portal.webp?v=20260902' },
	rabbitTileLand:    { type: 'sprite', src: './assets/components/symbols/magnetic/premium/electromagnetic_device.webp?v=20260902' },
	rabbitWinTileLand: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/electromagnetic_device.webp?v=20260902' },
	squirrelTileLand:    { type: 'sprite', src: './assets/components/symbols/magnetic/low/battery.webp?v=20260902' },
	squirrelWinTileLand: { type: 'sprite', src: './assets/components/symbols/magnetic/low/battery.webp?v=20260902' },
	aTileLand:    { type: 'sprite', src: './assets/components/symbols/magnetic/low/nut.webp?v=20260902' },
	aWinTileLand: { type: 'sprite', src: './assets/components/symbols/magnetic/low/nut.webp?v=20260902' },
	kTileLand:    { type: 'sprite', src: './assets/components/symbols/magnetic/low/coil.webp?v=20260902' },
	kWinTileLand: { type: 'sprite', src: './assets/components/symbols/magnetic/low/coil.webp?v=20260902' },
	qTileLand:    { type: 'sprite', src: './assets/components/symbols/magnetic/low/energy_screw.webp?v=20260902' },
	qWinTileLand: { type: 'sprite', src: './assets/components/symbols/magnetic/low/energy_screw.webp?v=20260902' },
	wildTileLand:    { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild.webp?v=20260902' },
	scatterTileLand: { type: 'sprite', src: './assets/components/symbols/magnetic/special/scatter.webp?v=20260902bb' },
	wild2xTileLand:  { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x2.webp?v=20260806' },
	wild3xTileLand:  { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x3.webp?v=20260806' },
	wild4xTileLand:  { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x4.webp?v=20260806' },
	wild5xTileLand:  { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x5.webp?v=20260806' },
	wild7xTileLand:  { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x7.webp?v=20260806' },
	wild9xTileLand:  { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x9.webp?v=20260806' },
	wild10xTileLand: { type: 'sprite', src: './assets/components/symbols/magnetic/special/wild_x10.webp?v=20260806' },
	foxWinTile: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/compass.webp?v=20260902' },
	wolfWinTile: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/lightning.webp?v=20260902' },
	bearWinTile: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/portal.webp?v=20260902' },
	rabbitWinTile: { type: 'sprite', src: './assets/components/symbols/magnetic/premium/electromagnetic_device.webp?v=20260902' },
	magnetWinTile: { type: 'sprite', src: './assets/components/ui/magnet_win.webp?v=20260709' },
	squirrelWinTile: { type: 'sprite', src: './assets/components/symbols/magnetic/low/battery.webp?v=20260902' },
	// Win boards — preloaded so board escalation during count-up doesn't stall
	// Version2 SWEET WIN sign (Figma 7022:7751) — ships as parts; WinSign.svelte assembles them
	// (pillars fly in from the sides, magnet drops, title rises) with landing impacts.
	winSignPlate:     { type: 'sprite', src: './assets/components/win_boards/sign_plate.webp?v=20260812' },
	winSignPillarL:   { type: 'sprite', src: './assets/components/win_boards/sign_pillar_left.webp?v=20260812' },
	winSignPillarR:   { type: 'sprite', src: './assets/components/win_boards/sign_pillar_right.webp?v=20260812' },
	winSignMagnet:    { type: 'sprite', src: './assets/components/win_boards/sign_magnet.webp?v=20260812' },
	winSignTextSweet: { type: 'sprite', src: './assets/components/win_boards/sign_text_sweet.webp?v=20260812' },
	// EPIC WIN parts (Figma 7022:8274) — its own plate/pillar/magnet art (looping pipes).
	winSignEpicPlate:   { type: 'sprite', src: './assets/components/win_boards/sign_epic_plate.webp?v=20260812' },
	winSignEpicPillarL: { type: 'sprite', src: './assets/components/win_boards/sign_epic_pillar_left.webp?v=20260812' },
	winSignEpicPillarR: { type: 'sprite', src: './assets/components/win_boards/sign_epic_pillar_right.webp?v=20260812' },
	winSignEpicMagnet:  { type: 'sprite', src: './assets/components/win_boards/sign_epic_magnet.webp?v=20260812' },
	winSignTextEpic:    { type: 'sprite', src: './assets/components/win_boards/sign_text_epic.webp?v=20260812' },
	// MYTHIC WIN parts (Figma 4007:1743) — neon-tube pillars, two-line magenta neon title.
	winSignMythicPlate:   { type: 'sprite', src: './assets/components/win_boards/sign_mythic_plate.webp?v=20260812' },
	winSignMythicPillarL: { type: 'sprite', src: './assets/components/win_boards/sign_mythic_pillar_left.webp?v=20260812' },
	winSignMythicPillarR: { type: 'sprite', src: './assets/components/win_boards/sign_mythic_pillar_right.webp?v=20260812' },
	winSignMythicMagnet:  { type: 'sprite', src: './assets/components/win_boards/sign_mythic_magnet.webp?v=20260812' },
	winSignTextMythic:    { type: 'sprite', src: './assets/components/win_boards/sign_text_mythic.webp?v=20260812' },
	// LEGENDARY WIN parts (Figma 7022:8095) — twin-capsule pillars, gold flame title.
	winSignLegendPlate:   { type: 'sprite', src: './assets/components/win_boards/sign_legend_plate.webp?v=20260810' },
	winSignLegendPillarL: { type: 'sprite', src: './assets/components/win_boards/sign_legend_pillar_left.webp?v=20260810' },
	winSignLegendPillarR: { type: 'sprite', src: './assets/components/win_boards/sign_legend_pillar_right.webp?v=20260810' },
	winSignLegendMagnet:  { type: 'sprite', src: './assets/components/win_boards/sign_legend_magnet.webp?v=20260810' },
	winSignTextLegend:    { type: 'sprite', src: './assets/components/win_boards/sign_text_legend.webp?v=20260810' },
	// WILD WIN parts (Figma 7022:7925) — green title; pillars reuse the sweet strip assets.
	winSignWildPlate:  { type: 'sprite', src: './assets/components/win_boards/sign_wild_plate.webp?v=20260812' },
	winSignWildPillarL: { type: 'sprite', src: './assets/components/win_boards/sign_wild_pillar_left.webp?v=20260812' },
	winSignWildPillarR: { type: 'sprite', src: './assets/components/win_boards/sign_wild_pillar_right.webp?v=20260812' },
	winSignWildMagnet: { type: 'sprite', src: './assets/components/win_boards/sign_wild_magnet.webp?v=20260812' },
	winSignTextWild:   { type: 'sprite', src: './assets/components/win_boards/sign_text_wild.webp?v=20260812' },
	// MAX WIN parts (Figma 7103:5231) — hazard-base pillars with a cyan neon column and a purple
	// pipe elbow, red/blue horseshoe, gold+cyan two-line title. Replaces the single baked
	// max_win_screen.webp board, which was the last tier still on the pre-Version2 art.
	winSignMaxPlate:   { type: 'sprite', src: './assets/components/win_boards/sign_max_plate.webp?v=20260811' },
	winSignMaxPillarL: { type: 'sprite', src: './assets/components/win_boards/sign_max_pillar_left.webp?v=20260811' },
	winSignMaxPillarR: { type: 'sprite', src: './assets/components/win_boards/sign_max_pillar_right.webp?v=20260811' },
	winSignMaxMagnet:  { type: 'sprite', src: './assets/components/win_boards/sign_max_magnet.webp?v=20260811' },
	winSignTextMax:    { type: 'sprite', src: './assets/components/win_boards/sign_text_max.webp?v=20260811' },
	// The seven stackAnim* sheets are GONE (2026-09-02). They were 36-frame charging loops built from
	// Kling videos of the PRE-REBUILD symbols, so once the set was redrawn a locked stack of, say,
	// astronauts came up as the old blue coil springs. Nothing replaces them: a locked cluster now
	// draws the same layered art as any other cell, unanimated -- the perimeter electricity is what
	// marks it. Their files under static/assets/sprites/stackAnims are deleted too (1.7 MB).
	silverFont: {
		type: 'font',
		src: './assets/fonts/silverFont/mm_silver.xml?v=20260611',
	},
	transition: {
		type: 'spine',
		src: {
			atlas: './assets/spines/transition/transition.atlas',
			skeleton: './assets/spines/transition/transition.json',
			scale: 2,
		},
	},
	coins: {
		type: 'spriteSheet',
		src: './assets/sprites/coin/SD2_Coin.json?v=20260624',
	},
	sound: {
		type: 'audio',
		src: './assets/audio/sounds.json?v=20260730n',
	},
} as const;

// ─────────────────────────────────────────────────────────────────────────────────────────────
// Load tiers. Every entry above is UNFLAGGED by default, which means it belongs to the gating
// pass: it downloads on the loading screen and the progress bar counts it. That default is the
// point — previously all 136 entries carried `preload: true`, which is a different tier entirely
// (it blocks before the game tree mounts AND before the progress bar starts counting), so players
// watched a frozen 0% bar through ~62MB and only saw motion over the last few files.
//
//   preload      – needed to DRAW the loading screen itself. Keep this list tiny.
//   (unflagged)  – base-game art. Gates `loaded`; the bar reflects it honestly.
//   defer        – loads in the background after `loaded`; safe only for art that cannot be
//                  drawn immediately (here: the layout the player did not start in).
//   deferDemand  – withheld until game code calls loadDemandAssets(); see game/utils.ts.
// ─────────────────────────────────────────────────────────────────────────────────────────────

type AssetFlags = { preload?: boolean; defer?: boolean; deferDemand?: boolean };
const flag = (keys: readonly string[], prop: keyof AssetFlags) => {
	for (const key of keys) {
		const entry = (assets as Record<string, AssetFlags | undefined>)[key];
		if (entry) entry[prop] = true;
	}
};

// The loading screen itself is pure HTML now (SplashIntro's `loading` phase — an inline-SVG Press
// Play mark over the room backdrop, which app.html <link rel=preload>s), so it needs nothing from
// this list to paint. The studio mark stays here only because it is the first thing the game tree
// draws once the splash hands over. The old `loadingBarAnim` sheet went with the bar it animated.
flag(['pressPlayLogo'], 'preload');

// Bonus-only art. game/utils.ts gates the drawing events (freeSpinTrigger / freeSpinEnd /
// createBonusSnapshot) on loadDemandAssets(), which covers every entry path — natural scatter, a
// bought DROP-O-MAGNET / MEGA CHAIN round, an activated FEATURE round, and a resumed round.
//
// Flagged BOTH: it streams in the background wave AND stays behind the demand gate. It used to be
// demand-only, which meant the first bonus of a session — the thing a reviewer goes looking for
// almost immediately — paid a ~720KB download before it could be drawn. Streaming it costs the
// loading screen nothing (the gating pass does not wait on it) and by the time anyone reaches a
// bonus it is already resident, so the gate resolves against the cache. The gate stays because it
// is the only hard guarantee for a player who buys a bonus before the stream finishes.
//
// Priority 2: behind the stack anims, which a cluster can need on the very first spin.
flag(
	[
		'bgBonus', 'bgSuper', 'bgMobileBonus', 'bgMobileSuper',
		'fsWonFrame',
		'transition', 'counterFrame',
	],
	'deferDemand',
);
flag(
	[
		'bgBonus', 'bgSuper', 'bgMobileBonus', 'bgMobileSuper',
		'fsWonFrame',
		'transition', 'counterFrame',
	],
	'defer',
);
for (const key of ['bgBonus', 'bgSuper', 'bgMobileBonus', 'bgMobileSuper', 'fsWonFrame', 'transition', 'counterFrame']) {
	const entry = (assets as Record<string, { deferPriority?: number } | undefined>)[key];
	if (entry) entry.deferPriority = 2;
}

// Layout-specific art: only the set matching the INITIAL viewport gates playability; the other
// layout's set is demoted to the background pass, so a later rotate/resize still works — worst
// case the alternate art streams in a moment after the rotate. Mirrors layoutType() in
// utils-layout/createLayout.svelte.ts (portrait = ratio <= 0.8; landscape = short side <= 480).
//
// NOTE: the desktop symbol tiles are deliberately NOT in DESKTOP_ONLY_KEYS. MOBILE_STATIC_KEYS /
// MOBILE_WIN_KEYS in game/utils.ts are Partial records that fall back to the desktop key, so the
// desktop set has to be present in every layout.
//
// Nor are the LOOSE SYMBOL PARTS -- the scatter's alien/eye/dome/word, the battery cell, and every
// magnet/compass/em/portal/astronaut/circuit layer. They are layout-independent: <ScatterSymbol>,
// <BatterySymbol>, <MagnetSymbol>, <CompassSymbol>, <LightningSymbol>, <PortalSymbol>, <CoilSymbol>,
// <CircuitSymbol> and <EmDeviceSymbol> place
// them by fractions of the symbol box, so the same crops serve portrait, landscape and desktop
// alike. Listing them here deferred them on DESKTOP only, and a desktop boot logged a wall of
// "key ... is not found in loadedAssets" while every layered symbol drew as a bare shell -- a
// compass with no face, a device with no antennae -- until the background pass caught up. They are
// ~350KB in total; they belong in the gating pass.
const MOBILE_ONLY_KEYS: readonly string[] = [
	'bgMobileBase', 'smallPadMobile',
	// Portrait symbol art
	'aTileMobile', 'aWinTileMobile', 'kTileMobile', 'kWinTileMobile',
	'qTileMobile', 'qWinTileMobile', 'squirrelTileMobile', 'squirrelWinTileMobile',
	'foxTileMobile', 'foxWinTileMobile', 'wolfTileMobile', 'wolfWinTileMobile',
	'bearTileMobile', 'bearWinTileMobile', 'rabbitTileMobile', 'rabbitWinTileMobile',
	'wildTileMobile', 'wildWinTileMobile',
	'wild2xTileMobile', 'wild3xTileMobile', 'wild4xTileMobile', 'wild5xTileMobile',
	'wild7xTileMobile', 'wild9xTileMobile', 'wild10xTileMobile',
	'scatterCustomMobile', 'scatterWinMobile',
	// Mobile-landscape symbol art
	'foxTileLand', 'foxWinTileLand', 'wolfTileLand', 'wolfWinTileLand',
	'bearTileLand', 'bearWinTileLand', 'rabbitTileLand', 'rabbitWinTileLand',
	'squirrelTileLand', 'squirrelWinTileLand',
	'aTileLand', 'aWinTileLand', 'kTileLand', 'kWinTileLand', 'qTileLand', 'qWinTileLand',
	'wildTileLand', 'scatterTileLand',
	'wild2xTileLand', 'wild3xTileLand', 'wild4xTileLand', 'wild5xTileLand',
	'wild7xTileLand', 'wild9xTileLand', 'wild10xTileLand',
];
// Nothing here at present. Both entries that used to live in this list are gone with the MOTHERSHIP
// redesign: the board plate is drawn (game/boardStyle.ts) and the magnet capsule was removed, so no
// layout loads a texture for either.
const DESKTOP_ONLY_KEYS: readonly string[] = [];

if (typeof window !== 'undefined') {
	const w = window.innerWidth;
	const h = window.innerHeight;
	const isMobileLayout = w / (h || 1) <= 0.8 || Math.min(w, h) <= 480;
	flag(isMobileLayout ? DESKTOP_ONLY_KEYS : MOBILE_ONLY_KEYS, 'defer');
}

export default assets;
