// Emissive strips in each room background, so Background.svelte can LIGHT them instead of
// leaving the room a still painting (the Stake review's "low quality resources" is partly
// that nothing in the scene moves between spins).
//
// GENERATED by scripts/build-room-art.py -- do not hand-edit. The lamps are keyed by colour
// (the terrace's sill lights are one saturated magenta, unique in a lilac landscape) and
// measured on the FINISHED background, so the fractions stay valid for whatever crop that
// script produces. Each room is keyed on its own painting -- they are four different
// paintings of the same terrace, not four tints of one.
export type BackgroundLight = { cx: number; cy: number; w: number; h: number; color: number };

export const BACKGROUND_LIGHTS: Record<string, BackgroundLight[]> = {
	bgBase: [
		{ cx: 0.5228, cy: 0.9122, w: 0.1556, h: 0.04, color: 0xc200ff },
		{ cx: 0.7606, cy: 0.5878, w: 0.0262, h: 0.0556, color: 0xcc00ff },
		{ cx: 0.9213, cy: 0.5667, w: 0.012, h: 0.0333, color: 0xb900ff },
		{ cx: 0.1775, cy: 0.5744, w: 0.012, h: 0.0222, color: 0xb900ff },
	],
	bgMobileBase: [
		{ cx: 0.4964, cy: 0.8659, w: 0.2118, h: 0.0172, color: 0xc400ff },
		{ cx: 0.8144, cy: 0.7292, w: 0.0395, h: 0.0254, color: 0xd500ff },
		{ cx: 0.0334, cy: 0.7226, w: 0.0153, h: 0.012, color: 0xc800ff },
	],
	bgBonus: [
		{ cx: 0.5253, cy: 0.9522, w: 0.2844, h: 0.0933, color: 0xd300ff },
		{ cx: 0.7922, cy: 0.5861, w: 0.0494, h: 0.0722, color: 0x8c00ff },
		{ cx: 0.8531, cy: 0.595, w: 0.0312, h: 0.09, color: 0x8900ff },
		{ cx: 0.9625, cy: 0.5839, w: 0.0163, h: 0.0678, color: 0x9800ff },
		{ cx: 0.2141, cy: 0.5817, w: 0.0219, h: 0.0633, color: 0x8800ff },
		{ cx: 0.2909, cy: 0.5894, w: 0.0231, h: 0.0789, color: 0xa100ff },
		{ cx: 0.5062, cy: 0.8667, w: 0.16, h: 0.012, color: 0x8900ff },
		{ cx: 0.82, cy: 0.6539, w: 0.012, h: 0.0456, color: 0x8200ff },
		{ cx: 0.1353, cy: 0.5644, w: 0.0131, h: 0.0289, color: 0x8600ff },
	],
	bgMobileBonus: [
		{ cx: 0.9642, cy: 0.7185, w: 0.07, h: 0.1227, color: 0xab00ff },
		{ cx: 0.07, cy: 0.7294, w: 0.0805, h: 0.0756, color: 0x9b00ff },
		{ cx: 0.8692, cy: 0.7495, w: 0.0717, h: 0.038, color: 0x8d00ff },
		{ cx: 0.5089, cy: 0.8725, w: 0.372, h: 0.012, color: 0x9500ff },
		{ cx: 0.1961, cy: 0.7536, w: 0.0362, h: 0.0371, color: 0xa300ff },
		{ cx: 0.9058, cy: 0.7824, w: 0.0129, h: 0.0213, color: 0x8600ff },
	],
	bgSuper: [{ cx: 0.4706, cy: 0.9328, w: 0.2162, h: 0.0922, color: 0xb800ff }],
	bgMobileSuper: [{ cx: 0.4964, cy: 0.918, w: 0.3132, h: 0.0417, color: 0xb900ff }],
	bgZero: [
		{ cx: 0.5278, cy: 0.9856, w: 0.1731, h: 0.0267, color: 0xe500ff },
		{ cx: 0.9922, cy: 0.6261, w: 0.0144, h: 0.0522, color: 0xc700ff },
		{ cx: 0.2562, cy: 0.685, w: 0.0187, h: 0.0322, color: 0xb700ff },
		{ cx: 0.8072, cy: 0.6767, w: 0.0156, h: 0.0244, color: 0xb800ff },
	],
	bgMobileZero: [
		{ cx: 0.5133, cy: 0.9264, w: 0.2907, h: 0.0322, color: 0xff00f8 },
		{ cx: 0.1554, cy: 0.7896, w: 0.0274, h: 0.014, color: 0xc000ff },
		{ cx: 0.0612, cy: 0.7149, w: 0.0274, h: 0.012, color: 0xc300ff },
		{ cx: 0.8849, cy: 0.7856, w: 0.0242, h: 0.012, color: 0xc000ff },
	],
};
