// Emissive strips in each room background, so Background.svelte can LIGHT them instead of
// leaving the room a still painting (the Stake review's "low quality resources" is partly
// that nothing in the scene moves between spins).
//
// GENERATED by scripts/build-room-art.py -- do not hand-edit. The lamps are keyed by colour
// (every emissive element in this room is the same saturated magenta, unique against the
// lavender walls) and measured on the FINISHED background, so the fractions stay valid for
// whatever crop that script produces. The bonus/super tables are the same strips under each
// room's coloured lamp.
export type BackgroundLight = { cx: number; cy: number; w: number; h: number; color: number };

export const BACKGROUND_LIGHTS: Record<string, BackgroundLight[]> = {
	bgBase: [
		{ cx: 0.6784, cy: 0.2583, w: 0.0406, h: 0.0811, color: 0xa700ff },
		{ cx: 0.3297, cy: 0.2583, w: 0.0406, h: 0.0811, color: 0xab00ff },
		{ cx: 0.5044, cy: 0.1539, w: 0.0462, h: 0.0122, color: 0xb800ff },
		{ cx: 0.7922, cy: 0.9944, w: 0.0544, h: 0.012, color: 0xd500ff },
		{ cx: 0.2, cy: 0.9944, w: 0.0537, h: 0.012, color: 0xd300ff },
		{ cx: 0.0244, cy: 0.9944, w: 0.0488, h: 0.012, color: 0xd300ff },
		{ cx: 0.7175, cy: 0.8978, w: 0.0262, h: 0.0533, color: 0x9f00ff },
		{ cx: 0.29, cy: 0.8983, w: 0.0262, h: 0.0522, color: 0x9800ff },
		{ cx: 0.9806, cy: 0.9944, w: 0.0375, h: 0.012, color: 0xd200ff },
	],
	bgMobileBase: [
		{ cx: 0.8217, cy: 0.2609, w: 0.0749, h: 0.048, color: 0xa700ff },
		{ cx: 0.1804, cy: 0.2609, w: 0.0757, h: 0.0471, color: 0xab00ff },
		{ cx: 0.5008, cy: 0.2, w: 0.0853, h: 0.012, color: 0xb800ff },
		{ cx: 0.8933, cy: 0.6329, w: 0.0491, h: 0.0312, color: 0x9f00ff },
		{ cx: 0.1067, cy: 0.6329, w: 0.0491, h: 0.0303, color: 0x9800ff },
		{ cx: 0.9899, cy: 0.6916, w: 0.0185, h: 0.012, color: 0xcf00ff },
	],
	bgBonus: [
		{ cx: 0.6784, cy: 0.2583, w: 0.0406, h: 0.0811, color: 0xa700f4 },
		{ cx: 0.3297, cy: 0.2583, w: 0.0406, h: 0.0811, color: 0xab00f4 },
		{ cx: 0.5044, cy: 0.1539, w: 0.0462, h: 0.0122, color: 0xb800f4 },
		{ cx: 0.7922, cy: 0.9944, w: 0.0544, h: 0.012, color: 0xd500f4 },
		{ cx: 0.2, cy: 0.9944, w: 0.0537, h: 0.012, color: 0xd300f4 },
		{ cx: 0.0244, cy: 0.9944, w: 0.0488, h: 0.012, color: 0xd300f4 },
		{ cx: 0.7175, cy: 0.8978, w: 0.0262, h: 0.0533, color: 0x9f00f4 },
		{ cx: 0.29, cy: 0.8983, w: 0.0262, h: 0.0522, color: 0x9800f4 },
		{ cx: 0.9806, cy: 0.9944, w: 0.0375, h: 0.012, color: 0xd200f4 },
	],
	bgMobileBonus: [
		{ cx: 0.8217, cy: 0.2609, w: 0.0749, h: 0.048, color: 0xa700f4 },
		{ cx: 0.1804, cy: 0.2609, w: 0.0757, h: 0.0471, color: 0xab00f4 },
		{ cx: 0.5008, cy: 0.2, w: 0.0853, h: 0.012, color: 0xb800f4 },
		{ cx: 0.8933, cy: 0.6329, w: 0.0491, h: 0.0312, color: 0x9f00f4 },
		{ cx: 0.1067, cy: 0.6329, w: 0.0491, h: 0.0303, color: 0x9800f4 },
		{ cx: 0.9899, cy: 0.6916, w: 0.0185, h: 0.012, color: 0xcf00f4 },
	],
	bgSuper: [
		{ cx: 0.6784, cy: 0.2583, w: 0.0406, h: 0.0811, color: 0x4c0093 },
		{ cx: 0.3297, cy: 0.2583, w: 0.0406, h: 0.0811, color: 0x4e0093 },
		{ cx: 0.5044, cy: 0.1539, w: 0.0462, h: 0.0122, color: 0x540093 },
		{ cx: 0.7922, cy: 0.9944, w: 0.0544, h: 0.012, color: 0x610093 },
		{ cx: 0.2, cy: 0.9944, w: 0.0537, h: 0.012, color: 0x610093 },
		{ cx: 0.0244, cy: 0.9944, w: 0.0488, h: 0.012, color: 0x610093 },
		{ cx: 0.7175, cy: 0.8978, w: 0.0262, h: 0.0533, color: 0x490093 },
		{ cx: 0.29, cy: 0.8983, w: 0.0262, h: 0.0522, color: 0x450093 },
		{ cx: 0.9806, cy: 0.9944, w: 0.0375, h: 0.012, color: 0x600093 },
	],
	bgMobileSuper: [
		{ cx: 0.8217, cy: 0.2609, w: 0.0749, h: 0.048, color: 0x4c0093 },
		{ cx: 0.1804, cy: 0.2609, w: 0.0757, h: 0.0471, color: 0x4e0093 },
		{ cx: 0.5008, cy: 0.2, w: 0.0853, h: 0.012, color: 0x540093 },
		{ cx: 0.8933, cy: 0.6329, w: 0.0491, h: 0.0312, color: 0x490093 },
		{ cx: 0.1067, cy: 0.6329, w: 0.0491, h: 0.0303, color: 0x450093 },
		{ cx: 0.9899, cy: 0.6916, w: 0.0185, h: 0.012, color: 0x5f0093 },
	],
};
