import type { RawSymbol, SymbolState, SymbolName } from './types';

// Cells are WIDER than tall so the 7×7 grid matches the blue board-pad's ~1.21 aspect and the
// magnetic symbol art (328×264 ≈ 1.24) reads bigger. Positions/magnet math all derive from these.
export const SYMBOL_W = 114;
export const SYMBOL_H = 94;
export const SYMBOL_SIZE = SYMBOL_H;
export const BOARD_GRID_OFFSET_Y = 0;
export const BOARD_DIMENSIONS = { x: 7, y: 7 };
export const BOARD_SIZES = {
	width: SYMBOL_W * BOARD_DIMENSIONS.x,
	height: SYMBOL_H * BOARD_DIMENSIONS.y,
};

export const BACKGROUND_RATIO = 1920 / 1080;
export const PORTRAIT_BACKGROUND_RATIO = 1242 / 2208;
const PORTRAIT_RATIO = 800 / 1422;
const LANDSCAPE_RATIO = 1600 / 900;
const DESKTOP_RATIO = 1422 / 800;
const DESKTOP_HEIGHT = 800;
const LANDSCAPE_HEIGHT = 900;
const PORTRAIT_HEIGHT = 1422;
export const DESKTOP_MAIN_SIZES = { width: DESKTOP_HEIGHT * DESKTOP_RATIO, height: DESKTOP_HEIGHT };
export const LANDSCAPE_MAIN_SIZES = {
	width: LANDSCAPE_HEIGHT * LANDSCAPE_RATIO,
	height: LANDSCAPE_HEIGHT,
};
export const PORTRAIT_MAIN_SIZES = {
	width: PORTRAIT_HEIGHT * PORTRAIT_RATIO,
	height: PORTRAIT_HEIGHT,
};

export const PAY_SYMBOLS: SymbolName[] = ['H1', 'H2', 'H3', 'H4', 'L1', 'L2', 'L3', 'L4'];
export const PREMIUM_SYMBOLS: SymbolName[] = ['H1', 'H2', 'H3', 'H4'];
export const LOW_SYMBOLS: SymbolName[] = ['L1', 'L2', 'L3', 'L4'];

const baseRows: RawSymbol[][] = [
	['H1', 'H2', 'H3', 'H4', 'L1', 'L2', 'L3'],
	['L4', 'H1', 'H2', 'H3', 'H4', 'L1', 'L2'],
	['L3', 'L4', 'H1', 'H2', 'H3', 'H4', 'L1'],
	['L2', 'L3', 'L4', 'H1', 'H2', 'H3', 'H4'],
	['L1', 'L2', 'L3', 'L4', 'H1', 'H2', 'H3'],
	['H4', 'L1', 'L2', 'L3', 'L4', 'WILD', 'H1'],
	['H3', 'H4', 'L1', 'L2', 'L3', 'L4', 'L4'],
].map((row) =>
	row.map((name) => ({
		name: name as SymbolName,
		wild: name === 'WILD',
		magnet: false,
		scatter: name === 'SCATTER',
	})),
);

export const INITIAL_BOARD = baseRows.map((row) => [...row]);
export const INITIAL_SYMBOL_STATE: SymbolState = 'static';

// Calibrated against the Version2 board render (green-chip core = 0.413 of cell pitch in the
// design; 0.92 measured 0.412 with the canvas-composited art), then taken down 5% on the user's
// final pass once the pads/gaps matched — the design's own symbols vary per piece, and slightly
// smaller read better across the set.
// Every class used to sit at 0.875, which is why the grid read as 49 icons of identical weight:
// nothing told the eye which symbols were worth chasing. Premiums now carry ~13% more cell than
// lows — enough to rank them at a glance, small enough that the pads still frame everything.
// (This is the deliberate flattening noted when the Version2 art landed; it was flagged in the
// 2026-08-11 review pass, so the hierarchy is back.) Specials stay biggest.
export const SYMBOL_SIZE_RATIOS = {
	premium: { width: 0.92, height: 0.92 },
	low: { width: 0.815, height: 0.815 },
	special: { width: 0.95, height: 0.95 },
	multiplierWild: { width: 0.95, height: 0.95 },
} as const;

// Per-asset compensation for padding baked into the ART FILE, so that the class ratio above is the
// ONLY thing that changes a symbol's size on the board.
//
// Without it a symbol's size depends on how tightly its own build script happened to fit the art to
// the 328x264 canvas, which is not a design decision -- it is an accident of ten separate scripts.
// Measured 2026-09-03, the four LOW symbols spanned 0.766 to 0.895 of the cell in height: a 17%
// spread inside one class, on top of the deliberate 13% step between premiums and lows. That is what
// made the lightning badge read a size larger than the chip beside it.
//
// Every value is a fraction of ONE over how much of its file the ASSEMBLED symbol fills on its
// limiting axis, so afterwards every premium reaches 0.92 of the cell on that axis, every low 0.815
// and every special 0.95. Equalising the limiting axis rather than the covered AREA is deliberate:
// area would blow the narrow symbols (the battery's art is 0.56 of the canvas wide) far past the
// cell to make up their missing width.
//
// One value here SHRINKS. The limiting axis is height for every symbol in this set, so equalising
// it leaves a symbol drawn on an unusually WIDE silhouette matching its class in height and
// overhanging it across -- H4's drum measured 0.774 of the cell wide against 0.70-0.72 for the
// other premiums and read a size larger than all of them. The generator caps any symbol more than
// 6% wider than its class median at that median; see THE WIDTH CAP in the script.
// Generated by scripts/measure-symbol-padding.py -- cancels each symbol's own padding
// so the class ratio in SYMBOL_SIZE_RATIOS is the ONLY thing that changes its size,
// then caps any symbol more than 6% wider than its class median at that median.
export const SYMBOL_PAD_SCALE: Record<string, number> = {
	kTile: 1.184, // L3: art fills 0.71w x 0.84h of its file
	kTileLand: 1.184, // L3: art fills 0.71w x 0.84h of its file
	kTileMobile: 1.184, // L3: art fills 0.71w x 0.84h of its file
	kWinTile: 1.184, // L3: art fills 0.71w x 0.84h of its file
	kWinTileLand: 1.184, // L3: art fills 0.71w x 0.84h of its file
	kWinTileMobile: 1.184, // L3: art fills 0.71w x 0.84h of its file
	qTile: 1.048, // L4: art fills 0.78w x 0.95h of its file
	qTileLand: 1.048, // L4: art fills 0.78w x 0.95h of its file
	qTileMobile: 1.048, // L4: art fills 0.78w x 0.95h of its file
	qWinTile: 1.048, // L4: art fills 0.78w x 0.95h of its file
	qWinTileLand: 1.048, // L4: art fills 0.78w x 0.95h of its file
	qWinTileMobile: 1.048, // L4: art fills 0.78w x 0.95h of its file
	rabbitTile: 0.92, // H4: art fills 0.84w x 1.00h of its file
	rabbitTileLand: 0.92, // H4: art fills 0.84w x 1.00h of its file
	rabbitTileMobile: 0.92, // H4: art fills 0.84w x 1.00h of its file
	rabbitWinTile: 0.92, // H4: art fills 0.84w x 1.00h of its file
	rabbitWinTileLand: 0.92, // H4: art fills 0.84w x 1.00h of its file
	rabbitWinTileMobile: 0.92, // H4: art fills 0.84w x 1.00h of its file
};

// SYMBOL_HEAD_OFFSET and SYMBOL_ZAP_OVERRIDE lived here and are GONE (2026-09-03). They positioned
// and sized the per-cell electric burst behind a stacked symbol, and that burst was removed in the
// 2026-08-07 pass -- nothing has imported either table since. Left in place they were worse than
// dead weight: every offset in them was measured against PRE-REBUILD art (the note they carried
// about washer.webp being the purple screw describes a symbol set that no longer exists), so anyone
// reading them while sizing the MOTHERSHIP symbols would be reading numbers for different drawings.
// scripts/measure-symbol-head.py, which generated the first of them, is orphaned by this.

export const SYMBOL_SIZE_OVERRIDE: Record<string, number> = {
	// EMPTY as of 2026-09-03. It used to hold kTile: 1.3 and squirrelTile: 1.1, both written for the
	// PRE-REBUILD art -- slim diagonal screws and bolts whose bounding box was mostly empty corner.
	// The MOTHERSHIP symbols in those slots are a chunky helmet and a chunky battery, so the reason
	// was gone while the numbers stayed, and they were multiplying on top of SYMBOL_PAD_SCALE: the
	// astronaut and the battery were rendering ~10% taller than the rest of the lows.
	//
	// Anything added here again must be justified by SHAPE, not by padding -- padding is what
	// SYMBOL_PAD_SCALE cancels, and a value here silently multiplies it.
};

// createReelForSpinning needs (BOARD_DIMENSIONS.y + 2) symbols per reel:
// one hidden above the mask and one hidden below.
export const SPIN_REEL_LENGTH = BOARD_DIMENSIONS.y + 2; // 9

const SPIN_OPTIONS_SHARED = {
	reelBounceBackSpeed: 0.15,
	reelSpinSpeedBeforeBounce: 4,
	reelPaddingMultiplierNormal: 1.2,
	reelPaddingMultiplierAnticipated: 3,
	reelSpinDelay: 145,
};

// Normal mode only (turbo/super-turbo use FAST/TURBO below). Speeds are 10% lower than the
// previous tuning (1.5 / 2.3 divided by 1.1), so the reels scroll 10% slower.
export const SPIN_OPTIONS_DEFAULT = {
	...SPIN_OPTIONS_SHARED,
	reelPreSpinSpeed: 1.36,
	reelSpinSpeed: 2.09,
	reelBounceSizeMulti: 0.3,
};

export const SPIN_OPTIONS_FAST = {
	...SPIN_OPTIONS_SHARED,
	reelPreSpinSpeed: 3,
	reelSpinSpeed: 4,
	reelBounceSizeMulti: 0.15,
};

export const SPIN_OPTIONS_TURBO = {
	...SPIN_OPTIONS_SHARED,
	reelPreSpinSpeed: 6,
	reelSpinSpeed: 7,
	reelBounceSizeMulti: 0.1,
	reelSpinDelay: 60,
};

// Normal-speed timings run ~69% slower than the original tuning (x1.3 applied twice) — the
// game felt too rushed at normal speed. Turbo (BOARD_MOTION_FAST) is unchanged.
export const BOARD_MOTION_DEFAULT = {
	spin: {
		dropRows: 12,
		fadeOutMs: 0,
		clearGapMs: 0,
		durationMs: 439,
		scaleFrom: 0.98,
		reelDelayMs: 122,
		rowDelayMs: 0,
		bounceMs: 163,
		overshootRows: 0.26,
		lockPulseMs: 0,
	},
	respin: {
		dropRows: 4.8,
		fadeOutMs: 203,
		clearGapMs: 118,
		durationMs: 642,
		scaleFrom: 0.9,
		reelDelayMs: 30,
		rowDelayMs: 30,
		bounceMs: 270,
		overshootRows: 0.18,
		lockPulseMs: 304,
	},
	pulse: {
		magnetMs: 507,
		freshMs: 575,
		winMs: 946,
	},
} as const;

export const BOARD_MOTION_FAST = {
	spin: {
		dropRows: 7,
		fadeOutMs: 0,
		clearGapMs: 0,
		durationMs: 140,
		scaleFrom: 0.96,
		reelDelayMs: 18,
		rowDelayMs: 0,
		bounceMs: 56,
		overshootRows: 0.2,
		lockPulseMs: 0,
	},
	respin: {
		dropRows: 2.2,
		fadeOutMs: 40,
		clearGapMs: 18,
		durationMs: 150,
		scaleFrom: 0.96,
		reelDelayMs: 8,
		rowDelayMs: 6,
		bounceMs: 60,
		overshootRows: 0.12,
		lockPulseMs: 72,
	},
	pulse: {
		magnetMs: 90,
		freshMs: 120,
		winMs: 140,
	},
} as const;

export const SCATTER_LAND_SOUND_MAP = {
	1: 'sfx_scatter_land_first',
	2: 'sfx_scatter_land_more',
	3: 'sfx_scatter_land_more',
	4: 'sfx_scatter_land_more',
	5: 'sfx_scatter_land_more',
} as const;

// Left-rail info plate (FREE SPINS / RESPIN / TOTAL WIN) — MOTHERSHIP design nodes 9051:27157,
// 9051:27159 and 9051:27160, three identical 222x93 plates on a 101px pitch under the logo.
// InfoBox DRAWS the plate now, so the aspect is the design's placement box rather than the aspect of
// a bitmap; the four call sites (desktop rail, mobile landscape, portrait top bar, RespinPanel) all
// read it from here because each used to keep its own copy of the old art's 781/335 and they only
// stayed in step by hand.
export const INFO_BOX_ASPECT = 222 / 93;
// Vertical gap between plates as a fraction of one plate's height (8 of 93 in the design).
export const INFO_BOX_GAP = 8 / 93;
