// GENERATED by scripts/measure-green-lights.py -- do not hand-edit.
//
// The green indicator lamps are painted INTO each symbol plate, so the runtime cannot
// make them blink without being told where they are. Offsets are from the symbol box
// CENTRE and radii are fractions of its WIDTH, so they multiply straight by the box the
// component is drawn at. Re-run the script after any art swap.
// `group` ties points that must light TOGETHER: a bulb is one point in its own group,
// an arc is a chain of points sharing one. Phase the blink by group, not by index, or an
// arc ripples instead of lighting.
export type GreenLight = { dx: number; dy: number; r: number; group: number };

export const GREEN_LIGHTS: Record<string, GreenLight[]> = {
	compass: [
		{ dx: -0.2226, dy: -0.1174, r: 0.0087, group: 0 },
		{ dx: -0.2256, dy: -0.1553, r: 0.0087, group: 0 },
		{ dx: -0.2012, dy: -0.1705, r: 0.0087, group: 0 },
		{ dx: -0.1799, dy: -0.1856, r: 0.0087, group: 0 },
		{ dx: -0.1677, dy: -0.2083, r: 0.0087, group: 0 },
		{ dx: -0.1616, dy: -0.2424, r: 0.0087, group: 0 },
		{ dx: -0.1433, dy: -0.2614, r: 0.0087, group: 0 },
		{ dx: -0.1159, dy: -0.2614, r: 0.0087, group: 0 },
		{ dx: -0.0945, dy: -0.2765, r: 0.0087, group: 0 },
		{ dx: +0.0976, dy: -0.2727, r: 0.0087, group: 1 },
		{ dx: +0.1220, dy: -0.2652, r: 0.0087, group: 1 },
		{ dx: +0.1463, dy: -0.2576, r: 0.0087, group: 1 },
		{ dx: +0.1616, dy: -0.2348, r: 0.0087, group: 1 },
		{ dx: +0.1799, dy: -0.2159, r: 0.0087, group: 1 },
		{ dx: +0.1951, dy: -0.1970, r: 0.0087, group: 1 },
		{ dx: +0.2134, dy: -0.1780, r: 0.0087, group: 1 },
		{ dx: +0.2134, dy: -0.1439, r: 0.0087, group: 1 },
		{ dx: +0.2256, dy: -0.1174, r: 0.0087, group: 1 },
		{ dx: +0.3384, dy: -0.0341, r: 0.0058, group: 2 },
		{ dx: +0.3506, dy: -0.0038, r: 0.0058, group: 2 },
		{ dx: +0.3567, dy: +0.0152, r: 0.0058, group: 2 },
		{ dx: +0.3598, dy: +0.0265, r: 0.0058, group: 2 },
		{ dx: +0.3628, dy: +0.0379, r: 0.0058, group: 2 },
		{ dx: +0.3567, dy: +0.0492, r: 0.0058, group: 2 },
		{ dx: +0.3476, dy: +0.0606, r: 0.0058, group: 2 },
		{ dx: +0.3506, dy: +0.0758, r: 0.0058, group: 2 },
		{ dx: +0.3354, dy: +0.0985, r: 0.0058, group: 2 },
		{ dx: -0.1646, dy: +0.2652, r: 0.0083, group: 3 },
		{ dx: -0.1890, dy: +0.2576, r: 0.0083, group: 3 },
		{ dx: -0.1951, dy: +0.2273, r: 0.0083, group: 3 },
		{ dx: -0.2165, dy: +0.2159, r: 0.0083, group: 3 },
		{ dx: -0.2226, dy: +0.1894, r: 0.0083, group: 3 },
		{ dx: -0.2226, dy: +0.1591, r: 0.0083, group: 3 },
		{ dx: -0.2287, dy: +0.1364, r: 0.0083, group: 3 },
		{ dx: -0.2439, dy: +0.1174, r: 0.0083, group: 3 },
		{ dx: -0.2500, dy: +0.0909, r: 0.0083, group: 3 },
		{ dx: +0.2530, dy: +0.0909, r: 0.0083, group: 4 },
		{ dx: +0.2470, dy: +0.1174, r: 0.0083, group: 4 },
		{ dx: +0.2378, dy: +0.1402, r: 0.0083, group: 4 },
		{ dx: +0.2348, dy: +0.1667, r: 0.0083, group: 4 },
		{ dx: +0.2256, dy: +0.1894, r: 0.0083, group: 4 },
		{ dx: +0.2165, dy: +0.2121, r: 0.0083, group: 4 },
		{ dx: +0.1921, dy: +0.2197, r: 0.0083, group: 4 },
		{ dx: +0.1829, dy: +0.2424, r: 0.0083, group: 4 },
		{ dx: +0.1677, dy: +0.2614, r: 0.0083, group: 4 }
	],
	scatter: [
		{ dx: -0.2317, dy: -0.3902, r: 0.0335, group: 0 },
		{ dx: +0.2317, dy: -0.3902, r: 0.0335, group: 1 },
		{ dx: -0.2256, dy: +0.3769, r: 0.0221, group: 2 },
		{ dx: +0.2256, dy: +0.3769, r: 0.0221, group: 3 }
	],
};
